{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "SqlServer CAHSIONNLSQL1 BRSales",
        "connectionString": "Provider=SQLOLEDB;Data Source=CAHSIONNLSQL1;Initial Catalog=DEV_BRSales;Persist Security Info=false;User ID=CAHSI\\tcrowley;Integrated Security=SSPI",
        "impersonationMode": "impersonateAccount",
        "account": "CAHSI\\tcrowley",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sales",
        "columns": [
          {
            "name": "Shipto",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Shipto"
          },
          {
            "name": "SalesAmt",
            "dataType": "double",
            "sourceColumn": "SalesAmt"
          },
          {
            "name": "GPcommAmt",
            "dataType": "double",
            "sourceColumn": "GPcommAmt"
          },
          {
            "name": "TsTagInd",
            "dataType": "string",
            "sourceColumn": "TsTagInd"
          },
          {
            "name": "FactKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FactKey"
          },
          {
            "name": "SalesDate",
            "dataType": "string",
            "sourceColumn": "SalesDate"
          },
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "LineNumber",
            "dataType": "int64",
            "sourceColumn": "LineNumber"
          },
          {
            "name": "IsrEmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "IsrEmployeeKey"
          },
          {
            "name": "OrderSourceCodeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderSourceCodeKey"
          },
          {
            "name": "DocTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DocTypeKey"
          },
          {
            "name": "LastOrderInd",
            "dataType": "int64",
            "sourceColumn": "LastOrderInd"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          }
        ],
        "partitions": [
          {
            "name": "BRS_TS_Cube",
            "source": {
              "query": "Exec [Fact].Sales_isr 0",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>Exec [Fact].Sales_isr 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales in Period",
            "expression": "SUM([SalesAmt])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Growth%",
            "expression": "if([PY MTD Sales]=0, blank(), [MTD Sales]/[PY MTD Sales]-1)",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "GP in Period",
            "expression": "SUM([GPcommAmt])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD GP Growth%",
            "expression": "if([PY QTD GP]=0,blank(),[QTD GP]-[PY QTD GP])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY QTD GM",
            "expression": "[PY QTD GP]/[PY QTD Sales]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "PY MTD GM",
            "expression": "[PY MTD GP]/[PY MTD Sales]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "YTD GM",
            "expression": "[YTD GP]/[YTD Sales]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "QTD GM",
            "expression": "[QTD GP]/[QTD Sales]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "MTD GM",
            "expression": "[MTD GP]/[MTD Sales]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "PY MTD FACTOR",
            "expression": "MAX(BRS_TS_Config[DayNumber])/MAX(BRS_TS_Config[WorkingDaysMonth])",
            "formatString": "0.0000"
          },
          {
            "name": "MTD Sales",
            "expression": "  CALCULATE([Sales in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))"
          },
          {
            "name": "YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "MTD GP",
            "expression": " CALCULATE([GP in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))"
          },
          {
            "name": "YTD GP",
            "expression": "  CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "PY MTD Sales",
            "expression": "  CALCULATE([Sales in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))"
          },
          {
            "name": "PY MTD GP",
            "expression": " CALCULATE([GP in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))"
          },
          {
            "name": "MTD Sales Growth",
            "expression": " [MTD Sales]-[PY MTD Sales]"
          },
          {
            "name": "MTD GP Growth",
            "expression": " [MTD GP]-[PY MTD GP]"
          },
          {
            "name": "PY YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))"
          },
          {
            "name": "PY YTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))"
          },
          {
            "name": "YTD Sales Growth",
            "expression": " [YTD Sales]-[PY YTD Sales]"
          },
          {
            "name": "YTD GP Growth",
            "expression": " [YTD GP]-[PY YTD GP]"
          },
          {
            "name": "Qty in Period",
            "expression": " sum([Quantity])"
          },
          {
            "name": "MTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))"
          },
          {
            "name": "YTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "PY MTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))"
          },
          {
            "name": "MTD Qty Growth",
            "expression": " [MTD Qty]-[PY MTD Qty]"
          },
          {
            "name": "PY YTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))"
          },
          {
            "name": "QTD Qty Growth",
            "expression": " [QTD Qty]-[PY QTD Qty]"
          },
          {
            "name": "Rolling  3mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-3&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "Rolling  6mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-6&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "Rolling 12mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "Rolling 24mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-24&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "QTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "QTD GP",
            "expression": "  CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "PY QTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))"
          },
          {
            "name": "QTD Sales Growth",
            "expression": " [QTD Sales]-[PY QTD Sales]"
          },
          {
            "name": "QTD Sales Growth%",
            "expression": "if([PY QTD Sales]=0, blank(), [QTD Sales]/[PY QTD Sales]-1)",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "YTD Sales Growth%",
            "expression": "if([PY YTD Sales]=0, blank(), [YTD Sales]/[PY YTD Sales]-1)",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "QTD GP Growth",
            "expression": " [QTD GP]-[PY QTD GP]"
          },
          {
            "name": "PY QTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))"
          },
          {
            "name": "MTD GP Growth%",
            "expression": "if([PY MTD GP]=0,blank(),[MTD GP]-[PY MTD GP])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Growth%",
            "expression": "if([PY YTD GP]=0,blank(),[YTD GP]-[PY YTD GP])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))"
          },
          {
            "name": "PY QTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))"
          },
          {
            "name": "YTD Qty Growth",
            "expression": " [YTD Qty]-[PY YTD Qty]"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_TS_Cube"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "Exec [Fact].Sales_isr 0"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>Exec [Fact].Sales_isr 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Periods",
        "columns": [
          {
            "name": "Period",
            "dataType": "int64",
            "sourceColumn": "Period"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Qtr",
            "dataType": "int64",
            "sourceColumn": "Qtr"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "WorkingDays",
            "dataType": "int64",
            "sourceColumn": "WorkingDays"
          },
          {
            "name": "PeriodID",
            "dataType": "int64",
            "sourceColumn": "PeriodID"
          },
          {
            "name": "FirstPeriodInYear",
            "dataType": "int64",
            "sourceColumn": "FirstPeriodInYear"
          },
          {
            "name": "FirstPeriodInQtr",
            "dataType": "int64",
            "sourceColumn": "FirstPeriodInQtr"
          },
          {
            "name": "BeginDt",
            "dataType": "dateTime",
            "sourceColumn": "BeginDt",
            "formatString": "General Date"
          },
          {
            "name": "EndDt",
            "dataType": "dateTime",
            "sourceColumn": "EndDt",
            "formatString": "General Date"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          }
        ],
        "partitions": [
          {
            "name": "Periods",
            "source": {
              "query": "SELECT [dbo].[BRS_TS_Period].* \t\tFROM [dbo].[BRS_TS_Period]",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_TS_Period"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[BRS_TS_Period].*   FROM [dbo].[BRS_TS_Period] "
          }
        ]
      },
      {
        "name": "BRS_TS_Config",
        "columns": [
          {
            "name": "SalesDateLastWeekly",
            "dataType": "dateTime",
            "sourceColumn": "SalesDateLastWeekly",
            "formatString": "General Date"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth"
          },
          {
            "name": "PriorFiscalMonth",
            "dataType": "int64",
            "sourceColumn": "PriorFiscalMonth"
          },
          {
            "name": "FirstFiscalMonth_LY",
            "dataType": "int64",
            "sourceColumn": "FirstFiscalMonth_LY"
          },
          {
            "name": "DayType",
            "dataType": "string",
            "sourceColumn": "DayType"
          },
          {
            "name": "DayNumber",
            "dataType": "int64",
            "sourceColumn": "DayNumber"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "sourceColumn": "WorkingDaysMonth"
          }
        ],
        "partitions": [
          {
            "name": "BRS_TS_Config",
            "source": {
              "query": "SELECT [dbo].[BRS_TS_Config].* \t\tFROM [dbo].[BRS_TS_Config]",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sum of FiscalMonth",
            "expression": "SUM('BRS_TS_Config'[FiscalMonth])"
          },
          {
            "name": "Sum of PriorFiscalMonth",
            "expression": "SUM('BRS_TS_Config'[PriorFiscalMonth])"
          },
          {
            "name": "Sum of FirstFiscalMonth_LY",
            "expression": "SUM('BRS_TS_Config'[FirstFiscalMonth_LY])"
          },
          {
            "name": "Sum of DayNumber",
            "expression": "SUM('BRS_TS_Config'[DayNumber])"
          },
          {
            "name": "Sum of WorkingDaysMonth",
            "expression": "SUM('BRS_TS_Config'[WorkingDaysMonth])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_TS_Config"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "      SELECT [dbo].[BRS_TS_Config].*   FROM [dbo].[BRS_TS_Config] "
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "ShipTo",
            "dataType": "int64",
            "sourceColumn": "ShipTo"
          },
          {
            "name": "Billto",
            "dataType": "int64",
            "sourceColumn": "Billto"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer"
          },
          {
            "name": "CustomerGroup",
            "dataType": "string",
            "sourceColumn": "CustomerGroup"
          },
          {
            "name": "SalesPlan",
            "dataType": "string",
            "sourceColumn": "SalesPlan"
          },
          {
            "name": "FieldSales",
            "dataType": "string",
            "sourceColumn": "FieldSales"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "Province",
            "dataType": "string",
            "sourceColumn": "Province"
          },
          {
            "name": "SalesDivision",
            "dataType": "string",
            "sourceColumn": "SalesDivision"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment"
          },
          {
            "name": "Specialty",
            "dataType": "string",
            "sourceColumn": "Specialty"
          },
          {
            "name": "CustomerStatus",
            "dataType": "string",
            "sourceColumn": "CustomerStatus"
          },
          {
            "name": "Focus",
            "dataType": "string",
            "sourceColumn": "Focus"
          },
          {
            "name": "DateAccountOpened",
            "dataType": "string",
            "sourceColumn": "DateAccountOpened"
          },
          {
            "name": "PhoneNumber",
            "dataType": "string",
            "sourceColumn": "PhoneNumber"
          },
          {
            "name": "IsrName",
            "dataType": "string",
            "sourceColumn": "IsrName"
          },
          {
            "name": "SalesChannel",
            "dataType": "string",
            "sourceColumn": "SalesChannel"
          },
          {
            "name": "TargetAmount",
            "dataType": "double",
            "sourceColumn": "TargetAmount"
          },
          {
            "name": "PotentialSpendAmount",
            "dataType": "double",
            "sourceColumn": "PotentialSpendAmount"
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "source": {
              "query": [
                "SELECT",
                "  Dimension.Customer.ShipTo",
                "  ,Dimension.Customer.Billto",
                "  ,Dimension.Customer.Customer",
                "  ,Dimension.Customer.CustomerGroup",
                "  ,Dimension.Customer.SalesPlan",
                "  ,Dimension.Customer.FieldSales",
                "  ,Dimension.Customer.Branch",
                "  ,Dimension.Customer.City",
                "  ,Dimension.Customer.Province",
                "  ,Dimension.Customer.PhoneNumber",
                "  ,Dimension.Customer.SalesDivision",
                "  ,Dimension.Customer.MarketClass",
                "  ,Dimension.Customer.Segment",
                "  ,Dimension.Customer.Specialty",
                "  ,Dimension.Customer.CustomerStatus",
                "  ,Dimension.Customer.Focus",
                "  ,Dimension.Customer.DateAccountOpened",
                "  ,Dimension.Customer.IsrName",
                "  ,Dimension.Customer.SalesChannel",
                "  ,Dimension.Customer.TargetAmount",
                "  ,Dimension.Customer.PotentialSpendAmount",
                "FROM",
                "  Dimension.Customer"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Customer.ShipTo",
                  "  ,Dimension.Customer.Billto",
                  "  ,Dimension.Customer.Customer",
                  "  ,Dimension.Customer.CustomerGroup",
                  "  ,Dimension.Customer.SalesPlan",
                  "  ,Dimension.Customer.FieldSales",
                  "  ,Dimension.Customer.Branch",
                  "  ,Dimension.Customer.City",
                  "  ,Dimension.Customer.Province",
                  "  ,Dimension.Customer.PhoneNumber",
                  "  ,Dimension.Customer.SalesDivision",
                  "  ,Dimension.Customer.MarketClass",
                  "  ,Dimension.Customer.Segment",
                  "  ,Dimension.Customer.Specialty",
                  "  ,Dimension.Customer.CustomerStatus",
                  "  ,Dimension.Customer.Focus",
                  "  ,Dimension.Customer.DateAccountOpened",
                  "  ,Dimension.Customer.IsrName",
                  "  ,Dimension.Customer.SalesChannel",
                  "  ,Dimension.Customer.TargetAmount",
                  "  ,Dimension.Customer.PotentialSpendAmount",
                  "FROM",
                  "  Dimension.Customer</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Customer.ShipTo",
              "  ,Dimension.Customer.Billto",
              "  ,Dimension.Customer.Customer",
              "  ,Dimension.Customer.CustomerGroup",
              "  ,Dimension.Customer.SalesPlan",
              "  ,Dimension.Customer.FieldSales",
              "  ,Dimension.Customer.Branch",
              "  ,Dimension.Customer.City",
              "  ,Dimension.Customer.Province",
              "  ,Dimension.Customer.PhoneNumber",
              "  ,Dimension.Customer.SalesDivision",
              "  ,Dimension.Customer.MarketClass",
              "  ,Dimension.Customer.Segment",
              "  ,Dimension.Customer.Specialty",
              "  ,Dimension.Customer.CustomerStatus",
              "  ,Dimension.Customer.Focus",
              "  ,Dimension.Customer.DateAccountOpened",
              "  ,Dimension.Customer.IsrName",
              "  ,Dimension.Customer.SalesChannel",
              "  ,Dimension.Customer.TargetAmount",
              "  ,Dimension.Customer.PotentialSpendAmount",
              "FROM",
              "  Dimension.Customer"
            ]
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Customer.ShipTo",
              "  ,Dimension.Customer.Billto",
              "  ,Dimension.Customer.Customer",
              "  ,Dimension.Customer.CustomerGroup",
              "  ,Dimension.Customer.SalesPlan",
              "  ,Dimension.Customer.FieldSales",
              "  ,Dimension.Customer.Branch",
              "  ,Dimension.Customer.City",
              "  ,Dimension.Customer.Province",
              "  ,Dimension.Customer.PhoneNumber",
              "  ,Dimension.Customer.SalesDivision",
              "  ,Dimension.Customer.MarketClass",
              "  ,Dimension.Customer.Segment",
              "  ,Dimension.Customer.Specialty",
              "  ,Dimension.Customer.CustomerStatus",
              "  ,Dimension.Customer.Focus",
              "  ,Dimension.Customer.DateAccountOpened",
              "  ,Dimension.Customer.IsrName",
              "  ,Dimension.Customer.SalesChannel",
              "  ,Dimension.Customer.TargetAmount",
              "  ,Dimension.Customer.PotentialSpendAmount",
              "FROM",
              "  Dimension.Customer</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period",
        "columns": [
          {
            "name": "SalesDate",
            "dataType": "string",
            "sourceColumn": "SalesDate",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DaySeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DaySeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "DayNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DayNumber",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "DayType",
            "dataType": "string",
            "sourceColumn": "DayType",
            "sourceProviderType": "Char"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "sourceColumn": "MonthNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName",
            "sourceProviderType": "Char"
          },
          {
            "name": "YearNum",
            "dataType": "int64",
            "sourceColumn": "YearNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "sourceColumn": "WorkingDaysMonth",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthSeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthSeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInQtr",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInYear",
            "sourceProviderType": "SmallInt"
          }
        ],
        "partitions": [
          {
            "name": "Day",
            "dataView": "full",
            "source": {
              "query": " SELECT [Dimension].[Day].* FROM [Dimension].[Day] ",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Day].* FROM [Dimension].[Day] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Day"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Period Select",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "SalesDate",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[SalesDate]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DaySeq",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[DaySeq]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[DayNumber]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayType",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[DayType]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FiscalMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[FiscalMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[MonthName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[MonthNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "QuarterName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[QuarterName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[YearNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[WorkingDaysMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthSeq",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[MonthSeq]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[FirstMonthSeqInQtr]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[FirstMonthSeqInYear]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "'Period'"
            }
          }
        ],
        "measures": [
          {
            "name": "__first_month_current",
            "expression": " max('Period Select'[FiscalMonth])",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_current",
            "expression": " calculate(max('Period Select'[MonthSeq]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_year",
            "expression": "  calculate(max('Period Select'[FirstMonthSeqInYear]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_quarter",
            "expression": " calculate(max('Period Select'[FirstMonthSeqInQtr]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__first_month_number",
            "expression": " calculate(max('Period Select'[MonthNum]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__ytd_factor",
            "expression": " 1",
            "isHidden": true
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "f12077bd-e88c-477b-85f6-de7c043d1647",
        "fromTable": "Sales",
        "fromColumn": "Shipto",
        "toTable": "Customer",
        "toColumn": "ShipTo"
      }
    ],
    "roles": [
      {
        "name": "TS_User_Roll",
        "modelPermission": "read"
      }
    ]
  },
  "id": "SemanticModel"
}