{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "SqlServer CAHSIONNLSQL1 BRSales",
        "connectionString": "Provider=SQLOLEDB;Data Source=CAHSIONNLSQL1;Initial Catalog=BRSales;Persist Security Info=false;User ID=CAHSI\\tcrowley;Integrated Security=SSPI",
        "impersonationMode": "impersonateAccount",
        "account": "CAHSI\\tcrowley",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sales",
        "columns": [
          {
            "name": "Shipto",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Shipto"
          },
          {
            "name": "SalesAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesAmt"
          },
          {
            "name": "GPcommAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GPcommAmt"
          },
          {
            "name": "TsTagInd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TsTagInd"
          },
          {
            "name": "FactKey",
            "dataType": "int64",
            "sourceColumn": "FactKey"
          },
          {
            "name": "SalesDate",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalesDate"
          },
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "LineNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LineNumber"
          },
          {
            "name": "IsrEmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "IsrEmployeeKey"
          },
          {
            "name": "OrderSourceCodeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderSourceCodeKey"
          },
          {
            "name": "DocTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DocTypeKey"
          },
          {
            "name": "LastOrderInd",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LastOrderInd"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Quantity"
          },
          {
            "type": "calculated",
            "name": "Tag Status",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "if([TsTagInd],\"TS Tagged\", \"TS Not Tagged\") "
          }
        ],
        "partitions": [
          {
            "name": "BRS_TS_Cube",
            "source": {
              "type": "query",
              "query": "Exec [Fact].Sales_isr 0",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>Exec [Fact].Sales_isr 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales in Period",
            "expression": "SUM([SalesAmt])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Growth%",
            "expression": "DIVIDE( [MTD Sales Growth], [PY MTD Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "GP in Period",
            "expression": "SUM([GPcommAmt])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD GP Growth%",
            "expression": "DIVIDE([QTD GP Growth], [PY QTD GP], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true
          },
          {
            "name": "PY QTD GM",
            "expression": "DIVIDE([PY QTD GP],[PY QTD Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY MTD GM",
            "expression": "DIVIDE([PY MTD GP], [PY MTD Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD GM",
            "expression": "DIVIDE([YTD GP],[YTD Sales],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD GM",
            "expression": "DIVIDE([QTD GP], [QTD Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true
          },
          {
            "name": "MTD GM",
            "expression": "DIVIDE([MTD GP],[MTD Sales],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Sales",
            "expression": "  CALCULATE([Sales in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP",
            "expression": " CALCULATE([GP in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP",
            "expression": "  CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Sales",
            "expression": "  CALCULATE([Sales in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12* [__year_factor])))*[__mtd_factor]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD GP",
            "expression": " CALCULATE([GP in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12* [__year_factor])))*[__mtd_factor]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Growth",
            "expression": " [MTD Sales]-[PY MTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Growth",
            "expression": " [MTD GP]-[PY MTD GP]"
          },
          {
            "name": "PY YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])-1))+[PY MTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])-1))+[PY MTD GP]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Growth",
            "expression": " [YTD Sales]-[PY YTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Growth",
            "expression": " [YTD GP]-[PY YTD GP]"
          },
          {
            "name": "Qty in Period",
            "expression": " sum([Quantity])",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "MTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "YTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY MTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12* [__year_factor])))*[__mtd_factor]",
            "formatString": "#,0"
          },
          {
            "name": "MTD Qty Growth",
            "expression": " [MTD Qty]-[PY MTD Qty]",
            "formatString": "#,0"
          },
          {
            "name": "PY YTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])-1))+[PY MTD Qty]",
            "formatString": "#,0"
          },
          {
            "name": "QTD Qty Growth",
            "expression": " [QTD Qty]-[PY QTD Qty]",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Last 3Mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-3&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD GP",
            "expression": "  CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY QTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])-1))+[PY MTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Sales Growth",
            "expression": " [QTD Sales]-[PY QTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Sales Growth%",
            "expression": "DIVIDE([QTD Sales Growth], [PY QTD Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true
          },
          {
            "name": "YTD Sales Growth%",
            "expression": "DIVIDE( [YTD Sales Growth], [PY YTD Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD GP Growth",
            "expression": " [QTD GP]-[PY QTD GP]",
            "isHidden": true
          },
          {
            "name": "PY QTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])-1))+[PY MTD GP]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Growth%",
            "expression": "DIVIDE([MTD GP Growth],[PY MTD GP], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD GP Growth%",
            "expression": "DIVIDE([YTD GP Growth], [PY YTD GP], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "PY QTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])-1))+[PY MTD Qty]",
            "formatString": "#,0"
          },
          {
            "name": "YTD Qty Growth",
            "expression": " [YTD Qty]-[PY YTD Qty]",
            "formatString": "#,0"
          },
          {
            "name": "PY YTD GM",
            "expression": "DIVIDE([PY YTD GP], [PY YTD Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Last 3Mo GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-3&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY Last 3Mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-3-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY Last 3Mo GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-3-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 3Mo Sales Growth",
            "expression": " [Last 3Mo Sales]-[PY Last 3Mo Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 3Mo Sales Growth%",
            "expression": "DIVIDE([Last 3Mo Sales Growth],  [PY Last 3Mo Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Last 3Mo GP Growth",
            "expression": " [Last 3Mo GP]-[PY Last 3Mo GP]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 3Mo GP Growth%",
            "expression": "DIVIDE( [Last 3Mo GP Growth], [PY Last 3Mo GP], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "WTD Sales",
            "expression": "  CALCULATE([Sales in Period],filter(Period, Period[FirstWeekSeqInDay]=[__seq_first_week_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 6Mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-6&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 12Mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 3Mo Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-3&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "Last 6Mo Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-6&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "Last 12Mo Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "Last 6Mo Sales Growth",
            "expression": " [Last 6Mo Sales]-[PY Last 6Mo Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 6Mo Sales Growth%",
            "expression": "DIVIDE([Last 6Mo Sales Growth],  [PY Last 6Mo Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY Last 6Mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-6-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY Last 12Mo Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12-(12* [__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12* [__year_factor])))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 12Mo Sales Growth",
            "expression": " [Last 12Mo Sales]-[PY Last 12Mo Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Last 12Mo Sales Growth%",
            "expression": "DIVIDE([Last 12Mo Sales Growth], [PY Last 12Mo Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Last Order Qty",
            "expression": " CALCULATE([Qty in Period],'sales'[Lastorderind]=1)",
            "formatString": "#,0"
          },
          {
            "name": "Last Order Date",
            "expression": " CALCULATE([Last Date in Period] ,'sales'[Lastorderind]=1)",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Last Date in Period",
            "expression": " max('Sales'[SalesDate])",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "WTD GP",
            "expression": "  CALCULATE([gp in Period],filter(Period, Period[FirstWeekSeqInDay]=[__seq_first_week_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "WTD GM",
            "expression": "DIVIDE([WTD GP], [WTD Sales], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "WTD Qty",
            "expression": "  CALCULATE([Qty in Period],filter(Period, Period[FirstWeekSeqInDay]=[__seq_first_week_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Percent to Goal",
            "expression": "DIVIDE( [MTD Sales], [MTD Goal])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Goal Growth Factor",
            "expression": "1.1",
            "isHidden": true
          },
          {
            "name": "MTD Goal",
            "expression": "[Last 12Mo Sales]*[Goal Growth Factor]/12",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_TS_Cube"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "Exec [Fact].Sales_isr 0"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>Exec [Fact].Sales_isr 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "ShipTo",
            "dataType": "int64",
            "sourceColumn": "ShipTo"
          },
          {
            "name": "Billto",
            "dataType": "int64",
            "sourceColumn": "Billto"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer"
          },
          {
            "name": "CustomerGroup",
            "dataType": "string",
            "sourceColumn": "CustomerGroup"
          },
          {
            "name": "SalesPlan",
            "dataType": "string",
            "sourceColumn": "SalesPlan"
          },
          {
            "name": "FieldSales",
            "dataType": "string",
            "sourceColumn": "FieldSales"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch"
          },
          {
            "name": "Province",
            "dataType": "string",
            "sourceColumn": "Province"
          },
          {
            "name": "SalesDivision",
            "dataType": "string",
            "sourceColumn": "SalesDivision"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass"
          },
          {
            "name": "Specialty",
            "dataType": "string",
            "sourceColumn": "Specialty"
          },
          {
            "name": "CustomerStatus",
            "dataType": "string",
            "sourceColumn": "CustomerStatus"
          },
          {
            "name": "DateAccountOpened",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DateAccountOpened"
          },
          {
            "name": "PhoneNumber",
            "dataType": "string",
            "sourceColumn": "PhoneNumber"
          },
          {
            "name": "InsideSales",
            "dataType": "string",
            "sourceColumn": "IsrName"
          },
          {
            "name": "SalesChannel",
            "dataType": "string",
            "sourceColumn": "SalesChannel"
          },
          {
            "name": "Sales Target Year",
            "dataType": "double",
            "sourceColumn": "TargetAmount",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "IsrEmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "IsrEmployeeKey"
          },
          {
            "name": "FocusCd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FocusCd"
          },
          {
            "name": "CreditLimit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CreditLimit"
          },
          {
            "type": "calculated",
            "name": "CreditRisk",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "if(Customer[CreditLimit]<= 10, \"Yes\", \"No\")"
          },
          {
            "type": "calculated",
            "name": "Sales Target Month",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "[Sales Target Year]/12",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment"
          },
          {
            "name": "PotentialSpendAmount",
            "dataType": "double",
            "sourceColumn": "PotentialSpendAmount"
          },
          {
            "name": "adhoc_model_code",
            "dataType": "string",
            "sourceColumn": "adhoc_model_code"
          },
          {
            "name": "adhoc_model_code2",
            "dataType": "string",
            "sourceColumn": "adhoc_model_code2"
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "  Dimension.Customer.ShipTo",
                "  ,Dimension.Customer.Billto",
                "  ,Dimension.Customer.Customer",
                "  ,Dimension.Customer.CustomerGroup",
                "  ,Dimension.Customer.SalesPlan",
                "  ,Dimension.Customer.FieldSales",
                "  ,Dimension.Customer.Branch",
                "  ,Dimension.Customer.City",
                "  ,Dimension.Customer.Province",
                "  ,Dimension.Customer.PhoneNumber",
                "  ,Dimension.Customer.SalesDivision",
                "  ,Dimension.Customer.MarketClass",
                "  ,Dimension.Customer.Segment",
                "  ,Dimension.Customer.Specialty",
                "  ,Dimension.Customer.CustomerStatus",
                "  ,Dimension.Customer.DateAccountOpened",
                "  ,Dimension.Customer.IsrName",
                "  ,Dimension.Customer.SalesChannel",
                "  ,Dimension.Customer.TargetAmount",
                "  ,Dimension.Customer.PotentialSpendAmount",
                "  ,Dimension.Customer.IsrEmployeeKey",
                " ,FocusCd",
                " ,CreditLimit",
                " ,adhoc_model_code",
                " ,adhoc_model_code2",
                "",
                "FROM",
                "  Dimension.Customer"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Customer.ShipTo",
                  "  ,Dimension.Customer.Billto",
                  "  ,Dimension.Customer.Customer",
                  "  ,Dimension.Customer.CustomerGroup",
                  "  ,Dimension.Customer.SalesPlan",
                  "  ,Dimension.Customer.FieldSales",
                  "  ,Dimension.Customer.Branch",
                  "  ,Dimension.Customer.City",
                  "  ,Dimension.Customer.Province",
                  "  ,Dimension.Customer.PhoneNumber",
                  "  ,Dimension.Customer.SalesDivision",
                  "  ,Dimension.Customer.MarketClass",
                  "  ,Dimension.Customer.Segment",
                  "  ,Dimension.Customer.Specialty",
                  "  ,Dimension.Customer.CustomerStatus",
                  "  ,Dimension.Customer.DateAccountOpened",
                  "  ,Dimension.Customer.IsrName",
                  "  ,Dimension.Customer.SalesChannel",
                  "  ,Dimension.Customer.TargetAmount",
                  "  ,Dimension.Customer.PotentialSpendAmount",
                  "  ,Dimension.Customer.IsrEmployeeKey",
                  " ,FocusCd",
                  " ,CreditLimit",
                  " ,adhoc_model_code",
                  " ,adhoc_model_code2",
                  "",
                  "FROM",
                  "  Dimension.Customer</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "_Count of ShipTo",
            "expression": "COUNTA([ShipTo])",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Customer.ShipTo",
              "  ,Dimension.Customer.Billto",
              "  ,Dimension.Customer.Customer",
              "  ,Dimension.Customer.CustomerGroup",
              "  ,Dimension.Customer.SalesPlan",
              "  ,Dimension.Customer.FieldSales",
              "  ,Dimension.Customer.Branch",
              "  ,Dimension.Customer.City",
              "  ,Dimension.Customer.Province",
              "  ,Dimension.Customer.PhoneNumber",
              "  ,Dimension.Customer.SalesDivision",
              "  ,Dimension.Customer.MarketClass",
              "  ,Dimension.Customer.Segment",
              "  ,Dimension.Customer.Specialty",
              "  ,Dimension.Customer.CustomerStatus",
              "  ,Dimension.Customer.DateAccountOpened",
              "  ,Dimension.Customer.IsrName",
              "  ,Dimension.Customer.SalesChannel",
              "  ,Dimension.Customer.TargetAmount",
              "  ,Dimension.Customer.PotentialSpendAmount",
              "  ,Dimension.Customer.IsrEmployeeKey",
              " ,FocusCd",
              " ,CreditLimit",
              " ,adhoc_model_code",
              " ,adhoc_model_code2",
              "",
              "FROM",
              "  Dimension.Customer"
            ]
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Customer.ShipTo",
              "  ,Dimension.Customer.Billto",
              "  ,Dimension.Customer.Customer",
              "  ,Dimension.Customer.CustomerGroup",
              "  ,Dimension.Customer.SalesPlan",
              "  ,Dimension.Customer.FieldSales",
              "  ,Dimension.Customer.Branch",
              "  ,Dimension.Customer.City",
              "  ,Dimension.Customer.Province",
              "  ,Dimension.Customer.PhoneNumber",
              "  ,Dimension.Customer.SalesDivision",
              "  ,Dimension.Customer.MarketClass",
              "  ,Dimension.Customer.Segment",
              "  ,Dimension.Customer.Specialty",
              "  ,Dimension.Customer.CustomerStatus",
              "  ,Dimension.Customer.DateAccountOpened",
              "  ,Dimension.Customer.IsrName",
              "  ,Dimension.Customer.SalesChannel",
              "  ,Dimension.Customer.TargetAmount",
              "  ,Dimension.Customer.PotentialSpendAmount",
              "  ,Dimension.Customer.IsrEmployeeKey",
              " ,FocusCd",
              " ,CreditLimit",
              " ,adhoc_model_code",
              " ,adhoc_model_code2",
              "",
              "FROM",
              "  Dimension.Customer</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period",
        "columns": [
          {
            "name": "SalesDate",
            "dataType": "string",
            "sourceColumn": "SalesDate",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DaySeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DaySeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "DayNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DayNumber",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "DayType",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DayType",
            "sourceProviderType": "Char"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "sourceColumn": "MonthNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName",
            "sourceProviderType": "Char"
          },
          {
            "name": "YearNum",
            "dataType": "int64",
            "sourceColumn": "YearNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "WorkingDaysMonth",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthSeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthSeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInQtr",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInYear",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstWeekSeqInDay",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstWeekSeqInDay"
          }
        ],
        "partitions": [
          {
            "name": "Day",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "SELECT [Dimension].[Day].* FROM [Dimension].[Day]",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Dimension].[Day].* FROM [Dimension].[Day]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "_Count of Day",
            "expression": "COUNTA([SalesDate])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [Dimension].[Day].* FROM [Dimension].[Day]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Day"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Dimension].[Day].* FROM [Dimension].[Day]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Period Select",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "SalesDate",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[SalesDate]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DaySeq",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[DaySeq]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[DayNumber]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayType",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[DayType]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FiscalMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[FiscalMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "QuarterName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[QuarterName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[YearNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[WorkingDaysMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthSeq",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthSeq]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstMonthSeqInQtr]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstMonthSeqInYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstWeekSeqInDay",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstWeekSeqInDay]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "'Period'"
            }
          }
        ],
        "measures": [
          {
            "name": "__first_month_current",
            "expression": " max('Period Select'[FiscalMonth])",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_current",
            "expression": " calculate(max('Period Select'[MonthSeq]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_year",
            "expression": "  calculate(max('Period Select'[FirstMonthSeqInYear]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_quarter",
            "expression": " calculate(max('Period Select'[FirstMonthSeqInQtr]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__first_month_number",
            "expression": " calculate(max('Period Select'[MonthNum]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__mtd_factor",
            "expression": " [__day_number_current]/[__day_number_working]",
            "formatString": "0.00"
          },
          {
            "name": "__day_number_current",
            "expression": " calculate(max('Period Select'[DayNumber]),filter('Period Select','Period Select'[DaySeq]=[__seq_last_day_current]))",
            "isHidden": true
          },
          {
            "name": "__day_number_working",
            "expression": " calculate(max('Period Select'[WorkingDaysMonth]),filter('Period Select','Period Select'[DaySeq]=[__seq_last_day_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_last_day_current",
            "expression": " max('Period Select'[DaySeq])",
            "isHidden": true
          },
          {
            "name": "__seq_first_week_current",
            "expression": " calculate(max('Period Select'[FirstWeekSeqInDay]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "Current Day",
            "expression": "MAX([SalesDate])",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"4105\" Group=\"LongDate\" FormatString=\"d-MMM-yy\" /></DateTimes></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "EmployeeSecurity",
        "columns": [
          {
            "name": "SamAccountName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SamAccountName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "LoginId",
            "dataType": "string",
            "sourceColumn": "LoginId",
            "sourceProviderType": "WChar"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "IsrRollupCd",
            "dataType": "string",
            "sourceColumn": "IsrRollupCd",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "EmployeeSecurity",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "SELECT [dbo].[BRS_Employee].[SamAccountName],[dbo].[BRS_Employee].[LoginId],[dbo].[BRS_Employee].[EmployeeKey],[dbo].[BRS_Employee].[IsrRollupCd] FROM [dbo].[BRS_Employee] where [BRS_Employee].[IsrRollupCd] is not null",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[BRS_Employee].[SamAccountName],[dbo].[BRS_Employee].[LoginId],[dbo].[BRS_Employee].[EmployeeKey],[dbo].[BRS_Employee].[IsrRollupCd] FROM [dbo].[BRS_Employee] where [BRS_Employee].[IsrRollupCd] is not null</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[BRS_Employee].[SamAccountName],[dbo].[BRS_Employee].[LoginId],[dbo].[BRS_Employee].[EmployeeKey],[dbo].[BRS_Employee].[IsrRollupCd] FROM [dbo].[BRS_Employee] where [BRS_Employee].[IsrRollupCd] is not null"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_Employee"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[BRS_Employee].[SamAccountName],[dbo].[BRS_Employee].[LoginId],[dbo].[BRS_Employee].[EmployeeKey],[dbo].[BRS_Employee].[IsrRollupCd] FROM [dbo].[BRS_Employee] where [BRS_Employee].[IsrRollupCd] is not null</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "CustomerFocus",
        "columns": [
          {
            "name": "FocusCd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FocusCd",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Focus",
            "dataType": "string",
            "sourceColumn": "FocusDescr",
            "sourceProviderType": "WChar"
          },
          {
            "name": "FocusKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FocusKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "CustomerFocus",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_CustomerFocus].[FocusCd],[dbo].[BRS_CustomerFocus].[FocusDescr],[dbo].[BRS_CustomerFocus].[FocusKey] FROM [dbo].[BRS_CustomerFocus] ",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>FocusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FocusDescr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>161</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FocusKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Note</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IsActiveInd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>85</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>FocusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FocusDescr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FocusKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Note</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IsActiveInd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Note</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IsActiveInd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_CustomerFocus].[FocusCd],[dbo].[BRS_CustomerFocus].[FocusDescr],[dbo].[BRS_CustomerFocus].[FocusKey] FROM [dbo].[BRS_CustomerFocus] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_CustomerFocus"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>FocusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FocusDescr</string>",
              "      </key>",
              "      <value>",
              "        <int>161</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FocusKey</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Note</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IsActiveInd</string>",
              "      </key>",
              "      <value>",
              "        <int>85</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>FocusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FocusDescr</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FocusKey</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Note</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IsActiveInd</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Note</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IsActiveInd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Item",
        "columns": [
          {
            "name": "deal_code",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "deal_code"
          },
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey"
          },
          {
            "name": "Item",
            "dataType": "string",
            "sourceColumn": "Item"
          },
          {
            "name": "SalesCategory",
            "dataType": "string",
            "sourceColumn": "SalesCategory"
          },
          {
            "name": "CategoryRollup",
            "dataType": "string",
            "sourceColumn": "CategoryRollup"
          },
          {
            "name": "Major",
            "dataType": "string",
            "sourceColumn": "Major"
          },
          {
            "name": "SubMajor",
            "dataType": "string",
            "sourceColumn": "SubMajor"
          },
          {
            "name": "ItemCode",
            "dataType": "string",
            "sourceColumn": "ItemCode"
          },
          {
            "name": "ItemStatus",
            "dataType": "string",
            "sourceColumn": "ItemStatus"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label"
          },
          {
            "name": "Current_BasePrice",
            "dataType": "double",
            "sourceColumn": "Current_BasePrice"
          },
          {
            "name": "Top15",
            "dataType": "string",
            "sourceColumn": "Top15"
          },
          {
            "name": "SubstItem",
            "dataType": "string",
            "sourceColumn": "SubstItem"
          }
        ],
        "partitions": [
          {
            "name": "Item",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT ",
                "--top 10",
                "\ti.[ItemKey],",
                "\ti.[Item],",
                "\ti.[SalesCategory],",
                "\ti.[CategoryRollup],",
                "\ti.[Major],",
                "\ti.[SubMajor],",
                "\ti.[ItemCode],",
                "\ti.[ItemStatus],",
                "\ti.[Brand],",
                "\ti.[Label],",
                "\ti.[Current_BasePrice],",
                "\ti.Top15,",
                "",
                "\tISNULL(ideal.recID, 0) deal_code,",
                "\t",
                "\tCASE ",
                "\t\tWHEN isub.ItemKey = 1 ",
                "\t\tTHEN ''",
                "\t\tELSE isub.Item",
                "\tEND AS SubstItem",
                "",
                "FROM ",
                "\t[Dimension].[Item] i",
                "",
                "\tLEFT JOIN Redemptions_tbl_Items AS ideal",
                "\tON i.ItemCode = ideal.[ItemNumber]",
                "",
                "\t-- add subst ...",
                "\tINNER JOIN [Dimension].[Item] isub",
                "\tON i.[CompetitiveMatchKey] = isub.[ItemKey]",
                "",
                "WHERE ",
                "\ti.SalesCategoryCode in ('MERCH', 'SMEQU') and",
                "--\tRecID <> 0 AND",
                "--\tisub.itemkey <> 1 AND",
                "\t1=1"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
                  "--top 10",
                  "\ti.[ItemKey],",
                  "\ti.[Item],",
                  "\ti.[SalesCategory],",
                  "\ti.[CategoryRollup],",
                  "\ti.[Major],",
                  "\ti.[SubMajor],",
                  "\ti.[ItemCode],",
                  "\ti.[ItemStatus],",
                  "\ti.[Brand],",
                  "\ti.[Label],",
                  "\ti.[Current_BasePrice],",
                  "\ti.Top15,",
                  "",
                  "\tISNULL(ideal.recID, 0) deal_code,",
                  "\t",
                  "\tCASE ",
                  "\t\tWHEN isub.ItemKey = 1 ",
                  "\t\tTHEN ''",
                  "\t\tELSE isub.Item",
                  "\tEND AS SubstItem",
                  "",
                  "FROM ",
                  "\t[Dimension].[Item] i",
                  "",
                  "\tLEFT JOIN Redemptions_tbl_Items AS ideal",
                  "\tON i.ItemCode = ideal.[ItemNumber]",
                  "",
                  "\t-- add subst ...",
                  "\tINNER JOIN [Dimension].[Item] isub",
                  "\tON i.[CompetitiveMatchKey] = isub.[ItemKey]",
                  "",
                  "WHERE ",
                  "\ti.SalesCategoryCode in ('MERCH', 'SMEQU') and",
                  "--\tRecID <> 0 AND",
                  "--\tisub.itemkey <> 1 AND",
                  "\t1=1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "_Count of Item",
            "expression": "COUNTA([ItemKey])",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT ",
              "--top 10",
              "\ti.[ItemKey],",
              "\ti.[Item],",
              "\ti.[SalesCategory],",
              "\ti.[CategoryRollup],",
              "\ti.[Major],",
              "\ti.[SubMajor],",
              "\ti.[ItemCode],",
              "\ti.[ItemStatus],",
              "\ti.[Brand],",
              "\ti.[Label],",
              "\ti.[Current_BasePrice],",
              "\ti.Top15,",
              "",
              "\tISNULL(ideal.recID, 0) deal_code,",
              "\t",
              "\tCASE ",
              "\t\tWHEN isub.ItemKey = 1 ",
              "\t\tTHEN ''",
              "\t\tELSE isub.Item",
              "\tEND AS SubstItem",
              "",
              "FROM ",
              "\t[Dimension].[Item] i",
              "",
              "\tLEFT JOIN Redemptions_tbl_Items AS ideal",
              "\tON i.ItemCode = ideal.[ItemNumber]",
              "",
              "\t-- add subst ...",
              "\tINNER JOIN [Dimension].[Item] isub",
              "\tON i.[CompetitiveMatchKey] = isub.[ItemKey]",
              "",
              "WHERE ",
              "\ti.SalesCategoryCode in ('MERCH', 'SMEQU') and",
              "--\tRecID <> 0 AND",
              "--\tisub.itemkey <> 1 AND",
              "\t1=1"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Item"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
              "--top 10",
              "\ti.[ItemKey],",
              "\ti.[Item],",
              "\ti.[SalesCategory],",
              "\ti.[CategoryRollup],",
              "\ti.[Major],",
              "\ti.[SubMajor],",
              "\ti.[ItemCode],",
              "\ti.[ItemStatus],",
              "\ti.[Brand],",
              "\ti.[Label],",
              "\ti.[Current_BasePrice],",
              "\ti.Top15,",
              "",
              "\tISNULL(ideal.recID, 0) deal_code,",
              "\t",
              "\tCASE ",
              "\t\tWHEN isub.ItemKey = 1 ",
              "\t\tTHEN ''",
              "\t\tELSE isub.Item",
              "\tEND AS SubstItem",
              "",
              "FROM ",
              "\t[Dimension].[Item] i",
              "",
              "\tLEFT JOIN Redemptions_tbl_Items AS ideal",
              "\tON i.ItemCode = ideal.[ItemNumber]",
              "",
              "\t-- add subst ...",
              "\tINNER JOIN [Dimension].[Item] isub",
              "\tON i.[CompetitiveMatchKey] = isub.[ItemKey]",
              "",
              "WHERE ",
              "\ti.SalesCategoryCode in ('MERCH', 'SMEQU') and",
              "--\tRecID <> 0 AND",
              "--\tisub.itemkey <> 1 AND",
              "\t1=1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Deal",
        "columns": [
          {
            "name": "deal_code",
            "dataType": "int64",
            "sourceColumn": "deal_code",
            "sourceProviderType": "Integer"
          },
          {
            "name": "deal",
            "dataType": "string",
            "sourceColumn": "deal",
            "sourceProviderType": "VarChar"
          }
        ],
        "partitions": [
          {
            "name": "Deal",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\tRecID deal_code,",
                "\tCASE ",
                "\t\tWHEN d.RecID = 0",
                "\t\tTHEN ''",
                "\t\tELSE LEFT('D-' + CAST(d.RecID as char(10)) + CAST(d.Buy AS VARCHAR(255)) + ' >> ' +  CAST(d.Get AS VARCHAR(255)), 255) ",
                "\tEND AS deal",
                "FROM            Redemptions_tbl_Main as d"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "\tRecID deal_code,",
                  "\tCASE ",
                  "\t\tWHEN d.RecID = 0",
                  "\t\tTHEN ''",
                  "\t\tELSE LEFT('D-' + CAST(d.RecID as char(10)) + CAST(d.Buy AS VARCHAR(255)) + ' >> ' +  CAST(d.Get AS VARCHAR(255)), 255) ",
                  "\tEND AS deal",
                  "FROM            Redemptions_tbl_Main as d</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "\tRecID deal_code,",
              "\tCASE ",
              "\t\tWHEN d.RecID = 0",
              "\t\tTHEN ''",
              "\t\tELSE LEFT('D-' + CAST(d.RecID as char(10)) + CAST(d.Buy AS VARCHAR(255)) + ' >> ' +  CAST(d.Get AS VARCHAR(255)), 255) ",
              "\tEND AS deal",
              "FROM            Redemptions_tbl_Main as d"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Deal"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "\tRecID deal_code,",
              "\tCASE ",
              "\t\tWHEN d.RecID = 0",
              "\t\tTHEN ''",
              "\t\tELSE LEFT('D-' + CAST(d.RecID as char(10)) + CAST(d.Buy AS VARCHAR(255)) + ' >> ' +  CAST(d.Get AS VARCHAR(255)), 255) ",
              "\tEND AS deal",
              "FROM            Redemptions_tbl_Main as d</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period Select YearFactor",
        "columns": [
          {
            "name": "YearFactor",
            "dataType": "int64",
            "sourceColumn": "YearFactor",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Note",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Note",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Period Select YearFactor",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_FiscalYearFactor].* FROM [dbo].[BRS_FiscalYearFactor] ",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            }
          }
        ],
        "measures": [
          {
            "name": "__year_factor",
            "expression": "min([YearFactor])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_FiscalYearFactor].* FROM [dbo].[BRS_FiscalYearFactor] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_FiscalYearFactor"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "f12077bd-e88c-477b-85f6-de7c043d1647",
        "fromTable": "Sales",
        "fromColumn": "Shipto",
        "toTable": "Customer",
        "toColumn": "ShipTo"
      },
      {
        "name": "d8b3a5d4-d370-49a4-b36b-7aba8078e902",
        "fromTable": "Sales",
        "fromColumn": "SalesDate",
        "toTable": "Period",
        "toColumn": "SalesDate"
      },
      {
        "name": "ede2fabe-3f3b-4e57-b1c4-6ec1ae0c896f",
        "fromTable": "Customer",
        "fromColumn": "IsrEmployeeKey",
        "toTable": "EmployeeSecurity",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "37335bf4-41ef-48f0-bf10-cd13946f63f6",
        "fromTable": "Customer",
        "fromColumn": "FocusCd",
        "toTable": "CustomerFocus",
        "toColumn": "FocusCd"
      },
      {
        "name": "42134443-8ea4-41ee-ae12-78858501d1d6",
        "fromTable": "Sales",
        "fromColumn": "ItemKey",
        "toTable": "Item",
        "toColumn": "ItemKey"
      },
      {
        "name": "2df637de-b257-443a-af34-bd7f7de4ca15",
        "fromTable": "Item",
        "fromColumn": "deal_code",
        "toTable": "Deal",
        "toColumn": "deal_code"
      }
    ],
    "roles": [
      {
        "name": "Inside_User_role",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "CAHSI\\Gary.Winslow",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1322"
          },
          {
            "memberName": "CAHSI\\Noah.Thompson",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11129"
          },
          {
            "memberName": "CAHSI\\tcrowley",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1815"
          },
          {
            "memberName": "CAHSI\\JLi",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-2414"
          },
          {
            "memberName": "CAHSI\\Amanda.Russell",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11317"
          },
          {
            "memberName": "CAHSI\\Emilia.Bronowicki",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11418"
          },
          {
            "memberName": "CAHSI\\Franca.Parente",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-4027"
          },
          {
            "memberName": "CAHSI\\Grace.Brohman",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-8327"
          },
          {
            "memberName": "CAHSI\\Janet.Dunphy",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11401"
          },
          {
            "memberName": "CAHSI\\Lori.Bonn",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11344"
          },
          {
            "memberName": "CAHSI\\Lina.Evraire",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11938"
          },
          {
            "memberName": "CAHSI\\Meaghan.Collins",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-13818"
          },
          {
            "memberName": "CAHSI\\Nadia.Xavier",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-6968"
          },
          {
            "memberName": "CAHSI\\Kristina.Fowler",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1443"
          },
          {
            "memberName": "CAHSI\\Shenila.Jaffer",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-9338"
          },
          {
            "memberName": "S-1-5-21-2722441861-2609703027-3449782368-11452",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11452"
          },
          {
            "memberName": "CAHSI\\Ann.Bilodeau",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-12090"
          },
          {
            "memberName": "CAHSI\\Madeleine.Khodaverdi",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-12793"
          },
          {
            "memberName": "CAHSI\\Nia.Othitis",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-5731"
          },
          {
            "memberName": "CAHSI\\GWatson",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-5503"
          }
        ],
        "tablePermissions": [
          {
            "name": "EmployeeSecurity",
            "filterExpression": "'EmployeeSecurity'[LoginId]=USERNAME()"
          }
        ]
      },
      {
        "name": "Inside_Admin_role",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "CAHSI\\Noah.Thompson",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11129"
          }
        ]
      }
    ]
  },
  "id": "SemanticModel"
}