{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "Commission SQL Source",
        "connectionString": "Provider=SQLOLEDB;Data Source=CAHSIONNLSQL1;Persist Security Info=false;Integrated Security=SSPI;Initial Catalog=BRSales",
        "impersonationMode": "impersonateAccount",
        "account": "CAHSI\\tcrowley",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Customer",
        "columns": [
          {
            "name": "ShipTo",
            "dataType": "int64",
            "sourceColumn": "ShipTo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Billto",
            "dataType": "int64",
            "sourceColumn": "Billto",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CustomerGroup",
            "dataType": "string",
            "sourceColumn": "CustomerGroup",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesPlan",
            "dataType": "string",
            "sourceColumn": "SalesPlan",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesPlanCode",
            "dataType": "string",
            "sourceColumn": "SalesPlanCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesPlanType",
            "dataType": "string",
            "sourceColumn": "SalesPlanType",
            "sourceProviderType": "Char"
          },
          {
            "name": "FieldSales",
            "dataType": "string",
            "sourceColumn": "FieldSales",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivision",
            "dataType": "string",
            "sourceColumn": "SalesDivision",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "CustomerStatus",
            "dataType": "string",
            "sourceColumn": "CustomerStatus",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivisionCode",
            "dataType": "string",
            "sourceColumn": "SalesDivisionCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "BranchCode",
            "dataType": "string",
            "sourceColumn": "BranchCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClassCode",
            "dataType": "string",
            "sourceColumn": "MarketClassCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "CommStatusCode",
            "dataType": "string",
            "sourceColumn": "CommStatusCode"
          },
          {
            "name": "CommStatusNote",
            "dataType": "string",
            "sourceColumn": "CommStatusNote"
          },
          {
            "name": "FocusCd",
            "dataType": "string",
            "sourceColumn": "FocusCd"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment"
          },
          {
            "name": "Specialty",
            "dataType": "string",
            "sourceColumn": "Specialty"
          },
          {
            "name": "wheel_active_ind",
            "dataType": "int64",
            "sourceColumn": "wheel_active_ind"
          },
          {
            "name": "wheel_seg1_merchandise_ind",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "wheel_seg1_merchandise_ind"
          },
          {
            "name": "wheel_seg2_hs_branded_ind",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "wheel_seg2_hs_branded_ind"
          },
          {
            "name": "wheel_seg3_equip_hitech_ind",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "wheel_seg3_equip_hitech_ind"
          },
          {
            "name": "wheel_seg4_digital_restoration_ind",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "wheel_seg4_digital_restoration_ind"
          },
          {
            "name": "wheel_seg5_henry_schein_one_ind",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "wheel_seg5_henry_schein_one_ind"
          },
          {
            "name": "wheel_seg6_equipment_services_ind",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "wheel_seg6_equipment_services_ind"
          },
          {
            "name": "wheel_seg7_business_solutions_ind",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "wheel_seg7_business_solutions_ind"
          },
          {
            "type": "calculated",
            "name": "wheel_seg_count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "[wheel_seg1_merchandise_ind]+Customer[wheel_seg2_hs_branded_ind]+Customer[wheel_seg3_equip_hitech_ind]+Customer[wheel_seg4_digital_restoration_ind]+Customer[wheel_seg5_henry_schein_one_ind]+Customer[wheel_seg6_equipment_services_ind]+Customer[wheel_seg7_business_solutions_ind]"
          },
          {
            "name": "playbook_focus_code",
            "dataType": "string",
            "sourceColumn": "playbook_focus_code"
          },
          {
            "name": "service_bonus_include_ind",
            "dataType": "boolean",
            "sourceColumn": "service_bonus_include_ind"
          },
          {
            "name": "CommMasterCode_FSC_Current",
            "dataType": "string",
            "sourceColumn": "CommMasterCode_FSC_Current"
          },
          {
            "name": "CreateDate",
            "dataType": "dateTime",
            "sourceColumn": "CreateDate",
            "formatString": "yyyy-MM-dd",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"yyyy-MM-dd\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "adhoc_model_code",
            "dataType": "string",
            "sourceColumn": "adhoc_model_code"
          },
          {
            "name": "ApplyFreightInd",
            "dataType": "boolean",
            "sourceColumn": "ApplyFreightInd",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "name": "ApplySmallOrderChargesInd",
            "dataType": "boolean",
            "sourceColumn": "ApplySmallOrderChargesInd",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "name": "MarketClassNewCode",
            "dataType": "string",
            "sourceColumn": "MarketClassNewCode"
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "  Dimension.Customer.ShipTo",
                "  ,Dimension.Customer.Billto",
                "  ,Dimension.Customer.Customer",
                "  ,Dimension.Customer.CustomerGroup",
                "  ,Dimension.Customer.SalesPlan",
                "  ,Dimension.Customer.SalesPlanCode",
                "  ,Dimension.Customer.SalesPlanType",
                "  ,Dimension.Customer.FieldSales",
                "  ,Dimension.Customer.Branch",
                "  ,Dimension.Customer.SalesDivision",
                "  ,Dimension.Customer.MarketClass",
                "  ,Dimension.Customer.CustomerStatus",
                "  ,Dimension.Customer.SalesDivisionCode",
                "  ,Dimension.Customer.BranchCode",
                "  ,Dimension.Customer.MarketClassCode",
                "  ,Dimension.Customer.CommStatusCode",
                "  ,Dimension.Customer.CommStatusNote",
                "  ,FocusCd",
                "  ,Segment",
                " ,Specialty",
                "",
                "-- wheel graft on last month results",
                ",[wheel_active_ind]",
                ",[wheel_seg1_merchandise_ind]",
                ",[wheel_seg2_hs_branded_ind]",
                ",[wheel_seg3_equip_hitech_ind]",
                ",[wheel_seg4_digital_restoration_ind]",
                ",[wheel_seg5_henry_schein_one_ind]",
                ",[wheel_seg6_equipment_services_ind]",
                ",[wheel_seg7_business_solutions_ind]",
                "",
                ", playbook_focus_code",
                "",
                ",CommMasterCode_FSC_Current",
                ",service_bonus_include_ind",
                ",CreateDate",
                ",adhoc_model_code",
                ",ApplyFreightInd",
                ",ApplySmallOrderChargesInd",
                ",Dimension.Customer.MarketClassNewCode",
                "",
                "FROM",
                "  Dimension.Customer"
              ],
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Customer.ShipTo",
                  "  ,Dimension.Customer.Billto",
                  "  ,Dimension.Customer.Customer",
                  "  ,Dimension.Customer.CustomerGroup",
                  "  ,Dimension.Customer.SalesPlan",
                  "  ,Dimension.Customer.SalesPlanCode",
                  "  ,Dimension.Customer.SalesPlanType",
                  "  ,Dimension.Customer.FieldSales",
                  "  ,Dimension.Customer.Branch",
                  "  ,Dimension.Customer.SalesDivision",
                  "  ,Dimension.Customer.MarketClass",
                  "  ,Dimension.Customer.CustomerStatus",
                  "  ,Dimension.Customer.SalesDivisionCode",
                  "  ,Dimension.Customer.BranchCode",
                  "  ,Dimension.Customer.MarketClassCode",
                  "  ,Dimension.Customer.CommStatusCode",
                  "  ,Dimension.Customer.CommStatusNote",
                  "  ,FocusCd",
                  "  ,Segment",
                  " ,Specialty",
                  "",
                  "-- wheel graft on last month results",
                  ",[wheel_active_ind]",
                  ",[wheel_seg1_merchandise_ind]",
                  ",[wheel_seg2_hs_branded_ind]",
                  ",[wheel_seg3_equip_hitech_ind]",
                  ",[wheel_seg4_digital_restoration_ind]",
                  ",[wheel_seg5_henry_schein_one_ind]",
                  ",[wheel_seg6_equipment_services_ind]",
                  ",[wheel_seg7_business_solutions_ind]",
                  "",
                  ", playbook_focus_code",
                  "",
                  ",CommMasterCode_FSC_Current",
                  ",service_bonus_include_ind",
                  ",CreateDate",
                  ",adhoc_model_code",
                  ",ApplyFreightInd",
                  ",ApplySmallOrderChargesInd",
                  ",Dimension.Customer.MarketClassNewCode",
                  "",
                  "FROM",
                  "  Dimension.Customer</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"ShipTo\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"Billto\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"Customer\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"CustomerGroup\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesPlan\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesPlanCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesPlanType\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"FieldSales\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"Branch\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesDivision\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"MarketClass\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"CustomerStatus\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesDivisionCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"BranchCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"MarketClassCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"CommStatusCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"CommStatusNote\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "wheel_seg_score",
            "expression": "DIVIDE( ([wheel_seg1_count]*1.0 + [wheel_seg2_count]*2.0 + [wheel_seg3_count]*3.0 + [wheel_seg4_count]*4.0 + [wheel_seg5_count]*5.0 + [wheel_seg6_count]*6.0 + [wheel_seg7_count]*7.0 ), [wheel_active_count])",
            "formatString": "0.0"
          },
          {
            "name": "Count of wheel_seg_count",
            "expression": "COUNTA([wheel_seg_count])"
          },
          {
            "name": "wheel_seg7_count",
            "expression": "CALCULATE([Count of wheel_seg_count],'Customer'[wheel_seg_count]=7)"
          },
          {
            "name": "wheel_seg6_count",
            "expression": "CALCULATE([Count of wheel_seg_count],'Customer'[wheel_seg_count]=6)"
          },
          {
            "name": "wheel_seg5_count",
            "expression": "CALCULATE([Count of wheel_seg_count],'Customer'[wheel_seg_count]=5)"
          },
          {
            "name": "wheel_seg4_count",
            "expression": "CALCULATE([Count of wheel_seg_count],'Customer'[wheel_seg_count]=4)"
          },
          {
            "name": "wheel_seg3_count",
            "expression": "CALCULATE([Count of wheel_seg_count],'Customer'[wheel_seg_count]=3)"
          },
          {
            "name": "wheel_seg2_count",
            "expression": "CALCULATE([Count of wheel_seg_count],'Customer'[wheel_seg_count]=2)"
          },
          {
            "name": "wheel_seg1_count",
            "expression": "CALCULATE([Count of wheel_seg_count],'Customer'[wheel_seg_count]=1)"
          },
          {
            "name": "wheel_active_count",
            "expression": "SUM([wheel_active_ind])"
          },
          {
            "name": "Count of ShipTo",
            "expression": "COUNTA([ShipTo])",
            "formatString": "0"
          },
          {
            "name": "Distinct Count of Billto",
            "expression": "DISTINCTCOUNT([Billto])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Customer.ShipTo",
              "  ,Dimension.Customer.Billto",
              "  ,Dimension.Customer.Customer",
              "  ,Dimension.Customer.CustomerGroup",
              "  ,Dimension.Customer.SalesPlan",
              "  ,Dimension.Customer.SalesPlanCode",
              "  ,Dimension.Customer.SalesPlanType",
              "  ,Dimension.Customer.FieldSales",
              "  ,Dimension.Customer.Branch",
              "  ,Dimension.Customer.SalesDivision",
              "  ,Dimension.Customer.MarketClass",
              "  ,Dimension.Customer.CustomerStatus",
              "  ,Dimension.Customer.SalesDivisionCode",
              "  ,Dimension.Customer.BranchCode",
              "  ,Dimension.Customer.MarketClassCode",
              "  ,Dimension.Customer.CommStatusCode",
              "  ,Dimension.Customer.CommStatusNote",
              "  ,FocusCd",
              "  ,Segment",
              " ,Specialty",
              "",
              "-- wheel graft on last month results",
              ",[wheel_active_ind]",
              ",[wheel_seg1_merchandise_ind]",
              ",[wheel_seg2_hs_branded_ind]",
              ",[wheel_seg3_equip_hitech_ind]",
              ",[wheel_seg4_digital_restoration_ind]",
              ",[wheel_seg5_henry_schein_one_ind]",
              ",[wheel_seg6_equipment_services_ind]",
              ",[wheel_seg7_business_solutions_ind]",
              "",
              ", playbook_focus_code",
              "",
              ",CommMasterCode_FSC_Current",
              ",service_bonus_include_ind",
              ",CreateDate",
              ",adhoc_model_code",
              ",ApplyFreightInd",
              ",ApplySmallOrderChargesInd",
              ",Dimension.Customer.MarketClassNewCode",
              "",
              "FROM",
              "  Dimension.Customer"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Customer.ShipTo",
              "  ,Dimension.Customer.Billto",
              "  ,Dimension.Customer.Customer",
              "  ,Dimension.Customer.CustomerGroup",
              "  ,Dimension.Customer.SalesPlan",
              "  ,Dimension.Customer.SalesPlanCode",
              "  ,Dimension.Customer.SalesPlanType",
              "  ,Dimension.Customer.FieldSales",
              "  ,Dimension.Customer.Branch",
              "  ,Dimension.Customer.SalesDivision",
              "  ,Dimension.Customer.MarketClass",
              "  ,Dimension.Customer.CustomerStatus",
              "  ,Dimension.Customer.SalesDivisionCode",
              "  ,Dimension.Customer.BranchCode",
              "  ,Dimension.Customer.MarketClassCode",
              "  ,Dimension.Customer.CommStatusCode",
              "  ,Dimension.Customer.CommStatusNote",
              "  ,FocusCd",
              "  ,Segment",
              " ,Specialty",
              "",
              "-- wheel graft on last month results",
              ",[wheel_active_ind]",
              ",[wheel_seg1_merchandise_ind]",
              ",[wheel_seg2_hs_branded_ind]",
              ",[wheel_seg3_equip_hitech_ind]",
              ",[wheel_seg4_digital_restoration_ind]",
              ",[wheel_seg5_henry_schein_one_ind]",
              ",[wheel_seg6_equipment_services_ind]",
              ",[wheel_seg7_business_solutions_ind]",
              "",
              ", playbook_focus_code",
              "",
              ",CommMasterCode_FSC_Current",
              ",service_bonus_include_ind",
              ",CreateDate",
              ",adhoc_model_code",
              ",ApplyFreightInd",
              ",ApplySmallOrderChargesInd",
              ",Dimension.Customer.MarketClassNewCode",
              "",
              "FROM",
              "  Dimension.Customer</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"ShipTo\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"Billto\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"Customer\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"CustomerGroup\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesPlan\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesPlanCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesPlanType\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"FieldSales\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"Branch\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesDivision\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"MarketClass\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"CustomerStatus\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"SalesDivisionCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"BranchCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"MarketClassCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"CommStatusCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer\" ColumnName=\"CommStatusNote\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Item",
        "columns": [
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Item",
            "dataType": "string",
            "sourceColumn": "Item",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesCategory",
            "dataType": "string",
            "sourceColumn": "SalesCategory",
            "sourceProviderType": "Char"
          },
          {
            "name": "Major",
            "dataType": "string",
            "sourceColumn": "Major",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SubMajor",
            "dataType": "string",
            "sourceColumn": "SubMajor",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "Supplier",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ItemCode",
            "dataType": "string",
            "sourceColumn": "ItemCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "ItemStatus",
            "dataType": "string",
            "sourceColumn": "ItemStatus",
            "sourceProviderType": "Char"
          },
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label",
            "sourceProviderType": "Char"
          },
          {
            "name": "Current_BasePrice",
            "dataType": "decimal",
            "sourceColumn": "Current_BasePrice",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CommGroupCode",
            "dataType": "string",
            "sourceColumn": "CommGroupCode"
          },
          {
            "name": "CommGroupNote",
            "dataType": "string",
            "sourceColumn": "CommGroupNote"
          },
          {
            "name": "CommGroupCpsCode",
            "dataType": "string",
            "sourceColumn": "CommGroupCpsCode"
          },
          {
            "name": "MajorCode",
            "dataType": "string",
            "sourceColumn": "MajorCode"
          },
          {
            "name": "SalesCategoryRollup",
            "dataType": "string",
            "sourceColumn": "SalesCategoryRollup"
          },
          {
            "name": "SalesCategoryScorecard",
            "dataType": "string",
            "sourceColumn": "SalesCategoryScorecard"
          },
          {
            "name": "PrivateLabelScopeInd",
            "dataType": "boolean",
            "sourceColumn": "PrivateLabelScopeInd"
          },
          {
            "name": "Top15",
            "dataType": "string",
            "sourceColumn": "Top15"
          },
          {
            "name": "SupplierFamily",
            "dataType": "string",
            "sourceColumn": "SupplierFamily"
          },
          {
            "name": "SupplierGlobal",
            "dataType": "string",
            "sourceColumn": "SupplierGlobal"
          },
          {
            "name": "MELP_code",
            "dataType": "string",
            "sourceColumn": "MELP_code"
          },
          {
            "name": "SupplierCode",
            "dataType": "string",
            "sourceColumn": "SupplierCode"
          },
          {
            "name": "MinorCode",
            "dataType": "string",
            "sourceColumn": "MinorCode"
          },
          {
            "name": "BrandEquityCategory",
            "dataType": "string",
            "sourceColumn": "BrandEquityCategory"
          },
          {
            "name": "BrandEquityCode",
            "dataType": "string",
            "sourceColumn": "BrandEquityCode"
          },
          {
            "name": "KeySupplierMerchInd",
            "dataType": "int64",
            "sourceColumn": "KeySupplierMerchInd"
          },
          {
            "name": "comm_group_legacy_cd",
            "dataType": "string",
            "sourceColumn": "comm_group_legacy_cd"
          },
          {
            "name": "global_product",
            "dataType": "string",
            "sourceColumn": "global_product"
          },
          {
            "name": "CategoryRollup",
            "dataType": "string",
            "sourceColumn": "CategoryRollup"
          },
          {
            "name": "comm_bonus1_cd",
            "dataType": "string",
            "sourceColumn": "comm_bonus1_cd"
          },
          {
            "name": "mpc_comm_bonus1_cd",
            "dataType": "string",
            "sourceColumn": "mpc_comm_bonus1_cd"
          },
          {
            "name": "comm_bonus2_cd",
            "dataType": "string",
            "sourceColumn": "comm_bonus2_cd"
          },
          {
            "name": "mpc_comm_bonus2_cd",
            "dataType": "string",
            "sourceColumn": "mpc_comm_bonus2_cd"
          },
          {
            "name": "comm_bonus3_cd",
            "dataType": "string",
            "sourceColumn": "comm_bonus3_cd"
          },
          {
            "name": "mpc_comm_bonus3_cd",
            "dataType": "string",
            "sourceColumn": "mpc_comm_bonus3_cd"
          },
          {
            "name": "SalesCategoryCode",
            "dataType": "string",
            "sourceColumn": "SalesCategoryCode"
          }
        ],
        "partitions": [
          {
            "name": "Item",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "  Dimension.Item.ItemKey",
                "  ,Dimension.Item.Item",
                "  ,Dimension.Item.SalesCategory",
                "  ,Dimension.Item.Major",
                "  ,Dimension.Item.SubMajor",
                "  ,Dimension.Item.Supplier",
                "  ,Dimension.Item.ItemCode",
                "  ,Dimension.Item.ItemStatus",
                "  ,Dimension.Item.Label",
                "  ,Dimension.Item.CommGroupCode",
                "  ,Dimension.Item.CommGroupNote",
                "  ,Dimension.Item.Current_BasePrice",
                "  ,Dimension.Item.CommGroupCpsCode",
                "  ,Dimension.Item.MajorCode",
                "  ,SalesCategoryRollup",
                " ,SalesCategoryScorecard",
                " ,PrivateLabelScopeInd",
                ",Top15",
                ", SupplierFamily",
                ",SupplierGlobal",
                ",MELP_code",
                ",Current_SupplierCode AS SupplierCode",
                ",MinorCode",
                "",
                "-- equity graft on last month results",
                ",BrandEquityCategory",
                ",BrandEquityCode",
                "",
                ", KeySupplierMerchInd",
                ",comm_group_legacy_cd",
                "",
                ",CategoryRollup",
                ",global_product",
                "",
                ",comm_bonus1_cd",
                ",mpc_comm_bonus1_cd",
                ",comm_bonus2_cd",
                ",mpc_comm_bonus2_cd",
                ",comm_bonus3_cd",
                ",mpc_comm_bonus3_cd",
                ",SalesCategoryCode",
                "",
                "",
                "FROM",
                "  Dimension.Item"
              ],
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Item.ItemKey",
                  "  ,Dimension.Item.Item",
                  "  ,Dimension.Item.SalesCategory",
                  "  ,Dimension.Item.Major",
                  "  ,Dimension.Item.SubMajor",
                  "  ,Dimension.Item.Supplier",
                  "  ,Dimension.Item.ItemCode",
                  "  ,Dimension.Item.ItemStatus",
                  "  ,Dimension.Item.Label",
                  "  ,Dimension.Item.CommGroupCode",
                  "  ,Dimension.Item.CommGroupNote",
                  "  ,Dimension.Item.Current_BasePrice",
                  "  ,Dimension.Item.CommGroupCpsCode",
                  "  ,Dimension.Item.MajorCode",
                  "  ,SalesCategoryRollup",
                  " ,SalesCategoryScorecard",
                  " ,PrivateLabelScopeInd",
                  ",Top15",
                  ", SupplierFamily",
                  ",SupplierGlobal",
                  ",MELP_code",
                  ",Current_SupplierCode AS SupplierCode",
                  ",MinorCode",
                  "",
                  "-- equity graft on last month results",
                  ",BrandEquityCategory",
                  ",BrandEquityCode",
                  "",
                  ", KeySupplierMerchInd",
                  ",comm_group_legacy_cd",
                  "",
                  ",CategoryRollup",
                  ",global_product",
                  "",
                  ",comm_bonus1_cd",
                  ",mpc_comm_bonus1_cd",
                  ",comm_bonus2_cd",
                  ",mpc_comm_bonus2_cd",
                  ",comm_bonus3_cd",
                  ",mpc_comm_bonus3_cd",
                  ",SalesCategoryCode",
                  "",
                  "",
                  "FROM",
                  "  Dimension.Item</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"ItemKey\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Item\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"SalesCategory\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Major\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"SubMajor\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Supplier\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"ItemCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"ItemStatus\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Label\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"CommGroupCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"CommGroupNote\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Current_BasePrice\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"CommGroupCpsCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"CustomCommGroup1Code\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Count of Item",
            "expression": "COUNTA([Item])",
            "formatString": "0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Item.ItemKey",
              "  ,Dimension.Item.Item",
              "  ,Dimension.Item.SalesCategory",
              "  ,Dimension.Item.Major",
              "  ,Dimension.Item.SubMajor",
              "  ,Dimension.Item.Supplier",
              "  ,Dimension.Item.ItemCode",
              "  ,Dimension.Item.ItemStatus",
              "  ,Dimension.Item.Label",
              "  ,Dimension.Item.CommGroupCode",
              "  ,Dimension.Item.CommGroupNote",
              "  ,Dimension.Item.Current_BasePrice",
              "  ,Dimension.Item.CommGroupCpsCode",
              "  ,Dimension.Item.MajorCode",
              "  ,SalesCategoryRollup",
              " ,SalesCategoryScorecard",
              " ,PrivateLabelScopeInd",
              ",Top15",
              ", SupplierFamily",
              ",SupplierGlobal",
              ",MELP_code",
              ",Current_SupplierCode AS SupplierCode",
              ",MinorCode",
              "",
              "-- equity graft on last month results",
              ",BrandEquityCategory",
              ",BrandEquityCode",
              "",
              ", KeySupplierMerchInd",
              ",comm_group_legacy_cd",
              "",
              ",CategoryRollup",
              ",global_product",
              "",
              ",comm_bonus1_cd",
              ",mpc_comm_bonus1_cd",
              ",comm_bonus2_cd",
              ",mpc_comm_bonus2_cd",
              ",comm_bonus3_cd",
              ",mpc_comm_bonus3_cd",
              ",SalesCategoryCode",
              "",
              "",
              "FROM",
              "  Dimension.Item"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Item"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Item.ItemKey",
              "  ,Dimension.Item.Item",
              "  ,Dimension.Item.SalesCategory",
              "  ,Dimension.Item.Major",
              "  ,Dimension.Item.SubMajor",
              "  ,Dimension.Item.Supplier",
              "  ,Dimension.Item.ItemCode",
              "  ,Dimension.Item.ItemStatus",
              "  ,Dimension.Item.Label",
              "  ,Dimension.Item.CommGroupCode",
              "  ,Dimension.Item.CommGroupNote",
              "  ,Dimension.Item.Current_BasePrice",
              "  ,Dimension.Item.CommGroupCpsCode",
              "  ,Dimension.Item.MajorCode",
              "  ,SalesCategoryRollup",
              " ,SalesCategoryScorecard",
              " ,PrivateLabelScopeInd",
              ",Top15",
              ", SupplierFamily",
              ",SupplierGlobal",
              ",MELP_code",
              ",Current_SupplierCode AS SupplierCode",
              ",MinorCode",
              "",
              "-- equity graft on last month results",
              ",BrandEquityCategory",
              ",BrandEquityCode",
              "",
              ", KeySupplierMerchInd",
              ",comm_group_legacy_cd",
              "",
              ",CategoryRollup",
              ",global_product",
              "",
              ",comm_bonus1_cd",
              ",mpc_comm_bonus1_cd",
              ",comm_bonus2_cd",
              ",mpc_comm_bonus2_cd",
              ",comm_bonus3_cd",
              ",mpc_comm_bonus3_cd",
              ",SalesCategoryCode",
              "",
              "",
              "FROM",
              "  Dimension.Item</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"ItemKey\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Item\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"SalesCategory\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Major\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"SubMajor\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Supplier\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"ItemCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"ItemStatus\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Label\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"CommGroupCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"CommGroupNote\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"Current_BasePrice\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"CommGroupCpsCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Item\" ColumnName=\"CustomCommGroup1Code\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period",
        "columns": [
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "sourceColumn": "MonthNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName",
            "sourceProviderType": "Char"
          },
          {
            "name": "YearNum",
            "dataType": "int64",
            "sourceColumn": "YearNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "WorkingDaysMonth",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthSeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthSeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInQtr",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInYear",
            "sourceProviderType": "SmallInt"
          }
        ],
        "partitions": [
          {
            "name": "Period",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Period].[FiscalMonth],[Dimension].[Period].[MonthName],[Dimension].[Period].[MonthNum],[Dimension].[Period].[QuarterName],[Dimension].[Period].[YearNum],[Dimension].[Period].[WorkingDaysMonth],[Dimension].[Period].[MonthSeq],[Dimension].[Period].[FirstMonthSeqInQtr],[Dimension].[Period].[FirstMonthSeqInYear] FROM [Dimension].[Period] ",
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>FiscalMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>86</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>87</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthNum</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearNum</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>WorkingDaysMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>123</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthSeq</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FirstMonthSeqInQtr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>125</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FirstMonthSeqInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>131</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>LastWorkingDay</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>FiscalMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthNum</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearNum</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>WorkingDaysMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthSeq</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FirstMonthSeqInQtr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FirstMonthSeqInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>LastWorkingDay</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>LastWorkingDay</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <SortByColumn>FiscalMonth</SortByColumn>",
                  "  <IsSortDescending>true</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Period].[FiscalMonth],[Dimension].[Period].[MonthName],[Dimension].[Period].[MonthNum],[Dimension].[Period].[QuarterName],[Dimension].[Period].[YearNum],[Dimension].[Period].[WorkingDaysMonth],[Dimension].[Period].[MonthSeq],[Dimension].[Period].[FirstMonthSeqInQtr],[Dimension].[Period].[FirstMonthSeqInYear] FROM [Dimension].[Period] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Period"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>FiscalMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>86</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthName</string>",
              "      </key>",
              "      <value>",
              "        <int>87</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthNum</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterName</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearNum</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>WorkingDaysMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>123</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthSeq</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FirstMonthSeqInQtr</string>",
              "      </key>",
              "      <value>",
              "        <int>125</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FirstMonthSeqInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>131</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>LastWorkingDay</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>FiscalMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthName</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthNum</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterName</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearNum</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>WorkingDaysMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthSeq</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FirstMonthSeqInQtr</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FirstMonthSeqInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>LastWorkingDay</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>LastWorkingDay</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <SortByColumn>FiscalMonth</SortByColumn>",
              "  <IsSortDescending>true</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sales",
        "columns": [
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ShipTo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShipTo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FactKey",
            "dataType": "int64",
            "sourceColumn": "FactKey"
          },
          {
            "name": "FSC_SalespersonKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FSC_SalespersonKey"
          },
          {
            "name": "FSC_CommGroupKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FSC_CommGroupKey"
          },
          {
            "name": "ESS_SalespersonKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ESS_SalespersonKey"
          },
          {
            "name": "ESS_CommGroupKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ESS_CommGroupKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "DocTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DocTypeKey"
          },
          {
            "name": "LineNumber",
            "dataType": "int64",
            "sourceColumn": "LineNumber"
          },
          {
            "name": "DateKey",
            "dataType": "dateTime",
            "sourceColumn": "DateKey",
            "formatString": "yyyy-MM-dd",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"yyyy-MM-dd\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "BillTo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BillTo"
          },
          {
            "name": "SourceKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SourceKey"
          },
          {
            "name": "FreeGoodsEstInd",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FreeGoodsEstInd"
          },
          {
            "name": "FreeGoodsRedeemedInd",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FreeGoodsRedeemedInd"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Quantity"
          },
          {
            "name": "SalesAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesAmt"
          },
          {
            "name": "GPAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GPAmt"
          },
          {
            "name": "FSC_CommAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FSC_CommAmt"
          },
          {
            "name": "ESS_CommAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ESS_CommAmt"
          },
          {
            "name": "FreeGoodsInvoicedInd",
            "dataType": "boolean",
            "sourceColumn": "FreeGoodsInvoicedInd"
          },
          {
            "name": "FSC_SalespersonCodeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FSC_SalespersonCodeKey"
          },
          {
            "name": "CPS_SalespersonKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CPS_SalespersonKey"
          },
          {
            "name": "CPS_CommGroupKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CPS_CommGroupKey"
          },
          {
            "name": "EPS_SalespersonKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EPS_SalespersonKey"
          },
          {
            "name": "EPS_CommGroupKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EPS_CommGroupKey"
          },
          {
            "name": "EPS_CommAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "EPS_CommAmt"
          },
          {
            "name": "CPS_CommAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CPS_CommAmt"
          },
          {
            "name": "AdjKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AdjKey"
          },
          {
            "name": "ISR_SalespersonKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ISR_SalespersonKey"
          },
          {
            "name": "ISR_CommAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ISR_CommAmt"
          },
          {
            "name": "ISR_CommGroupKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ISR_CommGroupKey"
          },
          {
            "name": "EST_SalespersonKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EST_SalespersonKey"
          },
          {
            "name": "EST_CommGroupKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EST_CommGroupKey"
          },
          {
            "name": "EST_CommAmt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "EST_CommAmt"
          },
          {
            "name": "hs_branded_baseline_ind",
            "dataType": "int64",
            "sourceColumn": "hs_branded_baseline_ind"
          },
          {
            "type": "calculated",
            "name": "gm_line_rt",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "DIVIDE([GPAmt],[SalesAmt])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "type": "calculated",
            "name": "gm_line_neg_ind",
            "dataType": "boolean",
            "isDataTypeInferred": false,
            "expression": "IF([gm_line_rt]<0,1,0)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "name": "OrderDateKey",
            "dataType": "dateTime",
            "sourceColumn": "OrderDateKey",
            "formatString": "yyyy-MM-dd",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"yyyy-MM-dd\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "backorder_ind",
            "dataType": "boolean",
            "sourceColumn": "backorder_ind",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          }
        ],
        "partitions": [
          {
            "name": "SaleVendor",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "--\ttop 10",
                "",
                "\tFactKey,",
                "\tFiscalMonth,",
                "",
                "\tFSC_SalespersonKey,",
                "\tFSC_SalespersonCodeKey,",
                "\tFSC_CommGroupKey,",
                "",
                "\tISR_SalespersonKey,",
                "\tISR_CommGroupKey,",
                "",
                "\tESS_SalespersonKey,",
                "\tESS_CommGroupKey,",
                "",
                "\tCPS_SalespersonKey,",
                "\tCPS_CommGroupKey,",
                "",
                "\tEPS_SalespersonKey,",
                "\tEPS_CommGroupKey,",
                "",
                "\tEST_SalespersonKey,",
                "\tEST_CommGroupKey,",
                "",
                "\tShipTo,",
                "\tItemKey,",
                "\tSalesOrderNumber,",
                "\tDocTypeKey,",
                "\tLineNumber,",
                "\tDateKey,",
                "\tBillTo,",
                "\tSourceKey,",
                "\tFreeGoodsInvoicedInd,",
                "\tFreeGoodsEstInd,",
                "\tFreeGoodsRedeemedInd,",
                "\tAdjKey,",
                "",
                "\tQuantity,",
                "\tSalesAmt,",
                "\tGPAmt,",
                "\tFSC_CommAmt,",
                "\tISR_CommAmt,",
                "\tESS_CommAmt,",
                "\tEPS_CommAmt,",
                "\tCPS_CommAmt,",
                "\tEST_CommAmt,",
                "",
                "\ths_branded_baseline_ind",
                "",
                "\t,OrderDateKey",
                "\t,backorder_ind",
                "",
                "FROM",
                "\tFact.Commission"
              ],
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "--\ttop 10",
                  "",
                  "\tFactKey,",
                  "\tFiscalMonth,",
                  "",
                  "\tFSC_SalespersonKey,",
                  "\tFSC_SalespersonCodeKey,",
                  "\tFSC_CommGroupKey,",
                  "",
                  "\tISR_SalespersonKey,",
                  "\tISR_CommGroupKey,",
                  "",
                  "\tESS_SalespersonKey,",
                  "\tESS_CommGroupKey,",
                  "",
                  "\tCPS_SalespersonKey,",
                  "\tCPS_CommGroupKey,",
                  "",
                  "\tEPS_SalespersonKey,",
                  "\tEPS_CommGroupKey,",
                  "",
                  "\tEST_SalespersonKey,",
                  "\tEST_CommGroupKey,",
                  "",
                  "\tShipTo,",
                  "\tItemKey,",
                  "\tSalesOrderNumber,",
                  "\tDocTypeKey,",
                  "\tLineNumber,",
                  "\tDateKey,",
                  "\tBillTo,",
                  "\tSourceKey,",
                  "\tFreeGoodsInvoicedInd,",
                  "\tFreeGoodsEstInd,",
                  "\tFreeGoodsRedeemedInd,",
                  "\tAdjKey,",
                  "",
                  "\tQuantity,",
                  "\tSalesAmt,",
                  "\tGPAmt,",
                  "\tFSC_CommAmt,",
                  "\tISR_CommAmt,",
                  "\tESS_CommAmt,",
                  "\tEPS_CommAmt,",
                  "\tCPS_CommAmt,",
                  "\tEST_CommAmt,",
                  "",
                  "\ths_branded_baseline_ind",
                  "",
                  "\t,OrderDateKey",
                  "\t,backorder_ind",
                  "",
                  "FROM",
                  "\tFact.Commission</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FactKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FiscalMonth\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FSC_SalespersonKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FSC_CommGroupKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ESS_SalespersonKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ESS_CommGroupKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ShipTo\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ItemKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"SalesOrderNumber\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"DocTypeKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"LineNumber\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"DateKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"BillTo\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"SourceKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FreeGoodsEstInd\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FreeGoodsRedeemedInd\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"Quantity\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"SalesAmt\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"GPAmt\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FSC_CommAmt\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ESS_CommAmt\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales in Period",
            "expression": "SUM([SalesAmt])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "GP in Period",
            "expression": "SUM([GPAmt])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales",
            "expression": "CALCULATE([Sales in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales",
            "expression": "CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP",
            "expression": "CALCULATE([GP in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP",
            "expression": "CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Sales",
            "expression": "CALCULATE([Sales in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD GP",
            "expression": "CALCULATE([GP in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Var",
            "expression": "[MTD Sales]-[PY MTD Sales]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Var",
            "expression": "[MTD GP]-[PY MTD GP]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Sales",
            "expression": "CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD GP",
            "expression": "CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Var",
            "expression": "[YTD Sales]-[PY YTD Sales]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Var",
            "expression": "[YTD GP]-[PY YTD GP]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Var %",
            "expression": "DIVIDE( [MTD Sales]-[PY MTD Sales],[PY MTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD GP Var %",
            "expression": "DIVIDE( [MTD GP] - [PY MTD GP], [PY MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Sales Var %",
            "expression": "DIVIDE( [YTD Sales]-[PY YTD Sales], [PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD GP Sales Var %",
            "expression": "DIVIDE( [YTD GP] - [PY YTD GP], [PY YTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Comm_FSC in Period",
            "expression": "SUM([FSC_CommAmt])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Comm_ESS in Period",
            "expression": "SUM([ESS_CommAmt])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm FSC",
            "expression": "CALCULATE([Comm_FSC in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Comm FSC",
            "expression": "CALCULATE([Comm_FSC in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm FSC Var",
            "expression": "[MTD Comm FSC]-[PY MTD Comm FSC]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm FSC Var %",
            "expression": "DIVIDE( [MTD Comm FSC] - [PY MTD Comm FSC], [PY MTD Comm FSC])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm FSC",
            "expression": "CALCULATE([Comm_FSC in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Comm FSC",
            "expression": "CALCULATE([Comm_FSC in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm FSC Var",
            "expression": "[YTD Comm FSC]-[PY YTD Comm FSC]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm FSC Var %",
            "expression": "DIVIDE( [YTD Comm FSC] - [PY YTD Comm FSC], [PY YTD Comm FSC])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Comm ESS",
            "expression": "CALCULATE([Comm_ESS in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Comm ESS",
            "expression": "CALCULATE([Comm_ESS in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm ESS Var",
            "expression": "[MTD Comm ESS]-[PY MTD Comm ESS]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm ESS Var %",
            "expression": "DIVIDE( [MTD Comm ESS] - [PY MTD Comm ESS], [PY MTD Comm ESS])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm ESS",
            "expression": "CALCULATE([Comm_ESS in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Comm ESS",
            "expression": "CALCULATE([Comm_ESS in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm ESS Var",
            "expression": "[YTD Comm ESS]-[PY YTD Comm ESS]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm ESS Var %",
            "expression": "DIVIDE( [YTD Comm ESS] - [PY YTD Comm ESS], [PY YTD Comm ESS])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Qty in Period",
            "expression": "SUM([Quantity])",
            "isHidden": true
          },
          {
            "name": "Comm_EPS in Period",
            "expression": "SUM([EPS_CommAmt])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Comm_CPS in Period",
            "expression": "SUM([CPS_CommAmt])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm EPS",
            "expression": "CALCULATE([Comm_EPS in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Comm EPS",
            "expression": "CALCULATE([Comm_EPS in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm EPS Var",
            "expression": "[MTD Comm EPS]-[PY MTD Comm EPS]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm EPS Var %",
            "expression": "DIVIDE( [MTD Comm EPS] - [PY MTD Comm EPS], [PY MTD Comm EPS])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm EPS",
            "expression": "CALCULATE([Comm_EPS in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Comm EPS",
            "expression": "CALCULATE([Comm_EPS in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm EPS Var",
            "expression": "[YTD Comm EPS]-[PY YTD Comm EPS]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm EPS Var %",
            "expression": "DIVIDE( [YTD Comm EPS] - [PY YTD Comm EPS], [PY YTD Comm EPS])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Comm CPS",
            "expression": "CALCULATE([Comm_CPS in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Comm CPS",
            "expression": "CALCULATE([Comm_CPS in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm CPS Var",
            "expression": "[MTD Comm CPS]-[PY MTD Comm CPS]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm CPS Var %",
            "expression": "DIVIDE( [MTD Comm CPS] - [PY MTD Comm CPS], [PY MTD Comm CPS])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm CPS",
            "expression": "CALCULATE([Comm_CPS in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Comm CPS",
            "expression": "CALCULATE([Comm_CPS in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm CPS Var",
            "expression": "[YTD Comm CPS]-[PY YTD Comm CPS]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm CPS Var %",
            "expression": "DIVIDE( [YTD Comm CPS] - [PY YTD Comm CPS], [PY YTD Comm CPS])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "SalesOrder in Period",
            "expression": "DISTINCTCOUNT([SalesOrderNumber])",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Lines in Period",
            "expression": "COUNTA([LineNumber])",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "MTD Salesorder",
            "expression": "CALCULATE([Salesorder in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY MTD Salesorder",
            "expression": "CALCULATE([Salesorder in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "#,0"
          },
          {
            "name": "YTD Salesorder",
            "expression": "CALCULATE([Salesorder in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY YTD Salesorder",
            "expression": "CALCULATE([Salesorder in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "#,0"
          },
          {
            "name": "MTD Lines",
            "expression": "CALCULATE([Lines in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY MTD Lines",
            "expression": "CALCULATE([Lines in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))",
            "formatString": "#,0"
          },
          {
            "name": "YTD Lines",
            "expression": "CALCULATE([Lines in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY YTD Lines",
            "expression": "CALCULATE([Lines in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "#,0"
          },
          {
            "name": "YTD GM",
            "expression": "DIVIDE([YTD GP],[YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD GM",
            "expression": "DIVIDE([MTD GP],[MTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY YTD GM",
            "expression": "DIVIDE([PY YTD GP],[PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY MTD GM",
            "expression": "DIVIDE([PY MTD GP],[PY MTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Comm_ISR in Period",
            "expression": "SUM([ISR_CommAmt])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm ISR",
            "expression": "CALCULATE([Comm_ISR in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Comm ISR",
            "expression": "CALCULATE([Comm_ISR in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm ISR Var",
            "expression": "[MTD Comm ISR]-[PY MTD Comm ISR]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm ISR Var %",
            "expression": "DIVIDE( [MTD Comm ISR] - [PY MTD Comm ISR], [PY MTD Comm ISR])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm ISR",
            "expression": "CALCULATE([Comm_ISR in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Comm ISR",
            "expression": "CALCULATE([Comm_ISR in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm ISR Var",
            "expression": "[YTD Comm ISR]-[PY YTD Comm ISR]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm ISR Var %",
            "expression": "DIVIDE( [YTD Comm ISR] - [PY YTD Comm CPS], [PY YTD Comm ISR])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Comm_EST in Period",
            "expression": "SUM([EST_CommAmt])",
            "isHidden": true
          },
          {
            "name": "YTD Comm EST",
            "expression": "CALCULATE([Comm_EST in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm EST",
            "expression": "CALCULATE([Comm_EST in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Comm EST",
            "expression": "CALCULATE([Comm_EST in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm EST Var",
            "expression": "[MTD Comm EST]-[PY MTD Comm EST]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Comm EST Var %",
            "expression": "DIVIDE( [MTD Comm EST] - [PY MTD Comm EST], [PY MTD Comm EST])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY YTD Comm EST",
            "expression": "CALCULATE([Comm_EST in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*[__year_factor])&&Period[MonthSeq]<=[__seq_first_month_current]-(12*[__year_factor])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm EST Var",
            "expression": "[YTD Comm EST]-[PY YTD Comm EST]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Comm EST Var %",
            "expression": "DIVIDE( [YTD Comm EST] - [PY YTD Comm EST], [PY YTD Comm EST])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Sales Var % - Customer Count Below Threshhold",
            "expression": "CALCULATE([Count of ShipTo], FILTER('Customer',  [YTD Sales Var %] < 0.25))"
          },
          {
            "name": "MTD Comm Rate FSC",
            "expression": "DIVIDE([MTD Comm FSC],[MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm Rate FSC",
            "expression": "DIVIDE([YTD Comm FSC],[YTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm Rate ESS",
            "expression": "DIVIDE([YTD Comm ESS],[YTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Comm Rate ESS",
            "expression": "DIVIDE([MTD Comm ESS],[MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Comm Rate EPS",
            "expression": "DIVIDE([MTD Comm EPS],[MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm Rate EPS",
            "expression": "DIVIDE([YTD Comm EPS],[YTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Comm Rate CPS",
            "expression": "DIVIDE([MTD Comm CPS],[MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm Rate CPS",
            "expression": "DIVIDE([YTD Comm CPS],[YTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Comm Rate ISR",
            "expression": "DIVIDE([MTD Comm ISR],[MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm Rate ISR",
            "expression": "DIVIDE([YTD Comm ISR],[YTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Comm Rate EST",
            "expression": "DIVIDE([MTD Comm EST],[MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Comm Rate EST",
            "expression": "DIVIDE([YTD Comm EST],[YTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Rolling 12mo Sales",
            "expression": [
              " ",
              "",
              "CALCULATE(",
              "",
              "        [Sales in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12) &&",
              "",
              "           Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              "",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY Rolling 12mo Sales",
            "expression": [
              " ",
              "",
              "CALCULATE(",
              "",
              "        [Sales in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12-12) &&",
              "",
              "           Period[MonthSeq]<=([__seq_first_month_current] -12)",
              "",
              "        )",
              "",
              ")",
              "",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling 12mo Sales Var",
            "expression": "[Rolling 12mo Sales]-[PY Rolling 12mo Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling 12mo Sales Var %",
            "expression": "DIVIDE( [Rolling 12mo Sales]-[PY Rolling 12mo Sales],[PY Rolling 12mo Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "--\ttop 10",
              "",
              "\tFactKey,",
              "\tFiscalMonth,",
              "",
              "\tFSC_SalespersonKey,",
              "\tFSC_SalespersonCodeKey,",
              "\tFSC_CommGroupKey,",
              "",
              "\tISR_SalespersonKey,",
              "\tISR_CommGroupKey,",
              "",
              "\tESS_SalespersonKey,",
              "\tESS_CommGroupKey,",
              "",
              "\tCPS_SalespersonKey,",
              "\tCPS_CommGroupKey,",
              "",
              "\tEPS_SalespersonKey,",
              "\tEPS_CommGroupKey,",
              "",
              "\tEST_SalespersonKey,",
              "\tEST_CommGroupKey,",
              "",
              "\tShipTo,",
              "\tItemKey,",
              "\tSalesOrderNumber,",
              "\tDocTypeKey,",
              "\tLineNumber,",
              "\tDateKey,",
              "\tBillTo,",
              "\tSourceKey,",
              "\tFreeGoodsInvoicedInd,",
              "\tFreeGoodsEstInd,",
              "\tFreeGoodsRedeemedInd,",
              "\tAdjKey,",
              "",
              "\tQuantity,",
              "\tSalesAmt,",
              "\tGPAmt,",
              "\tFSC_CommAmt,",
              "\tISR_CommAmt,",
              "\tESS_CommAmt,",
              "\tEPS_CommAmt,",
              "\tCPS_CommAmt,",
              "\tEST_CommAmt,",
              "",
              "\ths_branded_baseline_ind",
              "",
              "\t,OrderDateKey",
              "\t,backorder_ind",
              "",
              "FROM",
              "\tFact.Commission"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "SaleVendor"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Fact"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "--\ttop 10",
              "",
              "\tFactKey,",
              "\tFiscalMonth,",
              "",
              "\tFSC_SalespersonKey,",
              "\tFSC_SalespersonCodeKey,",
              "\tFSC_CommGroupKey,",
              "",
              "\tISR_SalespersonKey,",
              "\tISR_CommGroupKey,",
              "",
              "\tESS_SalespersonKey,",
              "\tESS_CommGroupKey,",
              "",
              "\tCPS_SalespersonKey,",
              "\tCPS_CommGroupKey,",
              "",
              "\tEPS_SalespersonKey,",
              "\tEPS_CommGroupKey,",
              "",
              "\tEST_SalespersonKey,",
              "\tEST_CommGroupKey,",
              "",
              "\tShipTo,",
              "\tItemKey,",
              "\tSalesOrderNumber,",
              "\tDocTypeKey,",
              "\tLineNumber,",
              "\tDateKey,",
              "\tBillTo,",
              "\tSourceKey,",
              "\tFreeGoodsInvoicedInd,",
              "\tFreeGoodsEstInd,",
              "\tFreeGoodsRedeemedInd,",
              "\tAdjKey,",
              "",
              "\tQuantity,",
              "\tSalesAmt,",
              "\tGPAmt,",
              "\tFSC_CommAmt,",
              "\tISR_CommAmt,",
              "\tESS_CommAmt,",
              "\tEPS_CommAmt,",
              "\tCPS_CommAmt,",
              "\tEST_CommAmt,",
              "",
              "\ths_branded_baseline_ind",
              "",
              "\t,OrderDateKey",
              "\t,backorder_ind",
              "",
              "FROM",
              "\tFact.Commission</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FactKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FiscalMonth\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FSC_SalespersonKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FSC_CommGroupKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ESS_SalespersonKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ESS_CommGroupKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ShipTo\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ItemKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"SalesOrderNumber\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"DocTypeKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"LineNumber\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"DateKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"BillTo\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"SourceKey\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FreeGoodsEstInd\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FreeGoodsRedeemedInd\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"Quantity\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"SalesAmt\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"GPAmt\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"FSC_CommAmt\" /><ColumnExpression Schema=\"Fact\" ColumnOwner=\"Commission\" ColumnName=\"ESS_CommAmt\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period Select",
        "columns": [
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MonthName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "QuarterName",
            "sourceProviderType": "Char"
          },
          {
            "name": "YearNum",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "YearNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "WorkingDaysMonth",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthSeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthSeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInQtr",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInYear",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "LastWorkingDay",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastWorkingDay",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          }
        ],
        "partitions": [
          {
            "name": "Fiscal_Month_List",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Period].* FROM [Dimension].[Period] ",
              "dataSource": "Commission SQL Source"
            }
          }
        ],
        "measures": [
          {
            "name": "__first_month_current",
            "expression": "max('Period Select'[FiscalMonth])",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_current",
            "expression": "calculate(max('Period Select'[MonthSeq]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_year",
            "expression": "calculate(max('Period Select'[FirstMonthSeqInYear]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_quarter",
            "expression": "calculate(max('Period Select'[FirstMonthSeqInQtr]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Period].* FROM [Dimension].[Period] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Period"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Salesorder",
        "columns": [
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DocType",
            "dataType": "string",
            "sourceColumn": "DocType",
            "sourceProviderType": "Char"
          },
          {
            "name": "OrderSource",
            "dataType": "string",
            "sourceColumn": "OrderSource",
            "sourceProviderType": "Char"
          },
          {
            "name": "EnteredByCode",
            "dataType": "string",
            "sourceColumn": "EnteredByCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "OrderTakenByCode",
            "dataType": "string",
            "sourceColumn": "OrderTakenByCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "EquipmentOrderNumber",
            "dataType": "string",
            "sourceColumn": "EquipmentOrderNumber",
            "sourceProviderType": "Char"
          },
          {
            "name": "CustomerPOText1",
            "dataType": "string",
            "sourceColumn": "CustomerPOText1",
            "sourceProviderType": "Char"
          },
          {
            "type": "calculated",
            "name": "FSC and Customer eBiz",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "if([OrderTakenByCode]=\"FSC\",\"Aruba FSC\", if([OrderTakenByCode]=\"CUSTOMER\" || [OrderTakenByCode]=\"DCORBZ\", \"Aruba Web\", \"CSR\"))"
          }
        ],
        "partitions": [
          {
            "name": "SalesorderCommission",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "SELECT [Dimension].[SalesorderCommission].* FROM [Dimension].[SalesorderCommission]",
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Dimension].[SalesorderCommission].* FROM [Dimension].[SalesorderCommission]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [Dimension].[SalesorderCommission].* FROM [Dimension].[SalesorderCommission]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "SalesorderCommission"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Dimension].[SalesorderCommission].* FROM [Dimension].[SalesorderCommission]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "CommGroup_FSC",
        "columns": [
          {
            "name": "CommGroupCode_FSC",
            "dataType": "string",
            "sourceColumn": "CommGroupCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "CommGroupKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CommGroupKey"
          },
          {
            "name": "comm_group_scorecard_cd",
            "dataType": "string",
            "sourceColumn": "comm_group_scorecard_cd"
          },
          {
            "name": "CommGroup",
            "dataType": "string",
            "sourceColumn": "CommGroup"
          },
          {
            "name": "CommGroupRollup",
            "dataType": "string",
            "sourceColumn": "CommGroupRollup"
          }
        ],
        "partitions": [
          {
            "name": "CommissionGroup",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "  Dimension.CommissionGroup.CommGroupKey",
                "  ,Dimension.CommissionGroup.CommGroup",
                "  ,Dimension.CommissionGroup.CommGroupCode",
                " , comm_group_scorecard_cd",
                " , CommGroupRollup",
                "",
                "FROM",
                "  Dimension.CommissionGroup"
              ],
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.CommissionGroup.CommGroupKey",
                  "  ,Dimension.CommissionGroup.CommGroup",
                  "  ,Dimension.CommissionGroup.CommGroupCode",
                  " , comm_group_scorecard_cd",
                  " , CommGroupRollup",
                  "",
                  "FROM",
                  "  Dimension.CommissionGroup</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.CommissionGroup.CommGroupKey",
              "  ,Dimension.CommissionGroup.CommGroup",
              "  ,Dimension.CommissionGroup.CommGroupCode",
              " , comm_group_scorecard_cd",
              "",
              "FROM",
              "  Dimension.CommissionGroup"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "CommissionGroup"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.CommissionGroup.CommGroupKey",
              "  ,Dimension.CommissionGroup.CommGroup",
              "  ,Dimension.CommissionGroup.CommGroupCode",
              " , comm_group_scorecard_cd",
              " , CommGroupRollup",
              "",
              "FROM",
              "  Dimension.CommissionGroup</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "CommGroup_ESS",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupCode_ESS",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupCode_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupKey",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[CommGroupKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "comm_group_scorecard_cd",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[comm_group_scorecard_cd]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroup]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupRollup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupRollup]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommGroup_FSC"
            }
          }
        ]
      },
      {
        "name": "CommSalesperson_FSC",
        "columns": [
          {
            "name": "EmployeeNumber_FSC",
            "dataType": "int64",
            "sourceColumn": "EmployeeNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CommMasterCode",
            "dataType": "string",
            "sourceColumn": "CommMasterCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalespersonName",
            "dataType": "string",
            "sourceColumn": "SalespersonName",
            "sourceProviderType": "Char"
          },
          {
            "name": "CommPlanCode",
            "dataType": "string",
            "sourceColumn": "CommPlanCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "TerritoryStart",
            "dataType": "string",
            "sourceColumn": "TerritoryStart",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SalespersonID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalespersonID",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalespersonKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalespersonKey",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "BranchCount",
            "dataType": "int64",
            "sourceColumn": "BranchCount"
          },
          {
            "name": "BranchCode",
            "dataType": "string",
            "sourceColumn": "BranchCode"
          },
          {
            "name": "BranchName",
            "dataType": "string",
            "sourceColumn": "BranchName"
          },
          {
            "name": "ZoneName",
            "dataType": "string",
            "sourceColumn": "ZoneName"
          },
          {
            "name": "tracker_ind",
            "dataType": "boolean",
            "sourceColumn": "tracker_ind"
          },
          {
            "name": "sf_adpt_login_score",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_adpt_login_score"
          },
          {
            "name": "sf_adpt_created_opps_score",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_adpt_created_opps_score"
          },
          {
            "name": "sf_adpt_activity_score",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_adpt_activity_score"
          },
          {
            "name": "sf_adpt_pastdue_opps_score",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_adpt_pastdue_opps_score"
          },
          {
            "name": "sf_adpt_closed_opps_score",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_adpt_closed_opps_score"
          },
          {
            "name": "sf_opps_equipment_technology_cnt",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_opps_equipment_technology_cnt"
          },
          {
            "name": "sf_opps_cadcam_digitial_imaging_cnt",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_opps_cadcam_digitial_imaging_cnt"
          },
          {
            "name": "sf_opps_merchandise_cnt",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_opps_merchandise_cnt"
          },
          {
            "name": "sf_opps_other_cnt",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sf_opps_other_cnt"
          },
          {
            "name": "sf_opps_equipment_technology_amt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "sf_opps_equipment_technology_amt"
          },
          {
            "name": "sf_opps_cadcam_digitial_imaging_amt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "sf_opps_cadcam_digitial_imaging_amt"
          },
          {
            "name": "sf_opps_merchandise_amt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "sf_opps_merchandise_amt"
          },
          {
            "name": "sf_opps_other_amt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "sf_opps_other_amt"
          },
          {
            "type": "calculated",
            "name": "Years of Service",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "year(now()) - year([TerritoryStart])"
          }
        ],
        "partitions": [
          {
            "name": "SalespersonCommission",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT [Dimension].[SalespersonCommission].[SalespersonKey],[Dimension].[SalespersonCommission].[EmployeeNumber],[Dimension].[SalespersonCommission].[CommMasterCode],[Dimension].[SalespersonCommission].[SalespersonName],[Dimension].[SalespersonCommission].[CommPlanCode],[Dimension].[SalespersonCommission].[TerritoryStart],[Dimension].[SalespersonCommission].[SalespersonID], BranchCount,",
                "[BranchCode], [BranchName], [ZoneName], tracker_ind",
                "",
                "\t-- tmc\tadd salesforce adoption and opportunity for playbook, 19 Jul 21",
                "\t,sf_adpt_login_score ",
                "\t,sf_adpt_created_opps_score ",
                "\t,sf_adpt_activity_score ",
                "\t,sf_adpt_pastdue_opps_score ",
                "\t,sf_adpt_closed_opps_score ",
                "",
                "\t,sf_opps_equipment_technology_cnt",
                "\t,sf_opps_cadcam_digitial_imaging_cnt",
                "\t,sf_opps_merchandise_cnt",
                "\t,sf_opps_other_cnt",
                "",
                "\t,sf_opps_equipment_technology_amt",
                "\t,sf_opps_cadcam_digitial_imaging_amt",
                "\t,sf_opps_merchandise_amt",
                "\t,sf_opps_other_amt",
                "",
                " ",
                "FROM [Dimension].[SalespersonCommission]"
              ],
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Dimension].[SalespersonCommission].[SalespersonKey],[Dimension].[SalespersonCommission].[EmployeeNumber],[Dimension].[SalespersonCommission].[CommMasterCode],[Dimension].[SalespersonCommission].[SalespersonName],[Dimension].[SalespersonCommission].[CommPlanCode],[Dimension].[SalespersonCommission].[TerritoryStart],[Dimension].[SalespersonCommission].[SalespersonID], BranchCount,",
                  "[BranchCode], [BranchName], [ZoneName], tracker_ind",
                  "",
                  "\t-- tmc\tadd salesforce adoption and opportunity for playbook, 19 Jul 21",
                  "\t,sf_adpt_login_score ",
                  "\t,sf_adpt_created_opps_score ",
                  "\t,sf_adpt_activity_score ",
                  "\t,sf_adpt_pastdue_opps_score ",
                  "\t,sf_adpt_closed_opps_score ",
                  "",
                  "\t,sf_opps_equipment_technology_cnt",
                  "\t,sf_opps_cadcam_digitial_imaging_cnt",
                  "\t,sf_opps_merchandise_cnt",
                  "\t,sf_opps_other_cnt",
                  "",
                  "\t,sf_opps_equipment_technology_amt",
                  "\t,sf_opps_cadcam_digitial_imaging_amt",
                  "\t,sf_opps_merchandise_amt",
                  "\t,sf_opps_other_amt",
                  "",
                  " ",
                  "FROM [Dimension].[SalespersonCommission]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "_Count of Salesperson_FSC",
            "expression": "COUNTA([EmployeeNumber_FSC])"
          },
          {
            "name": "Sum of sf_adpt_login_score",
            "expression": "SUM([sf_adpt_login_score])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_adpt_created_opps_score",
            "expression": "SUM([sf_adpt_created_opps_score])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_adpt_activity_score",
            "expression": "SUM([sf_adpt_activity_score])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_adpt_pastdue_opps_score",
            "expression": "SUM([sf_adpt_pastdue_opps_score])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_adpt_closed_opps_score",
            "expression": "SUM([sf_adpt_closed_opps_score])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_opps_equipment_technology_cnt",
            "expression": "SUM([sf_opps_equipment_technology_cnt])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_opps_cadcam_digitial_imaging_cnt",
            "expression": "SUM([sf_opps_cadcam_digitial_imaging_cnt])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_opps_merchandise_cnt",
            "expression": "SUM([sf_opps_merchandise_cnt])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_opps_other_cnt",
            "expression": "SUM([sf_opps_other_cnt])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_opps_equipment_technology_amt",
            "expression": "SUM([sf_opps_equipment_technology_amt])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_opps_cadcam_digitial_imaging_amt",
            "expression": "SUM([sf_opps_cadcam_digitial_imaging_amt])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_opps_merchandise_amt",
            "expression": "SUM([sf_opps_merchandise_amt])",
            "isHidden": true
          },
          {
            "name": "Sum of sf_opps_other_amt",
            "expression": "SUM([sf_opps_other_amt])",
            "isHidden": true
          },
          {
            "name": "SalesForce Adoption Score",
            "expression": "[Sum of sf_adpt_activity_score]+[Sum of sf_adpt_closed_opps_score]+[Sum of sf_adpt_created_opps_score]+[Sum of sf_adpt_login_score]+[Sum of sf_adpt_pastdue_opps_score]",
            "formatString": "0"
          },
          {
            "name": "SalesForce Opportunity - Equipment & Technology Count",
            "expression": "[Sum of sf_opps_equipment_technology_cnt]",
            "formatString": "0"
          },
          {
            "name": "SalesForce Opportunity - CAD/CAM & DI Count",
            "expression": "[Sum of sf_opps_cadcam_digitial_imaging_cnt]",
            "formatString": "0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT [Dimension].[SalespersonCommission].[SalespersonKey],[Dimension].[SalespersonCommission].[EmployeeNumber],[Dimension].[SalespersonCommission].[CommMasterCode],[Dimension].[SalespersonCommission].[SalespersonName],[Dimension].[SalespersonCommission].[CommPlanCode],[Dimension].[SalespersonCommission].[TerritoryStart],[Dimension].[SalespersonCommission].[SalespersonID], BranchCount,",
              "[BranchCode], [BranchName], [ZoneName], tracker_ind",
              "",
              "\t-- tmc\tadd salesforce adoption and opportunity for playbook, 19 Jul 21",
              "\t,sf_adpt_login_score ",
              "\t,sf_adpt_created_opps_score ",
              "\t,sf_adpt_activity_score ",
              "\t,sf_adpt_pastdue_opps_score ",
              "\t,sf_adpt_closed_opps_score ",
              "",
              "\t,sf_opps_equipment_technology_cnt",
              "\t,sf_opps_cadcam_digitial_imaging_cnt",
              "\t,sf_opps_merchandise_cnt",
              "\t,sf_opps_other_cnt",
              "",
              "\t,sf_opps_equipment_technology_amt",
              "\t,sf_opps_cadcam_digitial_imaging_amt",
              "\t,sf_opps_merchandise_amt",
              "\t,sf_opps_other_amt",
              "",
              " ",
              "FROM [Dimension].[SalespersonCommission]"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "SalespersonCommission"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Dimension].[SalespersonCommission].[SalespersonKey],[Dimension].[SalespersonCommission].[EmployeeNumber],[Dimension].[SalespersonCommission].[CommMasterCode],[Dimension].[SalespersonCommission].[SalespersonName],[Dimension].[SalespersonCommission].[CommPlanCode],[Dimension].[SalespersonCommission].[TerritoryStart],[Dimension].[SalespersonCommission].[SalespersonID], BranchCount,",
              "[BranchCode], [BranchName], [ZoneName], tracker_ind",
              "",
              "\t-- tmc\tadd salesforce adoption and opportunity for playbook, 19 Jul 21",
              "\t,sf_adpt_login_score ",
              "\t,sf_adpt_created_opps_score ",
              "\t,sf_adpt_activity_score ",
              "\t,sf_adpt_pastdue_opps_score ",
              "\t,sf_adpt_closed_opps_score ",
              "",
              "\t,sf_opps_equipment_technology_cnt",
              "\t,sf_opps_cadcam_digitial_imaging_cnt",
              "\t,sf_opps_merchandise_cnt",
              "\t,sf_opps_other_cnt",
              "",
              "\t,sf_opps_equipment_technology_amt",
              "\t,sf_opps_cadcam_digitial_imaging_amt",
              "\t,sf_opps_merchandise_amt",
              "\t,sf_opps_other_amt",
              "",
              " ",
              "FROM [Dimension].[SalespersonCommission]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "CommSalesperson_ESS",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "EmployeeNumber_ESS",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[EmployeeNumber_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommMasterCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommMasterCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommPlanCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommPlanCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "TerritoryStart",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[TerritoryStart]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonID",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonID]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCount",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCount]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "ZoneName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[ZoneName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "tracker_ind",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[tracker_ind]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_login_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_login_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_created_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_created_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_activity_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_activity_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_pastdue_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_pastdue_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_closed_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_closed_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Years of Service",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[Years of Service]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommSalesperson_FSC"
            }
          }
        ]
      },
      {
        "name": "CommSource",
        "columns": [
          {
            "name": "source_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "source_key",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "CommSourceCode",
            "dataType": "string",
            "sourceColumn": "CommSourceCode"
          },
          {
            "name": "CommSource",
            "dataType": "string",
            "sourceColumn": "CommSource"
          }
        ],
        "partitions": [
          {
            "name": "source",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "SELECT [comm].[source].[source_cd] as CommSourceCode,[comm].[source].[source_desc] AS CommSource,[comm].[source].[source_key] FROM [comm].[source]",
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [comm].[source].[source_cd] as CommSourceCode,[comm].[source].[source_desc] AS CommSource,[comm].[source].[source_key] FROM [comm].[source]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [comm].[source].[source_cd] as CommSourceCode,[comm].[source].[source_desc] AS CommSource,[comm].[source].[source_key] FROM [comm].[source]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "source"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "comm"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [comm].[source].[source_cd] as CommSourceCode,[comm].[source].[source_desc] AS CommSource,[comm].[source].[source_key] FROM [comm].[source]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "DocType",
        "columns": [
          {
            "name": "DocType",
            "dataType": "string",
            "sourceColumn": "DocType",
            "sourceProviderType": "Char"
          },
          {
            "name": "DocTypeDescr",
            "dataType": "string",
            "sourceColumn": "DocTypeDescr",
            "sourceProviderType": "Char"
          },
          {
            "name": "SourceCd",
            "dataType": "string",
            "sourceColumn": "SourceCd",
            "sourceProviderType": "Char"
          },
          {
            "name": "DocTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DocTypeKey",
            "sourceProviderType": "Integer"
          },
          {
            "type": "calculated",
            "name": "TransType",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "left([DocType],1)"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DocType",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "  BRS_DocType.DocType",
                "  ,BRS_DocType.DocTypeDescr",
                "  ,BRS_DocType.SourceCd",
                "  ,BRS_DocType.DocTypeKey",
                " FROM",
                "  BRS_DocType ",
                "WHERE",
                "  BRS_DocType.StatusCd = 1"
              ],
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  BRS_DocType.DocType",
                  "  ,BRS_DocType.DocTypeDescr",
                  "  ,BRS_DocType.SourceCd",
                  "  ,BRS_DocType.DocTypeKey",
                  " FROM",
                  "  BRS_DocType ",
                  "WHERE",
                  "  BRS_DocType.StatusCd = 1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"DocType\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"DocTypeDescr\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"SourceCd\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"StatusCd\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"FreeGoodsEstInd\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"DocTypeKey\" /></SelectedColumns><Filters><Filter Operator=\"=\"><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"StatusCd\" /><FilterValue>1</FilterValue></Filter></Filters></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  BRS_DocType.DocType",
              "  ,BRS_DocType.DocTypeDescr",
              "  ,BRS_DocType.SourceCd",
              "  ,BRS_DocType.DocTypeKey",
              " FROM",
              "  BRS_DocType ",
              "WHERE",
              "  BRS_DocType.StatusCd = 1"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DocType"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  BRS_DocType.DocType",
              "  ,BRS_DocType.DocTypeDescr",
              "  ,BRS_DocType.SourceCd",
              "  ,BRS_DocType.DocTypeKey",
              " FROM",
              "  BRS_DocType ",
              "WHERE",
              "  BRS_DocType.StatusCd = 1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"DocType\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"DocTypeDescr\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"SourceCd\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"StatusCd\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"FreeGoodsEstInd\" /><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"DocTypeKey\" /></SelectedColumns><Filters><Filter Operator=\"=\"><ColumnExpression ColumnOwner=\"BRS_DocType\" ColumnName=\"StatusCd\" /><FilterValue>1</FilterValue></Filter></Filters></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "CommSalespersonCode_FSC",
        "columns": [
          {
            "name": "FSC_SalespersonCode",
            "dataType": "string",
            "sourceColumn": "FSC_SalespersonCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalespersonName",
            "dataType": "string",
            "sourceColumn": "SalespersonName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "FSC_SalespersonCodeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FSC_SalespersonCodeKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FSCRollup",
            "dataType": "string",
            "sourceColumn": "FSCRollup",
            "sourceProviderType": "Char"
          },
          {
            "name": "BranchCode",
            "dataType": "string",
            "sourceColumn": "BranchCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "BranchName",
            "dataType": "string",
            "sourceColumn": "BranchName",
            "sourceProviderType": "Char"
          },
          {
            "name": "ZoneName",
            "dataType": "string",
            "sourceColumn": "ZoneName",
            "sourceProviderType": "Char"
          },
          {
            "name": "EmployeeNumber",
            "dataType": "int64",
            "sourceColumn": "EmployeeNumber"
          },
          {
            "name": "CommPlanCode",
            "dataType": "string",
            "sourceColumn": "CommPlanCode"
          },
          {
            "name": "TerritoryStart",
            "dataType": "string",
            "sourceColumn": "TerritoryStart"
          }
        ],
        "partitions": [
          {
            "name": "SalespersonCodeCommission",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "  Dimension.SalespersonCodeCommission.FSC_SalespersonCode",
                "  ,Dimension.SalespersonCodeCommission.SalespersonName",
                "  ,Dimension.SalespersonCodeCommission.EmployeeNumber",
                "  ,Dimension.SalespersonCodeCommission.CommPlanCode",
                "  ,Dimension.SalespersonCodeCommission.TerritoryStart",
                "  ,Dimension.SalespersonCodeCommission.FSC_SalespersonCodeKey",
                "  ,Dimension.SalespersonCodeCommission.FSCRollup",
                "  ,Dimension.SalespersonCodeCommission.BranchCode",
                "  ,Dimension.SalespersonCodeCommission.BranchName",
                "  ,Dimension.SalespersonCodeCommission.ZoneName",
                "FROM",
                "  Dimension.SalespersonCodeCommission"
              ],
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.SalespersonCodeCommission.FSC_SalespersonCode",
                  "  ,Dimension.SalespersonCodeCommission.SalespersonName",
                  "  ,Dimension.SalespersonCodeCommission.EmployeeNumber",
                  "  ,Dimension.SalespersonCodeCommission.CommPlanCode",
                  "  ,Dimension.SalespersonCodeCommission.TerritoryStart",
                  "  ,Dimension.SalespersonCodeCommission.FSC_SalespersonCodeKey",
                  "  ,Dimension.SalespersonCodeCommission.FSCRollup",
                  "  ,Dimension.SalespersonCodeCommission.BranchCode",
                  "  ,Dimension.SalespersonCodeCommission.BranchName",
                  "  ,Dimension.SalespersonCodeCommission.ZoneName",
                  "FROM",
                  "  Dimension.SalespersonCodeCommission</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"FSC_SalespersonCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"SalespersonName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"EmployeeNumber\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"CommPlanCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"TerritoryStart\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"FSC_SalespersonCodeKey\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"FSCRollup\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"BranchCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"BranchName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"ZoneName\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "_Count of SalespersonCode FSC",
            "expression": "COUNTA([FSC_SalespersonCode])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.SalespersonCodeCommission.FSC_SalespersonCode",
              "  ,Dimension.SalespersonCodeCommission.SalespersonName",
              "  ,Dimension.SalespersonCodeCommission.EmployeeNumber",
              "  ,Dimension.SalespersonCodeCommission.CommPlanCode",
              "  ,Dimension.SalespersonCodeCommission.TerritoryStart",
              "  ,Dimension.SalespersonCodeCommission.FSC_SalespersonCodeKey",
              "  ,Dimension.SalespersonCodeCommission.FSCRollup",
              "  ,Dimension.SalespersonCodeCommission.BranchCode",
              "  ,Dimension.SalespersonCodeCommission.BranchName",
              "  ,Dimension.SalespersonCodeCommission.ZoneName",
              "FROM",
              "  Dimension.SalespersonCodeCommission"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "SalespersonCodeCommission"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.SalespersonCodeCommission.FSC_SalespersonCode",
              "  ,Dimension.SalespersonCodeCommission.SalespersonName",
              "  ,Dimension.SalespersonCodeCommission.EmployeeNumber",
              "  ,Dimension.SalespersonCodeCommission.CommPlanCode",
              "  ,Dimension.SalespersonCodeCommission.TerritoryStart",
              "  ,Dimension.SalespersonCodeCommission.FSC_SalespersonCodeKey",
              "  ,Dimension.SalespersonCodeCommission.FSCRollup",
              "  ,Dimension.SalespersonCodeCommission.BranchCode",
              "  ,Dimension.SalespersonCodeCommission.BranchName",
              "  ,Dimension.SalespersonCodeCommission.ZoneName",
              "FROM",
              "  Dimension.SalespersonCodeCommission</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"FSC_SalespersonCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"SalespersonName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"EmployeeNumber\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"CommPlanCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"TerritoryStart\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"FSC_SalespersonCodeKey\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"FSCRollup\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"BranchCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"BranchName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"SalespersonCodeCommission\" ColumnName=\"ZoneName\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "CommSalesperson_CPS",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "EmployeeNumber_CPS",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[EmployeeNumber_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommMasterCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommMasterCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommPlanCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommPlanCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "TerritoryStart",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[TerritoryStart]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonID",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonID]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCount",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCount]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "ZoneName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[ZoneName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "tracker_ind",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[tracker_ind]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_login_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_login_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_created_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_created_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_activity_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_activity_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_pastdue_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_pastdue_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_closed_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_closed_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Years of Service",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[Years of Service]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommSalesperson_FSC"
            }
          }
        ]
      },
      {
        "name": "CommSalesperson_EPS",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "EmployeeNumber_EPS",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[EmployeeNumber_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommMasterCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommMasterCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommPlanCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommPlanCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "TerritoryStart",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[TerritoryStart]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonID",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonID]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCount",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCount]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "ZoneName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[ZoneName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "tracker_ind",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[tracker_ind]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_login_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_login_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_created_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_created_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_activity_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_activity_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_pastdue_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_pastdue_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_closed_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_closed_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Years of Service",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[Years of Service]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommSalesperson_FSC"
            }
          }
        ]
      },
      {
        "name": "CommGroup_CPS",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupCode_CPS",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupCode_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[CommGroupKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "comm_group_scorecard_cd",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[comm_group_scorecard_cd]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroup]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupRollup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupRollup]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommGroup_FSC"
            }
          }
        ]
      },
      {
        "name": "CommGroup_EPS",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupCode_EPS",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupCode_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[CommGroupKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "comm_group_scorecard_cd",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[comm_group_scorecard_cd]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroup]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupRollup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupRollup]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommGroup_FSC"
            }
          }
        ]
      },
      {
        "name": "CommAdjust",
        "columns": [
          {
            "name": "adj_comment_org",
            "dataType": "string",
            "sourceColumn": "adj_comment_org",
            "sourceProviderType": "Char"
          },
          {
            "name": "adj_source_org",
            "dataType": "string",
            "sourceColumn": "adj_source_org",
            "sourceProviderType": "Char"
          },
          {
            "name": "source_cd",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "source_cd",
            "sourceProviderType": "Char"
          },
          {
            "name": "adj_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "adj_key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "adj_source",
            "dataType": "string",
            "sourceColumn": "adj_source",
            "sourceProviderType": "Char"
          },
          {
            "name": "adj_type",
            "dataType": "string",
            "sourceColumn": "adj_type",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "CommAdjust",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [comm].[adjustment].[adj_comment_org],[comm].[adjustment].[adj_source_org],[comm].[adjustment].[source_cd],[comm].[adjustment].[adj_key],[comm].[adjustment].[adj_source],[comm].[adjustment].[adj_type] FROM [comm].[adjustment] ",
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_comment_org</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>170</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_source_org</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>142</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>source_cd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_key</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>68</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_source</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>123</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_note</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>183</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_comment_org</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_source_org</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>source_cd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_key</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_source</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_type</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_note</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>adj_note</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [comm].[adjustment].[adj_comment_org],[comm].[adjustment].[adj_source_org],[comm].[adjustment].[source_cd],[comm].[adjustment].[adj_key],[comm].[adjustment].[adj_source],[comm].[adjustment].[adj_type] FROM [comm].[adjustment] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "adjustment"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "comm"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>adj_comment_org</string>",
              "      </key>",
              "      <value>",
              "        <int>170</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_source_org</string>",
              "      </key>",
              "      <value>",
              "        <int>142</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>source_cd</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_key</string>",
              "      </key>",
              "      <value>",
              "        <int>68</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_source</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_type</string>",
              "      </key>",
              "      <value>",
              "        <int>123</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_note</string>",
              "      </key>",
              "      <value>",
              "        <int>183</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>adj_comment_org</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_source_org</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>source_cd</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_key</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_source</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_type</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>adj_note</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>adj_note</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "CommSalesperson_ISR",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "EmployeeNumber_ISR",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[EmployeeNumber_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommMasterCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommMasterCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommPlanCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommPlanCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "TerritoryStart",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[TerritoryStart]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonID",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonID]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCount",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCount]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "ZoneName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[ZoneName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "tracker_ind",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[tracker_ind]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_login_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_login_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_created_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_created_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_activity_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_activity_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_pastdue_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_pastdue_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_closed_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_closed_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Years of Service",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[Years of Service]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommSalesperson_FSC"
            }
          }
        ]
      },
      {
        "name": "CommGroup_ISR",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupCode_ISR",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupCode_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[CommGroupKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "comm_group_scorecard_cd",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[comm_group_scorecard_cd]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroup]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupRollup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupRollup]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommGroup_FSC"
            }
          }
        ]
      },
      {
        "name": "CommGroup_EST",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupCode_EST",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupCode_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[CommGroupKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "comm_group_scorecard_cd",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommGroup_FSC[comm_group_scorecard_cd]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroup]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommGroupRollup",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommGroup_FSC[CommGroupRollup]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommGroup_FSC"
            }
          }
        ]
      },
      {
        "name": "CommSalesperson_EST",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "EmployeeNumber_EST",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[EmployeeNumber_FSC]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommMasterCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommMasterCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CommPlanCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[CommPlanCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "TerritoryStart",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[TerritoryStart]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonID",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonID]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalespersonKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[SalespersonKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCount",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCount]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchCode",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchCode]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "BranchName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[BranchName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "ZoneName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[ZoneName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "tracker_ind",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[tracker_ind]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_login_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_login_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_created_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_created_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_activity_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_activity_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_pastdue_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_pastdue_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_adpt_closed_opps_score",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_adpt_closed_opps_score]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_cnt",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_cnt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_equipment_technology_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_equipment_technology_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_cadcam_digitial_imaging_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_cadcam_digitial_imaging_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_merchandise_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_merchandise_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "sf_opps_other_amt",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "CommSalesperson_FSC[sf_opps_other_amt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Years of Service",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "CommSalesperson_FSC[Years of Service]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CommSalesperson_FSC"
            }
          }
        ]
      },
      {
        "name": "Period Select YearFactor",
        "columns": [
          {
            "name": "YearFactor",
            "dataType": "int64",
            "sourceColumn": "YearFactor",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Period Select YearFactor",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_FiscalYearFactor].[YearFactor] FROM [dbo].[BRS_FiscalYearFactor] ",
              "dataSource": "Commission SQL Source"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearFactor</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>83</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Note</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>53</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearFactor</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Note</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Note</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "__year_factor",
            "expression": "min([YearFactor])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_FiscalYearFactor].[YearFactor] FROM [dbo].[BRS_FiscalYearFactor] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_FiscalYearFactor"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>YearFactor</string>",
              "      </key>",
              "      <value>",
              "        <int>83</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Note</string>",
              "      </key>",
              "      <value>",
              "        <int>53</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>YearFactor</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Note</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Note</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "97c6f6e8-5fbf-4329-8154-440eac8eecd0",
        "fromTable": "Sales",
        "fromColumn": "ItemKey",
        "toTable": "Item",
        "toColumn": "ItemKey"
      },
      {
        "name": "a6ee38fc-b57c-4c27-a5c0-984af0f429a8",
        "fromTable": "Sales",
        "fromColumn": "ShipTo",
        "toTable": "Customer",
        "toColumn": "ShipTo"
      },
      {
        "name": "d44baecf-b705-4535-ba67-437a692b182e",
        "fromTable": "Sales",
        "fromColumn": "FiscalMonth",
        "toTable": "Period",
        "toColumn": "FiscalMonth"
      },
      {
        "name": "52a3db26-7f9f-42ef-b23a-a51a1d89d823",
        "fromTable": "Sales",
        "fromColumn": "SalesOrderNumber",
        "toTable": "Salesorder",
        "toColumn": "SalesOrderNumber"
      },
      {
        "name": "6da5f4b1-7439-4814-8355-80866112fc7a",
        "fromTable": "Sales",
        "fromColumn": "FSC_SalespersonKey",
        "toTable": "CommSalesperson_FSC",
        "toColumn": "SalespersonKey"
      },
      {
        "name": "f5555d54-68f3-40a2-ab4d-77a154f7e010",
        "fromTable": "Sales",
        "fromColumn": "ESS_SalespersonKey",
        "toTable": "CommSalesperson_ESS",
        "toColumn": "SalespersonKey"
      },
      {
        "name": "bd9abf93-71d0-4e31-bd0d-8fa31936599e",
        "fromTable": "Sales",
        "fromColumn": "SourceKey",
        "toTable": "CommSource",
        "toColumn": "source_key"
      },
      {
        "name": "000cbd98-1f4b-46f2-bd4c-cddbc44dbba0",
        "fromTable": "Sales",
        "fromColumn": "DocTypeKey",
        "toTable": "DocType",
        "toColumn": "DocTypeKey"
      },
      {
        "name": "9c9c63ae-f194-49af-baab-d41d5e838786",
        "fromTable": "Sales",
        "fromColumn": "FSC_CommGroupKey",
        "toTable": "CommGroup_FSC",
        "toColumn": "CommGroupKey"
      },
      {
        "name": "e3132829-bde7-4936-b74d-ab8b83ae0f9e",
        "fromTable": "Sales",
        "fromColumn": "ESS_CommGroupKey",
        "toTable": "CommGroup_ESS",
        "toColumn": "CommGroupKey"
      },
      {
        "name": "b86a72af-7e06-491f-bf3f-edef37279c54",
        "fromTable": "Sales",
        "fromColumn": "FSC_SalespersonCodeKey",
        "toTable": "CommSalespersonCode_FSC",
        "toColumn": "FSC_SalespersonCodeKey"
      },
      {
        "name": "d359c253-2b8c-4b33-a96b-0ab3bcff6fd0",
        "fromTable": "Sales",
        "fromColumn": "CPS_SalespersonKey",
        "toTable": "CommSalesperson_CPS",
        "toColumn": "SalespersonKey"
      },
      {
        "name": "39d10bea-8aec-43fe-b256-0c39add75bb2",
        "fromTable": "Sales",
        "fromColumn": "EPS_SalespersonKey",
        "toTable": "CommSalesperson_EPS",
        "toColumn": "SalespersonKey"
      },
      {
        "name": "e911fce9-3ef1-4ac1-84f3-abb254ac0d59",
        "fromTable": "Sales",
        "fromColumn": "CPS_CommGroupKey",
        "toTable": "CommGroup_CPS",
        "toColumn": "CommGroupKey"
      },
      {
        "name": "9169b8a9-67e0-4d25-8564-66ccf725cb2b",
        "fromTable": "Sales",
        "fromColumn": "EPS_CommGroupKey",
        "toTable": "CommGroup_EPS",
        "toColumn": "CommGroupKey"
      },
      {
        "name": "8c2217da-8c65-4219-8703-c7bc2398f0cc",
        "fromTable": "Sales",
        "fromColumn": "AdjKey",
        "toTable": "CommAdjust",
        "toColumn": "adj_key"
      },
      {
        "name": "66823e6d-b98f-49bc-8676-b69c5c9215e7",
        "fromTable": "Sales",
        "fromColumn": "ISR_SalespersonKey",
        "toTable": "CommSalesperson_ISR",
        "toColumn": "SalespersonKey"
      },
      {
        "name": "4e04621c-da6a-40fa-a895-29f237413e87",
        "fromTable": "Sales",
        "fromColumn": "ISR_CommGroupKey",
        "toTable": "CommGroup_ISR",
        "toColumn": "CommGroupKey"
      },
      {
        "name": "07ffbbcf-126e-4405-b14b-8c157d1674ff",
        "fromTable": "Sales",
        "fromColumn": "EST_CommGroupKey",
        "toTable": "CommGroup_EST",
        "toColumn": "CommGroupKey"
      },
      {
        "name": "b4456c9b-6b01-4797-a87c-370276f040b1",
        "fromTable": "Sales",
        "fromColumn": "EST_SalespersonKey",
        "toTable": "CommSalesperson_EST",
        "toColumn": "SalespersonKey"
      }
    ],
    "roles": [
      {
        "name": "User Role",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "CAHSI\\tcrowley",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1815"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}