{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "SqlServer cahsionnlsql1 BRSales",
        "connectionString": "Provider=SQLNCLI11;Data Source=cahsionnlsql1;Persist Security Info=false;Initial Catalog=DEV_BRSales;User ID=tcrowley;Integrated Security=SSPI",
        "impersonationMode": "impersonateAccount",
        "account": "CAHSI\\tcrowley",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Sales",
        "columns": [
          {
            "name": "EntityKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EntityKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "HFM_Account_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "HFM_Account_key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "global_product_class_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "global_product_class_key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Excl_Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Excl_Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MarketClassKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MarketClassKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "gps_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "gps_key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "SupplierKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SupplierKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DocTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DocTypeKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "fact_id",
            "dataType": "int64",
            "sourceColumn": "ID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "GLBU_ClassKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GLBU_ClassKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "SalesDivision_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesDivision_key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Shipto",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Shipto",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "BranchKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BranchKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "AdjCodeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AdjCodeKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FreeGoodsEstInd",
            "dataType": "boolean",
            "sourceColumn": "FreeGoodsEstInd",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceProviderType": "Boolean"
          },
          {
            "name": "sales_amt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "sales_amt",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "gp_amt",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "gp_amt",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "LineNumber",
            "dataType": "int64",
            "sourceColumn": "LineNumber"
          },
          {
            "name": "SalesDate_ORG",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "SalesDate_ORG"
          },
          {
            "name": "day_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "day_key"
          },
          {
            "name": "GM Line",
            "dataType": "double",
            "sourceColumn": "gm_line",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "gm_line_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "gm_line_key"
          },
          {
            "name": "PriceMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PriceMethodKey"
          },
          {
            "name": "ID_Header",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID_Header"
          },
          {
            "name": "FreeGoodsInvoicedInd",
            "dataType": "boolean",
            "sourceColumn": "FreeGoodsInvoicedInd"
          },
          {
            "name": "ShippedQty",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShippedQty"
          }
        ],
        "partitions": [
          {
            "name": "global_cube_fact",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\tEntityKey",
                "\t,HFM_Account_key",
                "\t,global_product_class_key",
                "\t,Excl_Key",
                "\t,MarketClassKey",
                "\t,gps_key",
                "\t,SupplierKey",
                "\t,DocTypeKey",
                "\t,FiscalMonth",
                "\t,ID",
                "\t,GLBU_ClassKey",
                "\t,SalesDivision_key",
                "\t,SalesDate_ORG",
                "\t,day_key",
                "\t,Shipto",
                "\t,ItemKey",
                "\t,BranchKey",
                "\t,AdjCodeKey",
                "\t,SalesOrderNumber",
                "\t,LineNumber",
                "\t,FreeGoodsInvoicedInd",
                "\t,FreeGoodsEstInd",
                "\t,ShippedQty",
                "\t,sales_amt",
                "\t,gp_amt",
                "\t,gm_line",
                "\t,gm_line_key",
                "\t,PriceMethodKey",
                "\t,ID_Header",
                "FROM",
                "\tFact.global_cube"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "\tEntityKey",
                  "\t,HFM_Account_key",
                  "\t,global_product_class_key",
                  "\t,Excl_Key",
                  "\t,MarketClassKey",
                  "\t,gps_key",
                  "\t,SupplierKey",
                  "\t,DocTypeKey",
                  "\t,FiscalMonth",
                  "\t,ID",
                  "\t,GLBU_ClassKey",
                  "\t,SalesDivision_key",
                  "\t,SalesDate_ORG",
                  "\t,day_key",
                  "\t,Shipto",
                  "\t,ItemKey",
                  "\t,BranchKey",
                  "\t,AdjCodeKey",
                  "\t,SalesOrderNumber",
                  "\t,LineNumber",
                  "\t,FreeGoodsInvoicedInd",
                  "\t,FreeGoodsEstInd",
                  "\t,ShippedQty",
                  "\t,sales_amt",
                  "\t,gp_amt",
                  "\t,gm_line",
                  "\t,gm_line_key",
                  "\t,PriceMethodKey",
                  "\t,ID_Header",
                  "FROM",
                  "\tFact.global_cube</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales in Period",
            "expression": " SUM([sales_amt])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12 * 1)))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Var",
            "expression": " [MTD Sales]-[PY MTD Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12* 1) &&Period[MonthSeq]<=[__seq_first_month_current]-(12 * 1)))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Var",
            "expression": " [YTD Sales]-[PY YTD Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Var %",
            "expression": " DIVIDE([MTD Sales],[PY MTD Sales]) -1",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Sales Var %",
            "expression": " DIVIDE([YTD Sales],[PY YTD Sales])-1",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Rolling  3mo Sales",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Sales in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-3) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling  6mo Sales",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Sales in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-6) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling 12mo Sales",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Sales in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CY Sales (Est)",
            "expression": " [YTD Sales] * [__ytd_factor]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*1 ) &&Period[MonthSeq]<=[__seq_first_month_in_year]-1-12*(1-1) ))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "GP in Period",
            "expression": " SUM([gp_amt]) ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP",
            "expression": " CALCULATE([GP in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD GP",
            "expression": " CALCULATE([GP in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12 * 1)))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Var",
            "expression": " [MTD GP]-[PY MTD GP]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*1) &&Period[MonthSeq]<=[__seq_first_month_current]-(12*1)))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Var",
            "expression": " [YTD GP]-[PY YTD GP]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Var %",
            "expression": " DIVIDE([MTD GP],[PY MTD GP]) -1",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD GP Sales Var %",
            "expression": " DIVIDE([YTD GP],[PY YTD GP]) -1",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "GM in Period",
            "expression": "Divide([GP in Period],[Sales in Period])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD GM",
            "expression": " DIVIDE([MTD GP],[MTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD GM",
            "expression": " DIVIDE([YTD GP],[YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY MTD GM",
            "expression": " DIVIDE([PY MTD GP],[PY MTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY YTD GM",
            "expression": " DIVIDE([PY YTD GP],[PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Lines in Period",
            "expression": "COUNTA([LineNumber])",
            "formatString": "#,0"
          },
          {
            "name": "MTD Lines",
            "expression": " CALCULATE([Lines in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "Qty in Period",
            "expression": " sum([ShippedQty])",
            "formatString": "#,0"
          },
          {
            "name": "MTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "YTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY MTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-(12 * 1)))",
            "formatString": "#,0"
          },
          {
            "name": "MTD Qty Var",
            "expression": " [MTD Qty]-[PY MTD Qty]",
            "formatString": "#,0"
          },
          {
            "name": "PY YTD Qty",
            "expression": " CALCULATE([Qty in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-(12*1)&&Period[MonthSeq]<=[__seq_first_month_current]-(12*1)))",
            "formatString": "#,0"
          },
          {
            "name": "YTD Qty Var",
            "expression": " [YTD Qty]-[PY YTD Qty]",
            "formatString": "#,0"
          },
          {
            "name": "YTD Lines",
            "expression": " CALCULATE([Lines in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "Rolling  3mo Qty",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Qty in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-3) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Rolling  3mo Average Price",
            "expression": "DIVIDE([Rolling  3mo Sales],[Rolling  3mo Qty])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling  6mo Average Price",
            "expression": "DIVIDE([Rolling  6mo Sales],[Rolling  6mo Qty])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling  6mo Qty",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Qty in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-6) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Rolling 12mo Qty",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Qty in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Rolling 12mo Average Price",
            "expression": "DIVIDE([Rolling 12mo Sales],[Rolling 12mo Qty])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Average Price in Period",
            "expression": "DIVIDE([Sales in Period],[Qty in Period])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling 12mo Lines",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Lines in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Cost in Period",
            "expression": " [Sales in Period]-[GP in Period]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling  3mo Cost",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Cost in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-3) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling  6mo Cost",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Cost in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-6) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling 12mo Cost",
            "expression": [
              " ",
              "",
              "",
              "CALCULATE(",
              "",
              "        [Cost in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12) &&",
              "",
              "            Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling  3mo Average Cost",
            "expression": "DIVIDE([Rolling  3mo cost],[Rolling  3mo Qty])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling  6mo Average Cost",
            "expression": "DIVIDE([Rolling  6mo Cost],[Rolling  6mo Qty])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Rolling 12mo Average Cost",
            "expression": "DIVIDE([Rolling 12mo cost],[Rolling 12mo Qty])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Average Cost in Period",
            "expression": "DIVIDE([Cost in Period],[Qty in Period])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Distinct Count of ShipTo",
            "expression": "DISTINCTCOUNT([ShipTo])",
            "formatString": "#,0"
          },
          {
            "name": "Distinct Count of Orders",
            "expression": "DISTINCTCOUNT([SalesOrderNumber])",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "\tEntityKey",
              "\t,HFM_Account_key",
              "\t,global_product_class_key",
              "\t,Excl_Key",
              "\t,MarketClassKey",
              "\t,gps_key",
              "\t,SupplierKey",
              "\t,DocTypeKey",
              "\t,FiscalMonth",
              "\t,ID",
              "\t,GLBU_ClassKey",
              "\t,SalesDivision_key",
              "\t,SalesDate_ORG",
              "\t,day_key",
              "\t,Shipto",
              "\t,ItemKey",
              "\t,BranchKey",
              "\t,AdjCodeKey",
              "\t,SalesOrderNumber",
              "\t,LineNumber",
              "\t,FreeGoodsInvoicedInd",
              "\t,FreeGoodsEstInd",
              "\t,ShippedQty",
              "\t,sales_amt",
              "\t,gp_amt",
              "\t,gm_line",
              "\t,gm_line_key",
              "\t,PriceMethodKey",
              "\t,ID_Header",
              "FROM",
              "\tFact.global_cube"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "global_cube_fact"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "\tEntityKey",
              "\t,HFM_Account_key",
              "\t,global_product_class_key",
              "\t,Excl_Key",
              "\t,MarketClassKey",
              "\t,gps_key",
              "\t,SupplierKey",
              "\t,DocTypeKey",
              "\t,FiscalMonth",
              "\t,ID",
              "\t,GLBU_ClassKey",
              "\t,SalesDivision_key",
              "\t,SalesDate_ORG",
              "\t,day_key",
              "\t,Shipto",
              "\t,ItemKey",
              "\t,BranchKey",
              "\t,AdjCodeKey",
              "\t,SalesOrderNumber",
              "\t,LineNumber",
              "\t,FreeGoodsInvoicedInd",
              "\t,FreeGoodsEstInd",
              "\t,ShippedQty",
              "\t,sales_amt",
              "\t,gp_amt",
              "\t,gm_line",
              "\t,gm_line_key",
              "\t,PriceMethodKey",
              "\t,ID_Header",
              "FROM",
              "\tFact.global_cube</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "MarketClass",
        "columns": [
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClassDesc",
            "dataType": "string",
            "sourceColumn": "MarketClassDesc",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketRollup_L1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MarketRollup_L1",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketRollup_L2",
            "dataType": "string",
            "sourceColumn": "MarketRollup_L2",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketRollup_L3",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MarketRollup_L3",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClassKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MarketClassKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_CustomerMarketClass",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT        MarketClass, MarketClassDesc, MarketRollup_L1, MarketRollup_L2, MarketRollup_L3, MarketClassKey",
                "FROM            BRS_CustomerMarketClass"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        MarketClass, MarketClassDesc, MarketRollup_L1, MarketRollup_L2, MarketRollup_L3, MarketClassKey",
                  "FROM            BRS_CustomerMarketClass</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT        MarketClass, MarketClassDesc, MarketRollup_L1, MarketRollup_L2, MarketRollup_L3, MarketClassKey",
              "FROM            BRS_CustomerMarketClass"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_CustomerMarketClass"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        MarketClass, MarketClassDesc, MarketRollup_L1, MarketRollup_L2, MarketRollup_L3, MarketClassKey",
              "FROM            BRS_CustomerMarketClass</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Account",
        "columns": [
          {
            "name": "HFM_Account",
            "dataType": "string",
            "sourceColumn": "HFM_Account",
            "sourceProviderType": "WChar"
          },
          {
            "name": "HFM_Account_descr",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "HFM_Account_descr",
            "sourceProviderType": "WChar"
          },
          {
            "name": "HFM_Account_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "HFM_Account_key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "account",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT        HFM_Account, HFM_Account_descr, HFM_Account_key",
                "FROM            hfm.account"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        HFM_Account, HFM_Account_descr, HFM_Account_key",
                  "FROM            hfm.account</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT        HFM_Account, HFM_Account_descr, HFM_Account_key",
              "FROM            hfm.account"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "account"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "hfm"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        HFM_Account, HFM_Account_descr, HFM_Account_key",
              "FROM            hfm.account</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Entity",
        "columns": [
          {
            "name": "Entity",
            "dataType": "string",
            "sourceColumn": "Entity",
            "sourceProviderType": "WChar"
          },
          {
            "name": "EntityDescr",
            "dataType": "string",
            "sourceColumn": "EntityDescr",
            "sourceProviderType": "WChar"
          },
          {
            "name": "EntityKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EntityKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "entity",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT        Entity, EntityDescr, EntityKey",
                "FROM            hfm.entity"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        Entity, EntityDescr, EntityKey",
                  "FROM            hfm.entity</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT        Entity, EntityDescr, EntityKey",
              "FROM            hfm.entity"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "entity"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "hfm"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        Entity, EntityDescr, EntityKey",
              "FROM            hfm.entity</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Exclusive",
        "columns": [
          {
            "name": "Excl_Code",
            "dataType": "string",
            "sourceColumn": "Excl_Code",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Excl_Name",
            "dataType": "string",
            "sourceColumn": "Excl_Name",
            "sourceProviderType": "WChar"
          },
          {
            "name": "BrandEquityCategory",
            "dataType": "string",
            "sourceColumn": "BrandEquityCategory",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Excl_Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Excl_Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "eps_track_ind",
            "dataType": "boolean",
            "sourceColumn": "eps_track_ind",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceProviderType": "Boolean"
          }
        ],
        "partitions": [
          {
            "name": "exclusive_product",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "Excl_Code, Excl_Name, BrandEquityCategory, ",
                "Excl_Key, eps_track_ind",
                "                         ",
                "FROM            hfm.exclusive_product"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "Excl_Code, Excl_Name, BrandEquityCategory, ",
                  "Excl_Key, eps_track_ind",
                  "                         ",
                  "FROM            hfm.exclusive_product</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "Excl_Code, Excl_Name, BrandEquityCategory, ",
              "Excl_Key, eps_track_ind",
              "                         ",
              "FROM            hfm.exclusive_product"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "exclusive_product"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "hfm"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "Excl_Code, Excl_Name, BrandEquityCategory, ",
              "Excl_Key, eps_track_ind",
              "                         ",
              "FROM            hfm.exclusive_product</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "GPS",
        "columns": [
          {
            "name": "GpsCode",
            "dataType": "string",
            "sourceColumn": "GpsCode",
            "sourceProviderType": "WChar"
          },
          {
            "name": "GpsDescr",
            "dataType": "string",
            "sourceColumn": "GpsDescr",
            "sourceProviderType": "WChar"
          },
          {
            "name": "GpsKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GpsKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "gps_code",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [hfm].[gps_code].* FROM [hfm].[gps_code] ",
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [hfm].[gps_code].* FROM [hfm].[gps_code] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "gps_code"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "hfm"
          }
        ]
      },
      {
        "name": "Day",
        "columns": [
          {
            "name": "DayNumber",
            "dataType": "int64",
            "sourceColumn": "DayNumber",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "DayType",
            "dataType": "string",
            "sourceColumn": "DayType",
            "sourceProviderType": "Char"
          },
          {
            "name": "CalWeek",
            "dataType": "int64",
            "sourceColumn": "CalWeek"
          },
          {
            "name": "FiscWeekName",
            "dataType": "string",
            "sourceColumn": "FiscWeekName"
          },
          {
            "name": "SalesDay",
            "dataType": "dateTime",
            "sourceColumn": "SalesDay"
          },
          {
            "name": "day_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "day_key"
          }
        ],
        "partitions": [
          {
            "name": "Day",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT ",
                "\tday_key\t",
                "\t,SalesDay",
                "\t,DayNumber",
                "\t,DayType",
                "\t,[CalWeek]",
                "\t,[FiscWeekName]",
                "",
                "FROM",
                "Dimension.Day"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
                  "\tday_key\t",
                  "\t,SalesDay",
                  "\t,DayNumber",
                  "\t,DayType",
                  "\t,[CalWeek]",
                  "\t,[FiscWeekName]",
                  "",
                  "FROM",
                  "Dimension.Day</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT ",
              "\tday_key\t",
              "\t,SalesDay",
              "\t,DayNumber",
              "\t,DayType",
              "\t,[CalWeek]",
              "\t,[FiscWeekName]",
              "",
              "FROM",
              "Dimension.Day"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Day"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
              "\tday_key\t",
              "\t,SalesDay",
              "\t,DayNumber",
              "\t,DayType",
              "\t,[CalWeek]",
              "\t,[FiscWeekName]",
              "",
              "FROM",
              "Dimension.Day</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Item",
        "columns": [
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Item",
            "dataType": "string",
            "sourceColumn": "Item",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesCategory",
            "dataType": "string",
            "sourceColumn": "SalesCategory",
            "sourceProviderType": "Char"
          },
          {
            "name": "Top15",
            "dataType": "string",
            "sourceColumn": "Top15",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Major",
            "dataType": "string",
            "sourceColumn": "Major",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SubMajor",
            "dataType": "string",
            "sourceColumn": "SubMajor",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Minor",
            "dataType": "string",
            "sourceColumn": "Minor",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "Supplier",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ItemStatus",
            "dataType": "string",
            "sourceColumn": "ItemStatus",
            "sourceProviderType": "Char"
          },
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label",
            "sourceProviderType": "Char"
          },
          {
            "name": "MajorCode",
            "dataType": "string",
            "sourceColumn": "MajorCode",
            "sourceProviderType": "WChar"
          },
          {
            "name": "PrivateLabelScope_Item",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PrivateLabelScope_Item",
            "sourceProviderType": "Char"
          },
          {
            "name": "CurrentFileCost",
            "dataType": "decimal",
            "sourceColumn": "CurrentFileCost",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CurrentCorporatePrice",
            "dataType": "decimal",
            "sourceColumn": "CurrentCorporatePrice",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "ppe_code",
            "dataType": "string",
            "sourceColumn": "ppe_code",
            "sourceProviderType": "Char"
          },
          {
            "name": "Current_BasePrice",
            "dataType": "double",
            "sourceColumn": "Current_BasePrice"
          },
          {
            "name": "CommGroupCode",
            "dataType": "string",
            "sourceColumn": "CommGroupCode"
          },
          {
            "name": "adhoc_model_code",
            "dataType": "string",
            "sourceColumn": "adhoc_model_code"
          },
          {
            "name": "adhoc_model_code2",
            "dataType": "string",
            "sourceColumn": "adhoc_model_code2"
          },
          {
            "name": "adhoc_model_code3",
            "dataType": "string",
            "sourceColumn": "adhoc_model_code3"
          },
          {
            "name": "adhoc_model_code4",
            "dataType": "string",
            "sourceColumn": "adhoc_model_code4"
          },
          {
            "name": "adhoc_model_code5",
            "dataType": "string",
            "sourceColumn": "adhoc_model_code5"
          }
        ],
        "partitions": [
          {
            "name": "Item",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "",
                "ItemKey, Item, SalesCategory, Top15, Major, SubMajor, Minor, Supplier, ",
                "ItemStatus, Label, Current_BasePrice, MajorCode, PrivateLabelScope_Item, ",
                "                         CurrentFileCost, CurrentCorporatePrice, ppe_code, CommGroupCode, adhoc_model_code, adhoc_model_code2, adhoc_model_code3, adhoc_model_code4, adhoc_model_code5",
                "FROM            Dimension.Item"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "",
                  "ItemKey, Item, SalesCategory, Top15, Major, SubMajor, Minor, Supplier, ",
                  "ItemStatus, Label, Current_BasePrice, MajorCode, PrivateLabelScope_Item, ",
                  "                         CurrentFileCost, CurrentCorporatePrice, ppe_code, CommGroupCode, adhoc_model_code, adhoc_model_code2, adhoc_model_code3, adhoc_model_code4, adhoc_model_code5",
                  "FROM            Dimension.Item</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "",
              "ItemKey, Item, SalesCategory, Top15, Major, SubMajor, Minor, Supplier, ",
              "ItemStatus, Label, Current_BasePrice, MajorCode, PrivateLabelScope_Item, ",
              "                         CurrentFileCost, CurrentCorporatePrice, ppe_code, CommGroupCode, adhoc_model_code, adhoc_model_code2, adhoc_model_code3, adhoc_model_code4, adhoc_model_code5",
              "FROM            Dimension.Item"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Item"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "",
              "ItemKey, Item, SalesCategory, Top15, Major, SubMajor, Minor, Supplier, ",
              "ItemStatus, Label, Current_BasePrice, MajorCode, PrivateLabelScope_Item, ",
              "                         CurrentFileCost, CurrentCorporatePrice, ppe_code, CommGroupCode, adhoc_model_code, adhoc_model_code2, adhoc_model_code3, adhoc_model_code4, adhoc_model_code5",
              "FROM            Dimension.Item</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Supplier",
        "columns": [
          {
            "name": "SupplierKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SupplierKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "SupplierCode",
            "dataType": "string",
            "sourceColumn": "SupplierCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "SupplierName",
            "dataType": "string",
            "sourceColumn": "SupplierName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SupplierFamilyCode",
            "dataType": "string",
            "sourceColumn": "SupplierFamilyCode"
          },
          {
            "name": "SupplierBuyingGroupCode",
            "dataType": "string",
            "sourceColumn": "SupplierBuyingGroupCode"
          }
        ],
        "partitions": [
          {
            "name": "ItemSupplier",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\tSupplierKey",
                "\t, SupplierCode",
                "\t, SupplierName",
                "\t,[SupplierFamilyCode]",
                "\t,[SupplierBuyingGroupCode]",
                "",
                "FROM",
                "\tDimension.ItemSupplier"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "\tSupplierKey",
                  "\t, SupplierCode",
                  "\t, SupplierName",
                  "\t,[SupplierFamilyCode]",
                  "\t,[SupplierBuyingGroupCode]",
                  "",
                  "FROM",
                  "\tDimension.ItemSupplier</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "\tSupplierKey",
              "\t, SupplierCode",
              "\t, SupplierName",
              "\t,[SupplierFamilyCode]",
              "\t,[SupplierBuyingGroupCode]",
              "",
              "FROM",
              "\tDimension.ItemSupplier"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "ItemSupplier"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "\tSupplierKey",
              "\t, SupplierCode",
              "\t, SupplierName",
              "\t,[SupplierFamilyCode]",
              "\t,[SupplierBuyingGroupCode]",
              "",
              "FROM",
              "\tDimension.ItemSupplier</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period",
        "columns": [
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "sourceColumn": "MonthNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName",
            "sourceProviderType": "Char"
          },
          {
            "name": "YearNum",
            "dataType": "int64",
            "sourceColumn": "YearNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "sourceColumn": "WorkingDaysMonth",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthSeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthSeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInQtr",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInYear",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "LastWorkingDay",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastWorkingDay",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          }
        ],
        "partitions": [
          {
            "name": "Period",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Period].* FROM [Dimension].[Period] ",
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Period].* FROM [Dimension].[Period] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Period"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Branch",
        "columns": [
          {
            "name": "BranchKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BranchKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "BranchCode",
            "dataType": "string",
            "sourceColumn": "BranchCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "BranchName",
            "dataType": "string",
            "sourceColumn": "BranchName",
            "sourceProviderType": "Char"
          },
          {
            "name": "ZoneName",
            "dataType": "string",
            "sourceColumn": "ZoneName",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Branch",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Branch].* FROM [Dimension].[Branch] ",
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Branch].* FROM [Dimension].[Branch] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Branch"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "BusinessUnitClass",
        "columns": [
          {
            "name": "GLBU_Class",
            "dataType": "string",
            "sourceColumn": "GLBU_Class",
            "sourceProviderType": "Char"
          },
          {
            "name": "GLBU_ClassNm",
            "dataType": "string",
            "sourceColumn": "GLBU_ClassNm",
            "sourceProviderType": "Char"
          },
          {
            "name": "ReportingClass",
            "dataType": "string",
            "sourceColumn": "ReportingClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "GLBU_ClassKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GLBU_ClassKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_BusinessUnitClass",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "GLBU_Class, GLBU_ClassNm, ReportingClass,                         GLBU_ClassKey",
                "FROM            BRS_BusinessUnitClass"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "GLBU_Class, GLBU_ClassNm, ReportingClass,                         GLBU_ClassKey",
                  "FROM            BRS_BusinessUnitClass</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "GLBU_Class, GLBU_ClassNm, ReportingClass,                         GLBU_ClassKey",
              "FROM            BRS_BusinessUnitClass"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_BusinessUnitClass"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "GLBU_Class, GLBU_ClassNm, ReportingClass,                         GLBU_ClassKey",
              "FROM            BRS_BusinessUnitClass</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "SalesDivision",
        "columns": [
          {
            "name": "SalesDivision",
            "dataType": "string",
            "sourceColumn": "SalesDivision",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivisionDesc",
            "dataType": "string",
            "sourceColumn": "SalesDivisionDesc",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivision_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesDivision_key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_SalesDivision",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "SalesDivision, SalesDivisionDesc, SalesDivision_key",
                "FROM            BRS_SalesDivision"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "SalesDivision, SalesDivisionDesc, SalesDivision_key",
                  "FROM            BRS_SalesDivision</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "SalesDivision, SalesDivisionDesc, SalesDivision_key",
              "FROM            BRS_SalesDivision"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_SalesDivision"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "SalesDivision, SalesDivisionDesc, SalesDivision_key",
              "FROM            BRS_SalesDivision</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "GlobalProduct",
        "columns": [
          {
            "name": "global_product_class",
            "dataType": "string",
            "sourceColumn": "global_product_class",
            "sourceProviderType": "Char"
          },
          {
            "name": "global_product_class_descr",
            "dataType": "string",
            "sourceColumn": "global_product_class_descr",
            "sourceProviderType": "WChar"
          },
          {
            "name": "level_num",
            "dataType": "int64",
            "sourceColumn": "level_num",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "global_product_class_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "global_product_class_key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "global_product",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "global_product_class, global_product_class_descr, level_num, global_product_class_key",
                "FROM            hfm.global_product"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "global_product_class, global_product_class_descr, level_num, global_product_class_key",
                  "FROM            hfm.global_product</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "global_product_class, global_product_class_descr, level_num, global_product_class_key",
              "FROM            hfm.global_product"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "global_product"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "hfm"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "global_product_class, global_product_class_descr, level_num, global_product_class_key",
              "FROM            hfm.global_product</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Adjustment",
        "columns": [
          {
            "name": "AdjCode",
            "dataType": "string",
            "sourceColumn": "AdjCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "AdjType",
            "dataType": "string",
            "sourceColumn": "AdjType",
            "sourceProviderType": "Char"
          },
          {
            "name": "AdjCodeDesc",
            "dataType": "string",
            "sourceColumn": "AdjCodeDesc",
            "sourceProviderType": "Char"
          },
          {
            "name": "AdjCodeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AdjCodeKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_AdjCode",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "AdjCode, AdjType, AdjCodeDesc, AdjCodeKey",
                "FROM            BRS_AdjCode"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "AdjCode, AdjType, AdjCodeDesc, AdjCodeKey",
                  "FROM            BRS_AdjCode</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "AdjCode, AdjType, AdjCodeDesc, AdjCodeKey",
              "FROM            BRS_AdjCode"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_AdjCode"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "AdjCode, AdjType, AdjCodeDesc, AdjCodeKey",
              "FROM            BRS_AdjCode</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "DocType",
        "columns": [
          {
            "name": "DocType",
            "dataType": "string",
            "sourceColumn": "DocType",
            "sourceProviderType": "Char"
          },
          {
            "name": "DocTypeDescr",
            "dataType": "string",
            "sourceColumn": "DocTypeDescr",
            "sourceProviderType": "Char"
          },
          {
            "name": "SourceCd",
            "dataType": "string",
            "sourceColumn": "SourceCd",
            "sourceProviderType": "Char"
          },
          {
            "name": "DocTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DocTypeKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DocType",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "DocType, DocTypeDescr, SourceCd, DocTypeKey",
                "FROM            BRS_DocType"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "DocType, DocTypeDescr, SourceCd, DocTypeKey",
                  "FROM            BRS_DocType</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "DocType, DocTypeDescr, SourceCd, DocTypeKey",
              "FROM            BRS_DocType"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DocType"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "DocType, DocTypeDescr, SourceCd, DocTypeKey",
              "FROM            BRS_DocType</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "ShipTo",
            "dataType": "int64",
            "sourceColumn": "ShipTo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Billto",
            "dataType": "int64",
            "sourceColumn": "Billto",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CustomerGroup",
            "dataType": "string",
            "sourceColumn": "CustomerGroup",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesPlan",
            "dataType": "string",
            "sourceColumn": "SalesPlan",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesPlanCode",
            "dataType": "string",
            "sourceColumn": "SalesPlanCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesPlanType",
            "dataType": "string",
            "sourceColumn": "SalesPlanType",
            "sourceProviderType": "Char"
          },
          {
            "name": "FieldSales",
            "dataType": "string",
            "sourceColumn": "FieldSales",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivision",
            "dataType": "string",
            "sourceColumn": "SalesDivision",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Specialty",
            "dataType": "string",
            "sourceColumn": "Specialty",
            "sourceProviderType": "Char"
          },
          {
            "name": "CustomerStatus",
            "dataType": "string",
            "sourceColumn": "CustomerStatus",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivisionCode",
            "dataType": "string",
            "sourceColumn": "SalesDivisionCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "BranchCode",
            "dataType": "string",
            "sourceColumn": "BranchCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClassCode",
            "dataType": "string",
            "sourceColumn": "MarketClassCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "FscTerritoryCd",
            "dataType": "string",
            "sourceColumn": "FscTerritoryCd",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "",
                "ShipTo, Billto, Customer, CustomerGroup, SalesPlan, SalesPlanCode, SalesPlanType, FieldSales, Branch, ",
                "SalesDivision, MarketClass, Segment, Specialty, CustomerStatus, ",
                "SalesDivisionCode, BranchCode, MarketClassCode, ",
                "FscTerritoryCd",
                "",
                "",
                "FROM            Dimension.Customer"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "",
                  "ShipTo, Billto, Customer, CustomerGroup, SalesPlan, SalesPlanCode, SalesPlanType, FieldSales, Branch, ",
                  "SalesDivision, MarketClass, Segment, Specialty, CustomerStatus, ",
                  "SalesDivisionCode, BranchCode, MarketClassCode, ",
                  "FscTerritoryCd",
                  "",
                  "",
                  "FROM            Dimension.Customer</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "",
              "ShipTo, Billto, Customer, CustomerGroup, SalesPlan, SalesPlanCode, SalesPlanType, FieldSales, Branch, ",
              "SalesDivision, MarketClass, Segment, Specialty, CustomerStatus, ",
              "SalesDivisionCode, BranchCode, MarketClassCode, ",
              "FscTerritoryCd",
              "",
              "",
              "FROM            Dimension.Customer"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "",
              "ShipTo, Billto, Customer, CustomerGroup, SalesPlan, SalesPlanCode, SalesPlanType, FieldSales, Branch, ",
              "SalesDivision, MarketClass, Segment, Specialty, CustomerStatus, ",
              "SalesDivisionCode, BranchCode, MarketClassCode, ",
              "FscTerritoryCd",
              "",
              "",
              "FROM            Dimension.Customer</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period Select",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "FiscalMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[FiscalMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "QuarterName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[QuarterName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[YearNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[WorkingDaysMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthSeq",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthSeq]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstMonthSeqInQtr]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstMonthSeqInYear]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "LastWorkingDay",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[LastWorkingDay]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "Period"
            }
          }
        ],
        "measures": [
          {
            "name": "__first_month_current",
            "expression": " max('Period Select'[FiscalMonth])",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_current",
            "expression": " calculate(max('Period Select'[MonthSeq]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_year",
            "expression": " calculate(max('Period Select'[FirstMonthSeqInYear]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_quarter",
            "expression": " calculate(max('Period Select'[FirstMonthSeqInQtr]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__first_month_number",
            "expression": " calculate(max('Period Select'[MonthNum]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__ytd_factor",
            "expression": "12/[__first_month_number]",
            "isHidden": true
          }
        ]
      },
      {
        "name": "GM Bin Lines",
        "columns": [
          {
            "name": "Spend_From",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Spend_From",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "Spend_To",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Spend_To",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "GM Bin Line",
            "dataType": "string",
            "sourceColumn": "Spend_Display",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "GM Status",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Spend_Rank",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "SpendKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SpendKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "gm_line_buckets",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "SELECT [dbo].[BRS_Customer_Spend_Category].[Spend_From],[dbo].[BRS_Customer_Spend_Category].[Spend_To],[dbo].[BRS_Customer_Spend_Category].[Spend_Display],[dbo].[BRS_Customer_Spend_Category].[Spend_Rank],[dbo].[BRS_Customer_Spend_Category].[SpendKey] FROM [dbo].[BRS_Customer_Spend_Category]  WHERE ([Spend_Category] = N'L')",
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[BRS_Customer_Spend_Category].[Spend_From],[dbo].[BRS_Customer_Spend_Category].[Spend_To],[dbo].[BRS_Customer_Spend_Category].[Spend_Display],[dbo].[BRS_Customer_Spend_Category].[Spend_Rank],[dbo].[BRS_Customer_Spend_Category].[SpendKey] FROM [dbo].[BRS_Customer_Spend_Category]  WHERE ([Spend_Category] = N'L')</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[BRS_Customer_Spend_Category].[Spend_From],[dbo].[BRS_Customer_Spend_Category].[Spend_To],[dbo].[BRS_Customer_Spend_Category].[Spend_Display],[dbo].[BRS_Customer_Spend_Category].[Spend_Rank],[dbo].[BRS_Customer_Spend_Category].[SpendKey] FROM [dbo].[BRS_Customer_Spend_Category]  WHERE ([Spend_Category] = N'L')"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "gm_line_buckets"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[BRS_Customer_Spend_Category].[Spend_From],[dbo].[BRS_Customer_Spend_Category].[Spend_To],[dbo].[BRS_Customer_Spend_Category].[Spend_Display],[dbo].[BRS_Customer_Spend_Category].[Spend_Rank],[dbo].[BRS_Customer_Spend_Category].[SpendKey] FROM [dbo].[BRS_Customer_Spend_Category]  WHERE ([Spend_Category] = N'L')</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Salesorder",
        "columns": [
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "OriginalSalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "OriginalSalesOrderNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "OrderSource",
            "dataType": "string",
            "sourceColumn": "OrderSource",
            "sourceProviderType": "Char"
          },
          {
            "name": "Promotion",
            "dataType": "string",
            "sourceColumn": "Promotion",
            "sourceProviderType": "WChar"
          },
          {
            "name": "PromotionTracking",
            "dataType": "string",
            "sourceColumn": "PromotionTracking",
            "sourceProviderType": "WChar"
          },
          {
            "name": "PromotionTrackingType",
            "dataType": "string",
            "sourceColumn": "PromotionTrackingType",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DocType",
            "dataType": "string",
            "sourceColumn": "DocType",
            "sourceProviderType": "Char"
          },
          {
            "name": "EnteredBy",
            "dataType": "string",
            "sourceColumn": "EnteredBy",
            "sourceProviderType": "Char"
          },
          {
            "name": "OrderTakenBy",
            "dataType": "string",
            "sourceColumn": "OrderTakenBy",
            "sourceProviderType": "Char"
          },
          {
            "name": "ID_Header",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ID_Header"
          },
          {
            "type": "calculated",
            "name": "gm_order",
            "dataType": "double",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DIVIDE([GP in Period],[Sales in Period])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "type": "calculated",
            "name": "GM Bin Orders",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CALCULATE(VALUES('GM Bin Lines'[GM Bin Line]), filter('GM Bin Lines',[gm_order] >='GM Bin Lines'[Spend_From] && [gm_order] < 'GM Bin Lines'[Spend_To]))"
          }
        ],
        "partitions": [
          {
            "name": "Salesorder_global",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT        SalesOrderNumber, OriginalSalesOrderNumber, OrderSource, Promotion, PromotionTracking, PromotionTrackingType, DocType, EnteredBy, OrderTakenBy, ID_Header",
                "FROM            Dimension.Salesorder_global"
              ],
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        SalesOrderNumber, OriginalSalesOrderNumber, OrderSource, Promotion, PromotionTracking, PromotionTrackingType, DocType, EnteredBy, OrderTakenBy, ID_Header",
                  "FROM            Dimension.Salesorder_global</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT        SalesOrderNumber, OriginalSalesOrderNumber, OrderSource, Promotion, PromotionTracking, PromotionTrackingType, DocType, EnteredBy, OrderTakenBy, ID_Header",
              "FROM            Dimension.Salesorder_global"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Salesorder_global"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        SalesOrderNumber, OriginalSalesOrderNumber, OrderSource, Promotion, PromotionTracking, PromotionTrackingType, DocType, EnteredBy, OrderTakenBy, ID_Header",
              "FROM            Dimension.Salesorder_global</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "PriceMethod",
        "columns": [
          {
            "name": "PriceMethod",
            "dataType": "string",
            "sourceColumn": "PriceMethod",
            "sourceProviderType": "Char"
          },
          {
            "name": "PriceMethodDescr",
            "dataType": "string",
            "sourceColumn": "PriceMethodDescr",
            "sourceProviderType": "WChar"
          },
          {
            "name": "PriceMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PriceMethodKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_PriceMethod",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_PriceMethod].[PriceMethod],[dbo].[BRS_PriceMethod].[PriceMethodDescr],[dbo].[BRS_PriceMethod].[PriceMethodKey] FROM [dbo].[BRS_PriceMethod] ",
              "dataSource": "SqlServer cahsionnlsql1 BRSales"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethod</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>89</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodDescr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>164</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup_L2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>180</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup_L3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>135</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethod</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodDescr</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup_L2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup_L3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup_L2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PriceMethodRollup_L3</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_PriceMethod].[PriceMethod],[dbo].[BRS_PriceMethod].[PriceMethodDescr],[dbo].[BRS_PriceMethod].[PriceMethodKey] FROM [dbo].[BRS_PriceMethod] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_PriceMethod"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethod</string>",
              "      </key>",
              "      <value>",
              "        <int>89</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodDescr</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup</string>",
              "      </key>",
              "      <value>",
              "        <int>164</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup_L2</string>",
              "      </key>",
              "      <value>",
              "        <int>180</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup_L3</string>",
              "      </key>",
              "      <value>",
              "        <int>135</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodKey</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethod</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodDescr</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup_L2</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup_L3</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodKey</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup_L2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PriceMethodRollup_L3</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "8b233931-128a-40a5-a7b5-87a9fb63fcc4",
        "fromTable": "Sales",
        "fromColumn": "MarketClassKey",
        "toTable": "MarketClass",
        "toColumn": "MarketClassKey"
      },
      {
        "name": "008d7013-ed96-4528-9036-bb24c1b51ed0",
        "fromTable": "Sales",
        "fromColumn": "HFM_Account_key",
        "toTable": "Account",
        "toColumn": "HFM_Account_key"
      },
      {
        "name": "79b52b09-9ad4-401a-b740-53854bc15178",
        "fromTable": "Sales",
        "fromColumn": "EntityKey",
        "toTable": "Entity",
        "toColumn": "EntityKey"
      },
      {
        "name": "5b37c32a-5b21-4483-bc16-c8ad73eaf308",
        "fromTable": "Sales",
        "fromColumn": "Excl_Key",
        "toTable": "Exclusive",
        "toColumn": "Excl_Key"
      },
      {
        "name": "5bb8ec0a-0c17-45ca-8bed-ddbadc0aaae0",
        "fromTable": "Sales",
        "fromColumn": "FiscalMonth",
        "toTable": "Period",
        "toColumn": "FiscalMonth"
      },
      {
        "name": "21115e0c-7bf6-404a-ac7a-831f98129f34",
        "fromTable": "Sales",
        "fromColumn": "gps_key",
        "toTable": "GPS",
        "toColumn": "GpsKey"
      },
      {
        "name": "1238b639-75b0-4310-bccc-288c7d57acac",
        "fromTable": "Sales",
        "fromColumn": "SupplierKey",
        "toTable": "Supplier",
        "toColumn": "SupplierKey"
      },
      {
        "name": "1544ba51-dee4-4254-8e91-669ae02609c0",
        "fromTable": "Sales",
        "fromColumn": "ItemKey",
        "toTable": "Item",
        "toColumn": "ItemKey"
      },
      {
        "name": "59692ee9-aff2-4393-9c55-141bde3311ad",
        "fromTable": "Sales",
        "fromColumn": "BranchKey",
        "toTable": "Branch",
        "toColumn": "BranchKey"
      },
      {
        "name": "87eb8787-201a-41bc-9d85-5547bb4bed2f",
        "fromTable": "Sales",
        "fromColumn": "SalesDivision_key",
        "toTable": "SalesDivision",
        "toColumn": "SalesDivision_key"
      },
      {
        "name": "e1647055-779b-42e8-8072-228a8d0c8fdc",
        "fromTable": "Sales",
        "fromColumn": "GLBU_ClassKey",
        "toTable": "BusinessUnitClass",
        "toColumn": "GLBU_ClassKey"
      },
      {
        "name": "1e4d28d5-fb92-416f-8f1b-a3d6dede6676",
        "fromTable": "Sales",
        "fromColumn": "global_product_class_key",
        "toTable": "GlobalProduct",
        "toColumn": "global_product_class_key"
      },
      {
        "name": "85051d95-7e38-4b75-be11-a822b52a82e4",
        "fromTable": "Sales",
        "fromColumn": "DocTypeKey",
        "toTable": "DocType",
        "toColumn": "DocTypeKey"
      },
      {
        "name": "d79a1abf-60b8-4c8f-9bea-8b7341b4ec5a",
        "fromTable": "Sales",
        "fromColumn": "AdjCodeKey",
        "toTable": "Adjustment",
        "toColumn": "AdjCodeKey"
      },
      {
        "name": "c6ead21d-c555-46ad-98ea-b7953e15886d",
        "fromTable": "Sales",
        "fromColumn": "Shipto",
        "toTable": "Customer",
        "toColumn": "ShipTo"
      },
      {
        "name": "798e7131-2711-40a6-8b2c-6e988520ac3c",
        "fromTable": "Sales",
        "fromColumn": "day_key",
        "toTable": "Day",
        "toColumn": "day_key"
      },
      {
        "name": "2d5af872-5bb7-4663-a277-b10fb543e83c",
        "fromTable": "Sales",
        "fromColumn": "gm_line_key",
        "toTable": "GM Bin Lines",
        "toColumn": "SpendKey"
      },
      {
        "name": "6525968e-98b7-4fa7-9dfe-e3f0d225927d",
        "fromTable": "Sales",
        "fromColumn": "PriceMethodKey",
        "toTable": "PriceMethod",
        "toColumn": "PriceMethodKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "06953749-edaa-49d7-b896-900d5f5d219f",
        "fromTable": "Sales",
        "fromColumn": "ID_Header",
        "toTable": "Salesorder",
        "toColumn": "ID_Header"
      }
    ],
    "roles": [
      {
        "name": "Role",
        "modelPermission": "readRefresh",
        "members": [
          {
            "memberName": "CAHSI\\tcrowley",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1815"
          },
          {
            "memberName": "CAHSI\\Gary.Winslow",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1322"
          },
          {
            "memberName": "CAHSI\\JLi",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-2414"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}