{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-CA",
    "dataSources": [
      {
        "name": "SqlServer CAHSIONNLSQL1BRSales",
        "connectionString": "Provider=SQLNCLI11;Data Source=CAHSIONNLSQL1;Initial Catalog=BRSales;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "CAHSI\\tcrowley",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Period",
        "columns": [
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "sourceColumn": "MonthNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName",
            "sourceProviderType": "Char"
          },
          {
            "name": "YearNum",
            "dataType": "int64",
            "sourceColumn": "YearNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "WorkingDaysMonth",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthSeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthSeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInQtr",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInYear",
            "sourceProviderType": "SmallInt"
          }
        ],
        "partitions": [
          {
            "name": "Period",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT",
                "  Dimension.Period.FiscalMonth",
                "  ,Dimension.Period.MonthName",
                "  ,Dimension.Period.MonthNum",
                "  ,Dimension.Period.QuarterName",
                "  ,Dimension.Period.YearNum",
                "  ,Dimension.Period.WorkingDaysMonth",
                "  ,Dimension.Period.MonthSeq",
                "  ,Dimension.Period.FirstMonthSeqInQtr",
                "  ,Dimension.Period.FirstMonthSeqInYear",
                "FROM",
                "  Dimension.Period"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Period.FiscalMonth",
                  "  ,Dimension.Period.MonthName",
                  "  ,Dimension.Period.MonthNum",
                  "  ,Dimension.Period.QuarterName",
                  "  ,Dimension.Period.YearNum",
                  "  ,Dimension.Period.WorkingDaysMonth",
                  "  ,Dimension.Period.MonthSeq",
                  "  ,Dimension.Period.FirstMonthSeqInQtr",
                  "  ,Dimension.Period.FirstMonthSeqInYear",
                  "FROM",
                  "  Dimension.Period</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FiscalMonth\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthNum\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"QuarterName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"YearNum\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"WorkingDaysMonth\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthSeq\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FirstMonthSeqInQtr\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FirstMonthSeqInYear\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Period.FiscalMonth",
              "  ,Dimension.Period.MonthName",
              "  ,Dimension.Period.MonthNum",
              "  ,Dimension.Period.QuarterName",
              "  ,Dimension.Period.YearNum",
              "  ,Dimension.Period.WorkingDaysMonth",
              "  ,Dimension.Period.MonthSeq",
              "  ,Dimension.Period.FirstMonthSeqInQtr",
              "  ,Dimension.Period.FirstMonthSeqInYear",
              "FROM",
              "  Dimension.Period"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Period"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Period.FiscalMonth",
              "  ,Dimension.Period.MonthName",
              "  ,Dimension.Period.MonthNum",
              "  ,Dimension.Period.QuarterName",
              "  ,Dimension.Period.YearNum",
              "  ,Dimension.Period.WorkingDaysMonth",
              "  ,Dimension.Period.MonthSeq",
              "  ,Dimension.Period.FirstMonthSeqInQtr",
              "  ,Dimension.Period.FirstMonthSeqInYear",
              "FROM",
              "  Dimension.Period</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FiscalMonth\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthNum\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"QuarterName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"YearNum\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"WorkingDaysMonth\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthSeq\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FirstMonthSeqInQtr\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FirstMonthSeqInYear\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sales",
        "columns": [
          {
            "name": "FactKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FactKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "BillTo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BillTo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ShipTo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShipTo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PriceMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PriceMethodKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DateKey",
            "dataType": "dateTime",
            "sourceColumn": "DateKey",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "LineNumber",
            "dataType": "int64",
            "sourceColumn": "LineNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FreeGoodsInvoicedInd",
            "dataType": "boolean",
            "sourceColumn": "FreeGoodsInvoicedInd",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceProviderType": "Boolean"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Quantity",
            "sourceProviderType": "Integer"
          },
          {
            "name": "SalesAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "SalesAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "GPAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "GPAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "GPAtCommCostAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "GPAtCommCostAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "ExtChargebackAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "ExtChargebackAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "ExtBaseAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "ExtBaseAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DiscountAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "DiscountAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DiscountLineAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "DiscountLineAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DiscountOrderAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "DiscountOrderAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sale_qt",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT",
                "",
                "--top 10",
                "",
                "\tFactKey,",
                "\tBillTo,",
                "\tShipTo,",
                "\tItemKey,",
                "\tPriceMethodKey,",
                "\tFiscalMonth,",
                "\tDateKey,",
                "\tSalesOrderNumber,",
                "\tLineNumber,",
                "\tFreeGoodsInvoicedInd,",
                "\tQuantity,",
                "\tSalesAmt,",
                "\tGPAmt,",
                "",
                "\tGPAtCommCostAmt,",
                "\tExtChargebackAmt,",
                "\tExtBaseAmt,",
                "\tDiscountAmt,",
                "\tDiscountLineAmt,",
                "\tDiscountOrderAmt",
                "FROM",
                "\tFact.Sale_qt",
                "WHERE ",
                "\tSalesCategory = 'MERCH' AND",
                "\tFreeGoodsInvoicedInd = 0"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "",
                  "--top 10",
                  "",
                  "\tFactKey,",
                  "\tBillTo,",
                  "\tShipTo,",
                  "\tItemKey,",
                  "\tPriceMethodKey,",
                  "\tFiscalMonth,",
                  "\tDateKey,",
                  "\tSalesOrderNumber,",
                  "\tLineNumber,",
                  "\tFreeGoodsInvoicedInd,",
                  "\tQuantity,",
                  "\tSalesAmt,",
                  "\tGPAmt,",
                  "",
                  "\tGPAtCommCostAmt,",
                  "\tExtChargebackAmt,",
                  "\tExtBaseAmt,",
                  "\tDiscountAmt,",
                  "\tDiscountLineAmt,",
                  "\tDiscountOrderAmt",
                  "FROM",
                  "\tFact.Sale_qt",
                  "WHERE ",
                  "\tSalesCategory = 'MERCH' AND",
                  "\tFreeGoodsInvoicedInd = 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales in Period",
            "expression": " SUM([SalesAmt])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "GP in Period",
            "expression": " SUM([GPAmt]) ",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Var",
            "expression": " [YTD Sales]-[PY YTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Var %",
            "expression": " DIVIDE([YTD Sales],[PY YTD Sales])-1",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "YTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Var",
            "expression": " [YTD GP]-[PY YTD GP]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Sales Var %",
            "expression": " DIVIDE([YTD GP],[PY YTD GP]) -1",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "YTD GM",
            "expression": " DIVIDE([YTD GP],[YTD Sales])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "PY YTD GM",
            "expression": "divide([YTD GP],[PY YTD Sales])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Quote Sales in Period",
            "expression": " CALCULATE ([Sales in Period] , 'Salesorder'[PriceMethodRollup] = \"Quote\") ",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Sales",
            "expression": " CALCULATE([Quote Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote PY YTD Sales",
            "expression": " CALCULATE([Quote Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Sales Var",
            "expression": " [Quote YTD Sales]-[Quote PY YTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Sales Var %",
            "expression": " DIVIDE([Quote YTD Sales],[Quote PY YTD Sales])-1",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Quote GP in Period",
            "expression": " CALCULATE ( [GP in Period], 'Salesorder'[PriceMethodRollup] = \"Quote\")",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD GP",
            "expression": " CALCULATE([Quote GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote PY YTD GP",
            "expression": " CALCULATE([Quote GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD GP Var",
            "expression": " [Quote YTD GP]-[Quote PY YTD GP]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD GP Sales Var %",
            "expression": " DIVIDE([Quote YTD GP],[Quote PY YTD GP]) -1",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Quote YTD GM",
            "expression": " DIVIDE([Quote YTD GP],[Quote YTD Sales])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Quote PY YTD GM",
            "expression": "divide([Quote YTD GP],[Quote PY YTD Sales])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Rolling 12mo Sales",
            "expression": [
              " ",
              "",
              "CALCULATE(",
              "",
              "        [Sales in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12) &&",
              "",
              "           Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              "",
              ""
            ],
            "formatString": "\\$#,0.0;-\\$#,0.0;\\$#,0.0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"1\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Sales Share",
            "expression": "DIVIDE([Quote YTD Sales],[YTD Sales])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Quote PY YTD Sales Share",
            "expression": "DIVIDE([Quote PY YTD Sales],[PY YTD Sales])",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Ext.Base in Period",
            "expression": " sum(Sales[ExtBaseAmt])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Ext.Base",
            "expression": " CALCULATE([Ext.Base in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Disc in Period",
            "expression": " sum(Sales[DiscountAmt])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Disc",
            "expression": " CALCULATE([Disc in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Disc%",
            "expression": " [YTD Disc]/[YTD Ext.Base]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          },
          {
            "name": "Quote Disc in Period",
            "expression": " CALCULATE([Disc in Period],  'Salesorder'[PriceMethodRollup] = \"Quote\")",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Disc",
            "expression": " CALCULATE([Quote Disc in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote Ext.Base in Period",
            "expression": " CALCULATE([Ext.Base in Period],  'Salesorder'[PriceMethodRollup] = \"Quote\")",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Ext.Base",
            "expression": " CALCULATE([Quote Ext.Base in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Disc%",
            "expression": " [Quote YTD Disc]/[Quote YTD Ext.Base]",
            "formatString": "0.0 %;-0.0 %;0.0 %"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "",
              "--top 10",
              "",
              "\tFactKey,",
              "\tBillTo,",
              "\tShipTo,",
              "\tItemKey,",
              "\tPriceMethodKey,",
              "\tFiscalMonth,",
              "\tDateKey,",
              "\tSalesOrderNumber,",
              "\tLineNumber,",
              "\tFreeGoodsInvoicedInd,",
              "\tQuantity,",
              "\tSalesAmt,",
              "\tGPAmt,",
              "",
              "\tGPAtCommCostAmt,",
              "\tExtChargebackAmt,",
              "\tExtBaseAmt,",
              "\tDiscountAmt,",
              "\tDiscountLineAmt,",
              "\tDiscountOrderAmt",
              "FROM",
              "\tFact.Sale_qt",
              "WHERE ",
              "\tSalesCategory = 'MERCH' AND",
              "\tFreeGoodsInvoicedInd = 0"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sale_qt"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Fact"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "",
              "--top 10",
              "",
              "\tFactKey,",
              "\tBillTo,",
              "\tShipTo,",
              "\tItemKey,",
              "\tPriceMethodKey,",
              "\tFiscalMonth,",
              "\tDateKey,",
              "\tSalesOrderNumber,",
              "\tLineNumber,",
              "\tFreeGoodsInvoicedInd,",
              "\tQuantity,",
              "\tSalesAmt,",
              "\tGPAmt,",
              "",
              "\tGPAtCommCostAmt,",
              "\tExtChargebackAmt,",
              "\tExtBaseAmt,",
              "\tDiscountAmt,",
              "\tDiscountLineAmt,",
              "\tDiscountOrderAmt",
              "FROM",
              "\tFact.Sale_qt",
              "WHERE ",
              "\tSalesCategory = 'MERCH' AND",
              "\tFreeGoodsInvoicedInd = 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Item",
        "columns": [
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Item",
            "dataType": "string",
            "sourceColumn": "Item",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesCategory",
            "dataType": "string",
            "sourceColumn": "SalesCategory",
            "sourceProviderType": "Char"
          },
          {
            "name": "CategoryRollup",
            "dataType": "string",
            "sourceColumn": "CategoryRollup",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Top15",
            "dataType": "string",
            "sourceColumn": "Top15",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "Supplier",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ItemCode",
            "dataType": "string",
            "sourceColumn": "ItemCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Item",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT        ",
                "\tItemKey,",
                "\tItem,",
                "\tSalesCategory,",
                "\tCategoryRollup,",
                "\tTop15,",
                "\tSupplier,",
                "\tItemCode,",
                "\tLabel",
                "FROM",
                "\tDimension.Item",
                "WHERE",
                "\tSalesCategoryCode = 'MERCH'"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        ",
                  "\tItemKey,",
                  "\tItem,",
                  "\tSalesCategory,",
                  "\tCategoryRollup,",
                  "\tTop15,",
                  "\tSupplier,",
                  "\tItemCode,",
                  "\tLabel",
                  "FROM",
                  "\tDimension.Item",
                  "WHERE",
                  "\tSalesCategoryCode = 'MERCH'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT        ",
              "\tItemKey,",
              "\tItem,",
              "\tSalesCategory,",
              "\tCategoryRollup,",
              "\tTop15,",
              "\tSupplier,",
              "\tItemCode,",
              "\tLabel",
              "FROM",
              "\tDimension.Item",
              "WHERE",
              "\tSalesCategoryCode = 'MERCH'"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Item"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT        ",
              "\tItemKey,",
              "\tItem,",
              "\tSalesCategory,",
              "\tCategoryRollup,",
              "\tTop15,",
              "\tSupplier,",
              "\tItemCode,",
              "\tLabel",
              "FROM",
              "\tDimension.Item",
              "WHERE",
              "\tSalesCategoryCode = 'MERCH'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Salesorder",
        "columns": [
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "OrderSource",
            "dataType": "string",
            "sourceColumn": "OrderSource",
            "sourceProviderType": "Char"
          },
          {
            "name": "PromotionType",
            "dataType": "string",
            "sourceColumn": "PromotionType",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Promotion",
            "dataType": "string",
            "sourceColumn": "Promotion",
            "sourceProviderType": "WChar"
          },
          {
            "name": "PromotionConvention",
            "dataType": "string",
            "sourceColumn": "PromotionConvention",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DocType",
            "dataType": "string",
            "sourceColumn": "DocType",
            "sourceProviderType": "Char"
          },
          {
            "name": "EnteredBy",
            "dataType": "string",
            "sourceColumn": "EnteredBy",
            "sourceProviderType": "Char"
          },
          {
            "name": "OrderTakenBy",
            "dataType": "string",
            "sourceColumn": "OrderTakenBy",
            "sourceProviderType": "Char"
          },
          {
            "name": "PriceMethod",
            "dataType": "string",
            "sourceColumn": "PriceMethod"
          },
          {
            "name": "PriceMethodRollup",
            "dataType": "string",
            "sourceColumn": "PriceMethodRollup"
          }
        ],
        "partitions": [
          {
            "name": "Salesorder",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT",
                "  Dimension.Salesorder_qt.SalesOrderNumber",
                "  ,Dimension.Salesorder_qt.PriceMethod",
                "  ,Dimension.Salesorder_qt.PriceMethodRollup",
                "  ,Dimension.Salesorder_qt.OrderSource",
                "  ,Dimension.Salesorder_qt.PromotionType",
                "  ,Dimension.Salesorder_qt.Promotion",
                "  ,Dimension.Salesorder_qt.PromotionConvention",
                "  ,Dimension.Salesorder_qt.DocType",
                "  ,Dimension.Salesorder_qt.EnteredBy",
                "  ,Dimension.Salesorder_qt.OrderTakenBy",
                "FROM",
                "  Dimension.Salesorder_qt"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Salesorder_qt.SalesOrderNumber",
                  "  ,Dimension.Salesorder_qt.PriceMethod",
                  "  ,Dimension.Salesorder_qt.PriceMethodRollup",
                  "  ,Dimension.Salesorder_qt.OrderSource",
                  "  ,Dimension.Salesorder_qt.PromotionType",
                  "  ,Dimension.Salesorder_qt.Promotion",
                  "  ,Dimension.Salesorder_qt.PromotionConvention",
                  "  ,Dimension.Salesorder_qt.DocType",
                  "  ,Dimension.Salesorder_qt.EnteredBy",
                  "  ,Dimension.Salesorder_qt.OrderTakenBy",
                  "FROM",
                  "  Dimension.Salesorder_qt</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"SalesOrderNumber\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"PriceMethod\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"PriceMethodRollup\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"OrderSource\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"PromotionType\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"Promotion\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"PromotionConvention\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"DocType\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"EnteredBy\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"OrderTakenBy\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Salesorder_qt.SalesOrderNumber",
              "  ,Dimension.Salesorder_qt.PriceMethod",
              "  ,Dimension.Salesorder_qt.PriceMethodRollup",
              "  ,Dimension.Salesorder_qt.OrderSource",
              "  ,Dimension.Salesorder_qt.PromotionType",
              "  ,Dimension.Salesorder_qt.Promotion",
              "  ,Dimension.Salesorder_qt.PromotionConvention",
              "  ,Dimension.Salesorder_qt.DocType",
              "  ,Dimension.Salesorder_qt.EnteredBy",
              "  ,Dimension.Salesorder_qt.OrderTakenBy",
              "FROM",
              "  Dimension.Salesorder_qt"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Salesorder_qt"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Salesorder_qt.SalesOrderNumber",
              "  ,Dimension.Salesorder_qt.PriceMethod",
              "  ,Dimension.Salesorder_qt.PriceMethodRollup",
              "  ,Dimension.Salesorder_qt.OrderSource",
              "  ,Dimension.Salesorder_qt.PromotionType",
              "  ,Dimension.Salesorder_qt.Promotion",
              "  ,Dimension.Salesorder_qt.PromotionConvention",
              "  ,Dimension.Salesorder_qt.DocType",
              "  ,Dimension.Salesorder_qt.EnteredBy",
              "  ,Dimension.Salesorder_qt.OrderTakenBy",
              "FROM",
              "  Dimension.Salesorder_qt</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"SalesOrderNumber\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"PriceMethod\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"PriceMethodRollup\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"OrderSource\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"PromotionType\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"Promotion\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"PromotionConvention\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"DocType\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"EnteredBy\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Salesorder_qt\" ColumnName=\"OrderTakenBy\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "Billto",
            "dataType": "int64",
            "sourceColumn": "Billto",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ShipToPrimary",
            "dataType": "int64",
            "sourceColumn": "ShipToPrimary",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SalesPlan",
            "dataType": "string",
            "sourceColumn": "SalesPlan",
            "sourceProviderType": "Char"
          },
          {
            "name": "FieldSales",
            "dataType": "string",
            "sourceColumn": "FieldSales",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch",
            "sourceProviderType": "Char"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DateAccountOpened",
            "dataType": "dateTime",
            "sourceColumn": "DateAccountOpened",
            "formatString": "d-MMM-yy",
            "sourceProviderType": "DBDate",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"4105\" Group=\"LongDate\" FormatString=\"d-MMM-yy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "SalesDivisionCode",
            "dataType": "string",
            "sourceColumn": "SalesDivisionCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "Adjustment",
            "dataType": "string",
            "sourceColumn": "Adjustment"
          },
          {
            "name": "AdjEffectiveDate",
            "dataType": "dateTime",
            "sourceColumn": "AdjEffectiveDate",
            "formatString": "d-MMM-yy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"4105\" Group=\"LongDate\" FormatString=\"d-MMM-yy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NewPlanInd",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "if(Year([AdjEffectiveDate])>=[__current_year], 1, 0)"
          },
          {
            "type": "calculated",
            "name": "Quote Score",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH(TRUE(), [Quote YTD Sales]<=5000, \"\", [Quote YTD GM]<.32 && [YTD Sales Var %]<.2, \"Red\", [Quote YTD GM]>=.32 && [YTD Sales Var %]>=.2, \"Green\", \"Yellow\")"
          },
          {
            "type": "calculated",
            "name": "Spend Level",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "CALCULATE ( ",
              "\tVALUES('SpendRange'[Spend Range]),",
              "\t\tFILTER( ",
              "            SpendRange, ",
              "            'Sales'[Rolling 12mo Sales] >= 'SpendRange'[Spend Min]  && ",
              "            'Sales'[Rolling 12mo Sales] < 'SpendRange'[Spend Max]",
              "\t\t)",
              ") "
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT",
                "  Dimension.Customer_qt.Billto",
                "  ,Dimension.Customer_qt.ShipToPrimary",
                "  ,Dimension.Customer_qt.Customer",
                "  ,Dimension.Customer_qt.SalesPlan",
                "  ,Dimension.Customer_qt.FieldSales",
                "  ,Dimension.Customer_qt.Branch",
                "  ,Dimension.Customer_qt.City",
                "  ,Dimension.Customer_qt.DateAccountOpened",
                "  ,Dimension.Customer_qt.SalesDivisionCode",
                "  ,Dimension.Customer_qt.MarketClass",
                "  ,Dimension.Customer_qt.Adjustment",
                "  ,Dimension.Customer_qt.AdjEffectiveDate",
                "  ,Dimension.Customer_qt.AdjUserId",
                "FROM",
                "  Dimension.Customer_qt"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Customer_qt.Billto",
                  "  ,Dimension.Customer_qt.ShipToPrimary",
                  "  ,Dimension.Customer_qt.Customer",
                  "  ,Dimension.Customer_qt.SalesPlan",
                  "  ,Dimension.Customer_qt.FieldSales",
                  "  ,Dimension.Customer_qt.Branch",
                  "  ,Dimension.Customer_qt.City",
                  "  ,Dimension.Customer_qt.DateAccountOpened",
                  "  ,Dimension.Customer_qt.SalesDivisionCode",
                  "  ,Dimension.Customer_qt.MarketClass",
                  "  ,Dimension.Customer_qt.Adjustment",
                  "  ,Dimension.Customer_qt.AdjEffectiveDate",
                  "  ,Dimension.Customer_qt.AdjUserId",
                  "FROM",
                  "  Dimension.Customer_qt</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Billto\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"ShipToPrimary\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Customer\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"SalesPlan\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"FieldSales\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Branch\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"City\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"DateAccountOpened\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"SalesDivisionCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"MarketClass\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Adjustment\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"AdjEffectiveDate\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"AdjUserId\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Count of Billto",
            "expression": "COUNTA([Billto])"
          },
          {
            "name": "Tracked Account Ind",
            "expression": "1 "
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Customer_qt.Billto",
              "  ,Dimension.Customer_qt.ShipToPrimary",
              "  ,Dimension.Customer_qt.Customer",
              "  ,Dimension.Customer_qt.SalesPlan",
              "  ,Dimension.Customer_qt.FieldSales",
              "  ,Dimension.Customer_qt.Branch",
              "  ,Dimension.Customer_qt.City",
              "  ,Dimension.Customer_qt.DateAccountOpened",
              "  ,Dimension.Customer_qt.SalesDivisionCode",
              "  ,Dimension.Customer_qt.MarketClass",
              "  ,Dimension.Customer_qt.Adjustment",
              "  ,Dimension.Customer_qt.AdjEffectiveDate",
              "  ,Dimension.Customer_qt.AdjUserId",
              "FROM",
              "  Dimension.Customer_qt"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer_qt"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Customer_qt.Billto",
              "  ,Dimension.Customer_qt.ShipToPrimary",
              "  ,Dimension.Customer_qt.Customer",
              "  ,Dimension.Customer_qt.SalesPlan",
              "  ,Dimension.Customer_qt.FieldSales",
              "  ,Dimension.Customer_qt.Branch",
              "  ,Dimension.Customer_qt.City",
              "  ,Dimension.Customer_qt.DateAccountOpened",
              "  ,Dimension.Customer_qt.SalesDivisionCode",
              "  ,Dimension.Customer_qt.MarketClass",
              "  ,Dimension.Customer_qt.Adjustment",
              "  ,Dimension.Customer_qt.AdjEffectiveDate",
              "  ,Dimension.Customer_qt.AdjUserId",
              "FROM",
              "  Dimension.Customer_qt</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Billto\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"ShipToPrimary\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Customer\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"SalesPlan\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"FieldSales\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Branch\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"City\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"DateAccountOpened\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"SalesDivisionCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"MarketClass\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Adjustment\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"AdjEffectiveDate\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"AdjUserId\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period Select",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "FiscalMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[FiscalMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "QuarterName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[QuarterName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[YearNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[WorkingDaysMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthSeq",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthSeq]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstMonthSeqInQtr]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstMonthSeqInYear]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "Period"
            }
          }
        ],
        "measures": [
          {
            "name": "__first_month_current",
            "expression": " max('Period Select'[FiscalMonth])",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_current",
            "expression": " calculate(max('Period Select'[MonthSeq]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_year",
            "expression": " calculate(max('Period Select'[FirstMonthSeqInYear]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_quarter",
            "expression": " calculate(max('Period Select'[FirstMonthSeqInQtr]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__first_month_number",
            "expression": " calculate(max('Period Select'[FiscalMonth]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__ytd_factor",
            "expression": "12/[__first_month_number]",
            "isHidden": true
          },
          {
            "name": "__current_year",
            "expression": " calculate(max('Period Select'[YearNum]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          }
        ]
      },
      {
        "name": "SpendRange",
        "isHidden": true,
        "columns": [
          {
            "name": "Spend Min",
            "dataType": "double",
            "sourceColumn": "Spend Min",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "Spend Max",
            "dataType": "double",
            "sourceColumn": "Spend Max",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "Spend Range",
            "dataType": "string",
            "sourceColumn": "Spend Range",
            "sourceProviderType": "VarChar"
          }
        ],
        "partitions": [
          {
            "name": "SpendRange",
            "dataView": "full",
            "source": {
              "query": [
                "SELECT ",
                "      [Spend_From]\t\tAS [Spend Min]",
                "      ,[Spend_To]\t\tAS [Spend Max]",
                "      ,[Spend_Display]  AS [Spend Range]",
                "  FROM [BRS_Customer_Spend_Category]"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
                  "      [Spend_From]\t\tAS [Spend Min]",
                  "      ,[Spend_To]\t\tAS [Spend Max]",
                  "      ,[Spend_Display]  AS [Spend Range]",
                  "  FROM [BRS_Customer_Spend_Category]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT ",
              "      [Spend_From]\t\tAS [Spend Min]",
              "      ,[Spend_To]\t\tAS [Spend Max]",
              "      ,[Spend_Display]  AS [Spend Range]",
              "  FROM [BRS_Customer_Spend_Category]"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "SpendRange"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
              "      [Spend_From]\t\tAS [Spend Min]",
              "      ,[Spend_To]\t\tAS [Spend Max]",
              "      ,[Spend_Display]  AS [Spend Range]",
              "  FROM [BRS_Customer_Spend_Category]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a8e62166-6ac7-4dc0-ba4c-dd291fbd6a18",
        "fromTable": "Sales",
        "fromColumn": "ItemKey",
        "toTable": "Item",
        "toColumn": "ItemKey"
      },
      {
        "name": "e3687906-1ce1-4f47-8a0f-8137092a358a",
        "fromTable": "Sales",
        "fromColumn": "FiscalMonth",
        "toTable": "Period",
        "toColumn": "FiscalMonth"
      },
      {
        "name": "8db2abb5-09c3-414f-8170-a3ed35f8ce4d",
        "fromTable": "Sales",
        "fromColumn": "SalesOrderNumber",
        "toTable": "Salesorder",
        "toColumn": "SalesOrderNumber"
      },
      {
        "name": "981f08d8-1fed-485a-84e6-7a9dcd87f4e1",
        "fromTable": "Sales",
        "fromColumn": "BillTo",
        "toTable": "Customer",
        "toColumn": "Billto"
      }
    ],
    "roles": [
      {
        "name": "user",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "CAHSI\\TCrowley",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1815"
          },
          {
            "memberName": "CAHSI\\Gary.Winslow",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1322"
          },
          {
            "memberName": "CAHSI\\GWatson",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-5503"
          },
          {
            "memberName": "CAHSI\\Marco.Calabrese",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11954"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}