{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-CA",
    "dataSources": [
      {
        "name": "SqlServer CAHSIONNLSQL1BRSales",
        "connectionString": "Provider=SQLNCLI11;Data Source=CAHSIONNLSQL1;Initial Catalog=BRSales;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "CAHSI\\tcrowley",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Period",
        "columns": [
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "sourceColumn": "MonthNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName",
            "sourceProviderType": "Char"
          },
          {
            "name": "YearNum",
            "dataType": "int64",
            "sourceColumn": "YearNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "WorkingDaysMonth",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthSeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthSeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInQtr",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInYear",
            "sourceProviderType": "SmallInt"
          }
        ],
        "partitions": [
          {
            "name": "Period",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "  Dimension.Period.FiscalMonth",
                "  ,Dimension.Period.MonthName",
                "  ,Dimension.Period.MonthNum",
                "  ,Dimension.Period.QuarterName",
                "  ,Dimension.Period.YearNum",
                "  ,Dimension.Period.WorkingDaysMonth",
                "  ,Dimension.Period.MonthSeq",
                "  ,Dimension.Period.FirstMonthSeqInQtr",
                "  ,Dimension.Period.FirstMonthSeqInYear",
                "FROM",
                "  Dimension.Period"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Period.FiscalMonth",
                  "  ,Dimension.Period.MonthName",
                  "  ,Dimension.Period.MonthNum",
                  "  ,Dimension.Period.QuarterName",
                  "  ,Dimension.Period.YearNum",
                  "  ,Dimension.Period.WorkingDaysMonth",
                  "  ,Dimension.Period.MonthSeq",
                  "  ,Dimension.Period.FirstMonthSeqInQtr",
                  "  ,Dimension.Period.FirstMonthSeqInYear",
                  "FROM",
                  "  Dimension.Period</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FiscalMonth\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthNum\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"QuarterName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"YearNum\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"WorkingDaysMonth\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthSeq\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FirstMonthSeqInQtr\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FirstMonthSeqInYear\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Period.FiscalMonth",
              "  ,Dimension.Period.MonthName",
              "  ,Dimension.Period.MonthNum",
              "  ,Dimension.Period.QuarterName",
              "  ,Dimension.Period.YearNum",
              "  ,Dimension.Period.WorkingDaysMonth",
              "  ,Dimension.Period.MonthSeq",
              "  ,Dimension.Period.FirstMonthSeqInQtr",
              "  ,Dimension.Period.FirstMonthSeqInYear",
              "FROM",
              "  Dimension.Period"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Period"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Period.FiscalMonth",
              "  ,Dimension.Period.MonthName",
              "  ,Dimension.Period.MonthNum",
              "  ,Dimension.Period.QuarterName",
              "  ,Dimension.Period.YearNum",
              "  ,Dimension.Period.WorkingDaysMonth",
              "  ,Dimension.Period.MonthSeq",
              "  ,Dimension.Period.FirstMonthSeqInQtr",
              "  ,Dimension.Period.FirstMonthSeqInYear",
              "FROM",
              "  Dimension.Period</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FiscalMonth\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthNum\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"QuarterName\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"YearNum\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"WorkingDaysMonth\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"MonthSeq\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FirstMonthSeqInQtr\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Period\" ColumnName=\"FirstMonthSeqInYear\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sales",
        "columns": [
          {
            "name": "FactKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FactKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "BillTo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BillTo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ShipTo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShipTo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PriceMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PriceMethodKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DateKey",
            "dataType": "dateTime",
            "sourceColumn": "DateKey",
            "formatString": "yyyy-MM-dd",
            "sourceProviderType": "DBDate",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"yyyy-MM-dd\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "LineNumber",
            "dataType": "int64",
            "sourceColumn": "LineNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "FreeGoodsInvoicedInd",
            "dataType": "boolean",
            "sourceColumn": "FreeGoodsInvoicedInd",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceProviderType": "Boolean"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Quantity",
            "sourceProviderType": "Integer"
          },
          {
            "name": "SalesAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "SalesAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "GPAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "GPAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "GPAtCommCostAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "GPAtCommCostAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "ExtChargebackAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "ExtChargebackAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "ExtBaseAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "ExtBaseAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DiscountAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "DiscountAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DiscountLineAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "DiscountLineAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DiscountOrderAmt",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "DiscountOrderAmt",
            "formatString": "\\$#,0.00;-\\$#,0.00;\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "entered_by_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "entered_by_key"
          },
          {
            "name": "sales_order_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sales_order_key"
          },
          {
            "name": "MarketClassKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MarketClassKey"
          },
          {
            "name": "CreditKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CreditKey"
          }
        ],
        "partitions": [
          {
            "name": "Sale_qt",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\tFactKey,",
                "\tBillTo,",
                "\tShipTo,",
                "\tItemKey,",
                "\tPriceMethodKey,",
                "\t[entered_by_key],",
                "\tMarketClassKey,",
                "\tCreditKey,",
                "\tFiscalMonth,",
                "\tDateKey,",
                "\tsales_order_key,",
                "\tSalesOrderNumber,",
                "\tLineNumber,",
                "\tFreeGoodsInvoicedInd,",
                "\tQuantity,",
                "\tSalesAmt,",
                "\tGPAmt,",
                "",
                "\tGPAtCommCostAmt,",
                "\tExtChargebackAmt,",
                "\tExtBaseAmt,",
                "\tDiscountAmt,",
                "\tDiscountLineAmt,",
                "\tDiscountOrderAmt",
                "FROM",
                "\tFact.Sale_qt",
                "WHERE ",
                "\tSalesCategory = 'MERCH' AND",
                "\tFreeGoodsInvoicedInd = 0"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "\tFactKey,",
                  "\tBillTo,",
                  "\tShipTo,",
                  "\tItemKey,",
                  "\tPriceMethodKey,",
                  "\t[entered_by_key],",
                  "\tMarketClassKey,",
                  "\tCreditKey,",
                  "\tFiscalMonth,",
                  "\tDateKey,",
                  "\tsales_order_key,",
                  "\tSalesOrderNumber,",
                  "\tLineNumber,",
                  "\tFreeGoodsInvoicedInd,",
                  "\tQuantity,",
                  "\tSalesAmt,",
                  "\tGPAmt,",
                  "",
                  "\tGPAtCommCostAmt,",
                  "\tExtChargebackAmt,",
                  "\tExtBaseAmt,",
                  "\tDiscountAmt,",
                  "\tDiscountLineAmt,",
                  "\tDiscountOrderAmt",
                  "FROM",
                  "\tFact.Sale_qt",
                  "WHERE ",
                  "\tSalesCategory = 'MERCH' AND",
                  "\tFreeGoodsInvoicedInd = 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales in Period",
            "expression": " SUM([SalesAmt])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "GP in Period",
            "expression": " SUM([GPAtCommCostAmt]) ",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Sales",
            "expression": " CALCULATE([Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Var",
            "expression": " [YTD Sales]-[PY YTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Var %",
            "expression": " DIVIDE([YTD Sales]-[PY YTD Sales],[PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD GP",
            "expression": " CALCULATE([GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Var",
            "expression": " [YTD GP]-[PY YTD GP]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Var %",
            "expression": " DIVIDE([YTD GP]-[PY YTD GP],[PY YTD GP]) ",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD GM",
            "expression": " DIVIDE([YTD GP],[YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY YTD GM",
            "expression": "divide([YTD GP],[PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Quote Sales in Period",
            "expression": " CALCULATE ([Sales in Period] , 'Salesorder'[PriceMethodRollup] = \"Quote\") ",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Sales",
            "expression": " CALCULATE([Quote Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote PY YTD Sales",
            "expression": " CALCULATE([Quote Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Sales Var",
            "expression": " [Quote YTD Sales]-[Quote PY YTD Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Sales Var %",
            "expression": " DIVIDE([Quote YTD Sales]-[Quote PY YTD Sales],[Quote PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Quote GP in Period",
            "expression": " CALCULATE ( [GP in Period], 'Salesorder'[PriceMethodRollup] = \"Quote\")",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD GP",
            "expression": " CALCULATE([Quote GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote PY YTD GP",
            "expression": " CALCULATE([Quote GP in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD GP Var",
            "expression": " [Quote YTD GP]-[Quote PY YTD GP]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD GP Sales Var %",
            "expression": " DIVIDE([Quote YTD GP]-[Quote PY YTD GP],[Quote PY YTD GP]) ",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Quote YTD GM",
            "expression": " DIVIDE([Quote YTD GP],[Quote YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Quote PY YTD GM",
            "expression": "divide([Quote YTD GP],[Quote PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Rolling 12mo Sales",
            "expression": [
              " ",
              "",
              "CALCULATE(",
              "",
              "        [Sales in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12) &&",
              "",
              "           Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              "",
              ""
            ],
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Sales Share",
            "expression": "DIVIDE([Quote YTD Sales],[YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Quote PY YTD Sales Share",
            "expression": "DIVIDE([Quote PY YTD Sales],[PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Ext.Base in Period",
            "expression": " sum(Sales[ExtBaseAmt])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Ext.Base",
            "expression": " CALCULATE([Ext.Base in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Disc in Period",
            "expression": " sum(Sales[DiscountAmt])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Disc",
            "expression": " CALCULATE([Disc in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Disc%",
            "expression": " DIVIDE([YTD Disc],[YTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Quote Disc in Period",
            "expression": " CALCULATE([Disc in Period],  'Salesorder'[PriceMethodRollup] = \"Quote\")",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Disc",
            "expression": " CALCULATE([Quote Disc in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote Ext.Base in Period",
            "expression": " CALCULATE([Ext.Base in Period],  'Salesorder'[PriceMethodRollup] = \"Quote\")",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Ext.Base",
            "expression": " CALCULATE([Quote Ext.Base in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Quote YTD Disc%",
            "expression": " DIVIDE([Quote YTD Disc],[Quote YTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Sales",
            "expression": "CALCULATE([Sales in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP",
            "expression": "CALCULATE([GP in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Sales",
            "expression": "CALCULATE([Sales in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Var",
            "expression": "[MTD Sales]-[PY MTD Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Var %",
            "expression": "DIVIDE( [MTD Sales]-[PY MTD Sales],[PY MTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY MTD GP",
            "expression": "CALCULATE([GP in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Var",
            "expression": "[MTD GP]-[PY MTD GP]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Var %",
            "expression": "DIVIDE( [MTD GP] - [PY MTD GP], [PY MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY YTD Ext.Base",
            "expression": " CALCULATE([Ext.Base in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Ext.Base Var",
            "expression": " [YTD Ext.Base]-[PY YTD Ext.Base]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Ext.Base Var %",
            "expression": " DIVIDE([YTD Ext.Base]-[PY YTD Ext.Base],[PY YTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY MTD Ext.Base",
            "expression": "CALCULATE([Ext.Base in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Ext.Base Var",
            "expression": "[MTD Ext.Base]-[PY MTD ext.base]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Ext.Base Var %",
            "expression": "DIVIDE( [MTD Ext.Base]-[PY MTD Ext.Base],[PY MTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Ext.Base",
            "expression": "CALCULATE([Ext.Base in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Disc",
            "expression": " CALCULATE([Disc in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Disc Var",
            "expression": " [YTD Disc]-[PY YTD Disc]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4105\" DisplayName=\"$ English (Canada)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Disc Var %",
            "expression": " DIVIDE([YTD Disc]-[PY YTD Disc],[PY YTD Disc])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Disc",
            "expression": "CALCULATE([Disc in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Disc",
            "expression": "CALCULATE([Disc in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Disc Var",
            "expression": "[MTD Disc]-[PY MTD Disc]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Disc Var %",
            "expression": "DIVIDE( [MTD Disc]-[PY MTD Disc],[PY MTD Disc])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY YTD Disc%",
            "expression": " DIVIDE([PY YTD Disc],[PY YTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Disc%",
            "expression": " DIVIDE([MTD Disc],[MTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY MTD Disc%",
            "expression": " DIVIDE([PY MTD Disc],[PY MTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD Sales",
            "expression": "CALCULATE([Sales in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY QTD Sales",
            "expression": "CALCULATE([Sales in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-12 &&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Sales Var",
            "expression": "[QTD Sales]-[PY QTD Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Sales Var %",
            "expression": "DIVIDE( [QTD Sales]-[PY QTD Sales],[PY QTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD GP",
            "expression": "CALCULATE([GP in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY QTD GP",
            "expression": "CALCULATE([GP in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-12 &&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD GP Var",
            "expression": "[QTD GP]-[PY QTD GP] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD GP Var %",
            "expression": "DIVIDE( [QTD GP] - [PY QTD GP], [PY QTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD Ext.Base",
            "expression": "CALCULATE([Ext.Base in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY QTD Ext.Base",
            "expression": "CALCULATE([Ext.Base in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-12 &&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Ext.Base Var",
            "expression": "[QTD Ext.Base]-[PY QTD Ext.Base]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Ext.Base Var %",
            "expression": "DIVIDE( [QTD Ext.Base] - [PY QTD Ext.Base], [PY QTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD Disc",
            "expression": "CALCULATE([Disc in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY QTD Disc",
            "expression": "CALCULATE([Disc in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-12 &&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Disc Var",
            "expression": "[QTD Disc]-[PY QTD Disc] ",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Disc Var %",
            "expression": "DIVIDE( [QTD Disc] - [PY QTD Disc], [PY QTD Disc])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD Disc%",
            "expression": " DIVIDE([QTD Disc],[QTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY QTD Disc%",
            "expression": " DIVIDE([PY QTD Disc],[PY QTD Ext.Base])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD Disc% Improve",
            "expression": " [PY YTD Disc%] - [YTD Disc%] ",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD Disc% Improve",
            "expression": " [PY MTD Disc%] - [MTD Disc%] ",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD Disc% Improve",
            "expression": " [PY QTD Disc%] -  [QTD Disc%]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Lines in Period",
            "expression": "COUNTA([LineNumber])",
            "isHidden": true
          },
          {
            "name": "YTD Lines",
            "expression": " CALCULATE([Lines in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "MTD Lines",
            "expression": "CALCULATE([Lines in Period],filter(Period, Period[FiscalMonth]=[__first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY YTD Lines",
            "expression": " CALCULATE([Lines in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "#,0"
          },
          {
            "name": "YTD Lines Var",
            "expression": " [YTD Lines]-[PY YTD Lines]",
            "formatString": "#,0"
          },
          {
            "name": "YTD Lines Var %",
            "expression": " DIVIDE([YTD Lines]-[PY YTD Lines],[PY YTD Lines])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY MTD Lines",
            "expression": "CALCULATE([Lines in Period],filter(Period, Period[MonthSeq]=[__seq_first_month_current]-12))",
            "formatString": "#,0"
          },
          {
            "name": "MTD Lines Var",
            "expression": "[MTD Lines]-[PY MTD Lines]",
            "formatString": "#,0"
          },
          {
            "name": "MTD Lines Var %",
            "expression": "DIVIDE( [MTD Lines]-[PY MTD Lines],[PY MTD Lines])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Rolling 12mo Lines",
            "expression": [
              " ",
              "",
              "CALCULATE(",
              "",
              "        [Lines in Period],",
              "",
              "        filter(",
              "",
              "            ALL(Period),",
              " ",
              "           Period[MonthSeq]>([__seq_first_month_current]-12) &&",
              "",
              "           Period[MonthSeq]<=[__seq_first_month_current]",
              "",
              "        )",
              "",
              ")",
              "",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "QTD Lines",
            "expression": "CALCULATE([Lines in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY QTD Lines",
            "expression": "CALCULATE([Lines in Period],filter(all(Period), Period[MonthSeq]>=[__seq_first_month_in_quarter]-12 &&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "#,0"
          },
          {
            "name": "QTD Lines Var",
            "expression": "[QTD Lines]-[PY QTD Lines]",
            "formatString": "#,0"
          },
          {
            "name": "QTD Lines Var %",
            "expression": "DIVIDE( [QTD Lines]-[PY QTD Lines],[PY QTD Lines])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Quantity in Period",
            "expression": "SUM([Quantity])",
            "isHidden": true
          },
          {
            "name": "YTD Units",
            "expression": " CALCULATE([Quantity in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          },
          {
            "name": "PY YTD Units",
            "expression": " CALCULATE([Quantity in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "#,0"
          },
          {
            "name": "YTD Avg Sell",
            "expression": "DIVIDE([YTD Sales],[YTD Units])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Avg Sell",
            "expression": "DIVIDE([PY YTD Sales],[PY YTD Units])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Private Sales in Period",
            "expression": " CALCULATE ( [Sales in Period], 'Item'[Label] = \"P\")"
          },
          {
            "name": "YTD PL Sales",
            "expression": " CALCULATE([Private Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD PL Sales Share",
            "expression": "DIVIDE([YTD PL Sales], [YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY YTD PL Sales",
            "expression": " CALCULATE([Private Sales in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]-12&&Period[MonthSeq]<=[__seq_first_month_current]-12))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD PL Sales Share",
            "expression": "DIVIDE([PY YTD PL Sales], [PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD PL Sales Share Growth",
            "expression": "[YTD PL Sales Share] - [PY YTD PL Sales Share]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Orders in Period",
            "expression": "DISTINCTCOUNT([SalesOrderNumber])",
            "isHidden": true
          },
          {
            "name": "YTD Orders",
            "expression": " CALCULATE([Orders in Period],filter(ALL(Period), Period[MonthSeq]>=[__seq_first_month_in_year]&&Period[MonthSeq]<=[__seq_first_month_current]))",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "\tFactKey,",
              "\tBillTo,",
              "\tShipTo,",
              "\tItemKey,",
              "\tPriceMethodKey,",
              "\t[entered_by_key],",
              "\tMarketClassKey,",
              "\tCreditKey,",
              "\tFiscalMonth,",
              "\tDateKey,",
              "\tsales_order_key,",
              "\tSalesOrderNumber,",
              "\tLineNumber,",
              "\tFreeGoodsInvoicedInd,",
              "\tQuantity,",
              "\tSalesAmt,",
              "\tGPAmt,",
              "",
              "\tGPAtCommCostAmt,",
              "\tExtChargebackAmt,",
              "\tExtBaseAmt,",
              "\tDiscountAmt,",
              "\tDiscountLineAmt,",
              "\tDiscountOrderAmt",
              "FROM",
              "\tFact.Sale_qt",
              "WHERE ",
              "\tSalesCategory = 'MERCH' AND",
              "\tFreeGoodsInvoicedInd = 0"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sale_qt"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Fact"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "\tFactKey,",
              "\tBillTo,",
              "\tShipTo,",
              "\tItemKey,",
              "\tPriceMethodKey,",
              "\t[entered_by_key],",
              "\tMarketClassKey,",
              "\tCreditKey,",
              "\tFiscalMonth,",
              "\tDateKey,",
              "\tsales_order_key,",
              "\tSalesOrderNumber,",
              "\tLineNumber,",
              "\tFreeGoodsInvoicedInd,",
              "\tQuantity,",
              "\tSalesAmt,",
              "\tGPAmt,",
              "",
              "\tGPAtCommCostAmt,",
              "\tExtChargebackAmt,",
              "\tExtBaseAmt,",
              "\tDiscountAmt,",
              "\tDiscountLineAmt,",
              "\tDiscountOrderAmt",
              "FROM",
              "\tFact.Sale_qt",
              "WHERE ",
              "\tSalesCategory = 'MERCH' AND",
              "\tFreeGoodsInvoicedInd = 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Item",
        "columns": [
          {
            "name": "ItemKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ItemKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Item",
            "dataType": "string",
            "sourceColumn": "Item",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesCategory",
            "dataType": "string",
            "sourceColumn": "SalesCategory",
            "sourceProviderType": "Char"
          },
          {
            "name": "CategoryRollup",
            "dataType": "string",
            "sourceColumn": "CategoryRollup",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Top15",
            "dataType": "string",
            "sourceColumn": "Top15",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "Supplier",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ItemCode",
            "dataType": "string",
            "sourceColumn": "ItemCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label",
            "sourceProviderType": "Char"
          },
          {
            "name": "Major",
            "dataType": "string",
            "sourceColumn": "Major"
          },
          {
            "name": "StrengthInd",
            "dataType": "int64",
            "sourceColumn": "StrengthInd"
          },
          {
            "name": "ClassificationCode",
            "dataType": "string",
            "sourceColumn": "ClassificationCode"
          },
          {
            "name": "PrivateLabelScope_Item",
            "dataType": "string",
            "sourceColumn": "PrivateLabelScope_Item"
          },
          {
            "name": "SubMajor",
            "dataType": "string",
            "sourceColumn": "SubMajor"
          },
          {
            "name": "Minor",
            "dataType": "string",
            "sourceColumn": "Minor"
          },
          {
            "name": "CurrentFileCost",
            "dataType": "double",
            "sourceColumn": "CurrentFileCost",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CurrentCorporatePrice",
            "dataType": "double",
            "sourceColumn": "CurrentCorporatePrice",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Item",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT ",
                "\tItemKey,",
                "\tItem,",
                "\tSalesCategory,",
                "\tCategoryRollup,",
                "\tTop15,",
                "\tMajor,",
                "\tSubMajor,",
                "\tMinor,",
                "\tStrengthInd,",
                "\tSupplier,",
                "\tItemCode,",
                "\tLabel,",
                "\tClassificationCode,",
                "\tPrivateLabelScope_Item,",
                "\tCurrentFileCost,",
                "\t[CurrentCorporatePrice]",
                "",
                "",
                "FROM",
                "\tDimension.Item",
                "WHERE",
                "\tSalesCategoryCode = 'MERCH'"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
                  "\tItemKey,",
                  "\tItem,",
                  "\tSalesCategory,",
                  "\tCategoryRollup,",
                  "\tTop15,",
                  "\tMajor,",
                  "\tSubMajor,",
                  "\tMinor,",
                  "\tStrengthInd,",
                  "\tSupplier,",
                  "\tItemCode,",
                  "\tLabel,",
                  "\tClassificationCode,",
                  "\tPrivateLabelScope_Item,",
                  "\tCurrentFileCost,",
                  "\t[CurrentCorporatePrice]",
                  "",
                  "",
                  "FROM",
                  "\tDimension.Item",
                  "WHERE",
                  "\tSalesCategoryCode = 'MERCH'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Count of Item",
            "expression": "COUNTA([ItemKey])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT ",
              "\tItemKey,",
              "\tItem,",
              "\tSalesCategory,",
              "\tCategoryRollup,",
              "\tTop15,",
              "\tMajor,",
              "\tSubMajor,",
              "\tMinor,",
              "\tStrengthInd,",
              "\tSupplier,",
              "\tItemCode,",
              "\tLabel,",
              "\tClassificationCode,",
              "\tPrivateLabelScope_Item,",
              "\tCurrentFileCost,",
              "\t[CurrentCorporatePrice]",
              "",
              "",
              "FROM",
              "\tDimension.Item",
              "WHERE",
              "\tSalesCategoryCode = 'MERCH'"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Item"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
              "\tItemKey,",
              "\tItem,",
              "\tSalesCategory,",
              "\tCategoryRollup,",
              "\tTop15,",
              "\tMajor,",
              "\tSubMajor,",
              "\tMinor,",
              "\tStrengthInd,",
              "\tSupplier,",
              "\tItemCode,",
              "\tLabel,",
              "\tClassificationCode,",
              "\tPrivateLabelScope_Item,",
              "\tCurrentFileCost,",
              "\t[CurrentCorporatePrice]",
              "",
              "",
              "FROM",
              "\tDimension.Item",
              "WHERE",
              "\tSalesCategoryCode = 'MERCH'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Customer Billto",
        "columns": [
          {
            "name": "Billto",
            "dataType": "int64",
            "sourceColumn": "Billto",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ShipToPrimary",
            "dataType": "int64",
            "sourceColumn": "ShipToPrimary",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SalesPlan",
            "dataType": "string",
            "sourceColumn": "SalesPlan",
            "sourceProviderType": "Char"
          },
          {
            "name": "FieldSales",
            "dataType": "string",
            "sourceColumn": "FieldSales",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch",
            "sourceProviderType": "Char"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DateAccountOpened",
            "dataType": "dateTime",
            "sourceColumn": "DateAccountOpened",
            "formatString": "dd-MMM-yy",
            "sourceProviderType": "DBDate",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"dd-MMM-yy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "SalesDivisionCode",
            "dataType": "string",
            "sourceColumn": "SalesDivisionCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "Adjustment",
            "dataType": "string",
            "sourceColumn": "Adjustment"
          },
          {
            "name": "AdjEffectiveDate",
            "dataType": "dateTime",
            "sourceColumn": "AdjEffectiveDate",
            "formatString": "yyyy-MM-dd",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"yyyy-MM-dd\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NewPlanInd",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "if(Year([AdjEffectiveDate])>=[__current_year], 1, 0)"
          },
          {
            "type": "calculated",
            "name": "Quote Score",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "SWITCH(TRUE(), [Quote YTD Sales]<=5000, \"\", [Quote YTD GM]<.32 && [YTD Sales Var %]<.2, \"Red\", [Quote YTD GM]>=.32 && [YTD Sales Var %]>=.2, \"Green\", \"Yellow\")"
          },
          {
            "type": "calculated",
            "name": "Spend Level",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "CALCULATE ( ",
              "\tVALUES('SpendRange'[Spend Range]),",
              "\t\tFILTER( ",
              "            SpendRange, ",
              "            'Sales'[Rolling 12mo Sales] >= 'SpendRange'[Spend Min]  && ",
              "            'Sales'[Rolling 12mo Sales] < 'SpendRange'[Spend Max]",
              "\t\t)",
              ") "
            ]
          },
          {
            "name": "AdjUserId",
            "dataType": "string",
            "sourceColumn": "AdjUserId"
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "  Dimension.Customer_qt.Billto",
                "  ,Dimension.Customer_qt.ShipToPrimary",
                "  ,Dimension.Customer_qt.Customer",
                "  ,Dimension.Customer_qt.SalesPlan",
                "  ,Dimension.Customer_qt.FieldSales",
                "  ,Dimension.Customer_qt.Branch",
                "  ,Dimension.Customer_qt.City",
                "  ,Dimension.Customer_qt.DateAccountOpened",
                "  ,Dimension.Customer_qt.SalesDivisionCode",
                "  ,Dimension.Customer_qt.MarketClass",
                "  ,Dimension.Customer_qt.Adjustment",
                "  ,Dimension.Customer_qt.AdjEffectiveDate",
                "  ,Dimension.Customer_qt.AdjUserId",
                "FROM",
                "  Dimension.Customer_qt"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "  Dimension.Customer_qt.Billto",
                  "  ,Dimension.Customer_qt.ShipToPrimary",
                  "  ,Dimension.Customer_qt.Customer",
                  "  ,Dimension.Customer_qt.SalesPlan",
                  "  ,Dimension.Customer_qt.FieldSales",
                  "  ,Dimension.Customer_qt.Branch",
                  "  ,Dimension.Customer_qt.City",
                  "  ,Dimension.Customer_qt.DateAccountOpened",
                  "  ,Dimension.Customer_qt.SalesDivisionCode",
                  "  ,Dimension.Customer_qt.MarketClass",
                  "  ,Dimension.Customer_qt.Adjustment",
                  "  ,Dimension.Customer_qt.AdjEffectiveDate",
                  "  ,Dimension.Customer_qt.AdjUserId",
                  "FROM",
                  "  Dimension.Customer_qt</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Billto\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"ShipToPrimary\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Customer\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"SalesPlan\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"FieldSales\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Branch\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"City\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"DateAccountOpened\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"SalesDivisionCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"MarketClass\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Adjustment\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"AdjEffectiveDate\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"AdjUserId\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Count of Billto",
            "expression": "COUNTA([Billto])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "  Dimension.Customer_qt.Billto",
              "  ,Dimension.Customer_qt.ShipToPrimary",
              "  ,Dimension.Customer_qt.Customer",
              "  ,Dimension.Customer_qt.SalesPlan",
              "  ,Dimension.Customer_qt.FieldSales",
              "  ,Dimension.Customer_qt.Branch",
              "  ,Dimension.Customer_qt.City",
              "  ,Dimension.Customer_qt.DateAccountOpened",
              "  ,Dimension.Customer_qt.SalesDivisionCode",
              "  ,Dimension.Customer_qt.MarketClass",
              "  ,Dimension.Customer_qt.Adjustment",
              "  ,Dimension.Customer_qt.AdjEffectiveDate",
              "  ,Dimension.Customer_qt.AdjUserId",
              "FROM",
              "  Dimension.Customer_qt"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer_qt"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "  Dimension.Customer_qt.Billto",
              "  ,Dimension.Customer_qt.ShipToPrimary",
              "  ,Dimension.Customer_qt.Customer",
              "  ,Dimension.Customer_qt.SalesPlan",
              "  ,Dimension.Customer_qt.FieldSales",
              "  ,Dimension.Customer_qt.Branch",
              "  ,Dimension.Customer_qt.City",
              "  ,Dimension.Customer_qt.DateAccountOpened",
              "  ,Dimension.Customer_qt.SalesDivisionCode",
              "  ,Dimension.Customer_qt.MarketClass",
              "  ,Dimension.Customer_qt.Adjustment",
              "  ,Dimension.Customer_qt.AdjEffectiveDate",
              "  ,Dimension.Customer_qt.AdjUserId",
              "FROM",
              "  Dimension.Customer_qt</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState><DesignerState><UseGenericDesigner>false</UseGenericDesigner><InternalDesignerState><QueryDefinition xmlns=\"http://schemas.microsoft.com/ReportingServices/QueryDefinition/Relational\"><SelectedColumns><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Billto\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"ShipToPrimary\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Customer\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"SalesPlan\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"FieldSales\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Branch\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"City\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"DateAccountOpened\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"SalesDivisionCode\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"MarketClass\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"Adjustment\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"AdjEffectiveDate\" /><ColumnExpression Schema=\"Dimension\" ColumnOwner=\"Customer_qt\" ColumnName=\"AdjUserId\" /></SelectedColumns></QueryDefinition></InternalDesignerState></DesignerState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period Select",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "FiscalMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Period[FiscalMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "QuarterName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[QuarterName]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearNum",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[YearNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[WorkingDaysMonth]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthSeq",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[MonthSeq]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstMonthSeqInQtr]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Period[FirstMonthSeqInYear]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "Period"
            }
          }
        ],
        "measures": [
          {
            "name": "__first_month_current",
            "expression": " max('Period Select'[FiscalMonth])",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_current",
            "expression": " calculate(max('Period Select'[MonthSeq]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_year",
            "expression": " calculate(max('Period Select'[FirstMonthSeqInYear]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__seq_first_month_in_quarter",
            "expression": " calculate(max('Period Select'[FirstMonthSeqInQtr]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__first_month_number",
            "expression": " calculate(max('Period Select'[FiscalMonth]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          },
          {
            "name": "__ytd_factor",
            "expression": "12/[__first_month_number]",
            "isHidden": true
          },
          {
            "name": "__current_year",
            "expression": " calculate(max('Period Select'[YearNum]),filter('Period Select','Period Select'[FiscalMonth]=[__first_month_current]))",
            "isHidden": true
          }
        ]
      },
      {
        "name": "SpendRange",
        "isHidden": true,
        "columns": [
          {
            "name": "Spend Min",
            "dataType": "double",
            "sourceColumn": "Spend Min",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "Spend Max",
            "dataType": "double",
            "sourceColumn": "Spend Max",
            "sourceProviderType": "Decimal"
          },
          {
            "name": "Spend Range",
            "dataType": "string",
            "sourceColumn": "Spend Range",
            "sourceProviderType": "VarChar"
          }
        ],
        "partitions": [
          {
            "name": "SpendRange",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT ",
                "      [Spend_From]\t\tAS [Spend Min]",
                "      ,[Spend_To]\t\tAS [Spend Max]",
                "      ,[Spend_Display]  AS [Spend Range]",
                "  FROM [BRS_Customer_Spend_Category]"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
                  "      [Spend_From]\t\tAS [Spend Min]",
                  "      ,[Spend_To]\t\tAS [Spend Max]",
                  "      ,[Spend_Display]  AS [Spend Range]",
                  "  FROM [BRS_Customer_Spend_Category]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT ",
              "      [Spend_From]\t\tAS [Spend Min]",
              "      ,[Spend_To]\t\tAS [Spend Max]",
              "      ,[Spend_Display]  AS [Spend Range]",
              "  FROM [BRS_Customer_Spend_Category]"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "SpendRange"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT ",
              "      [Spend_From]\t\tAS [Spend Min]",
              "      ,[Spend_To]\t\tAS [Spend Max]",
              "      ,[Spend_Display]  AS [Spend Range]",
              "  FROM [BRS_Customer_Spend_Category]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "CSR",
        "columns": [
          {
            "name": "entered_by_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "entered_by_key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "csr",
            "dataType": "string",
            "sourceColumn": "csr"
          },
          {
            "name": "csr_branch",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "csr_branch"
          },
          {
            "name": "csr_role",
            "dataType": "string",
            "sourceColumn": "csr_role"
          }
        ],
        "partitions": [
          {
            "name": "entered_by",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\tc.entered_by_key",
                "\t,RTRIM(c.entered_by) + ' | ' +  RTRIM(c.entered_by_code) as csr",
                "\t,b.BranchName AS csr_branch",
                "\t,c.[role_code] AS csr_role",
                "FROM",
                "\tPricing.entered_by AS c ",
                "",
                "\tINNER JOIN BRS_Branch AS b ",
                "\tON c.branch_code = b.Branch"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "\tc.entered_by_key",
                  "\t,RTRIM(c.entered_by) + ' | ' +  RTRIM(c.entered_by_code) as csr",
                  "\t,b.BranchName AS csr_branch",
                  "\t,c.[role_code] AS csr_role",
                  "FROM",
                  "\tPricing.entered_by AS c ",
                  "",
                  "\tINNER JOIN BRS_Branch AS b ",
                  "\tON c.branch_code = b.Branch</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "\tc.entered_by_key",
              "\t,RTRIM(c.entered_by) + ' | ' +  RTRIM(c.entered_by_code) as csr",
              "\t,b.BranchName AS csr_branch",
              "\t,c.[role_code] AS csr_role",
              "FROM",
              "\tPricing.entered_by AS c ",
              "",
              "\tINNER JOIN BRS_Branch AS b ",
              "\tON c.branch_code = b.Branch"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "entered_by"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Pricing"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "\tc.entered_by_key",
              "\t,RTRIM(c.entered_by) + ' | ' +  RTRIM(c.entered_by_code) as csr",
              "\t,b.BranchName AS csr_branch",
              "\t,c.[role_code] AS csr_role",
              "FROM",
              "\tPricing.entered_by AS c ",
              "",
              "\tINNER JOIN BRS_Branch AS b ",
              "\tON c.branch_code = b.Branch</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "PriceMethod",
        "columns": [
          {
            "name": "PriceMethod",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PriceMethod",
            "sourceProviderType": "Char"
          },
          {
            "name": "PriceMethodDescr",
            "dataType": "string",
            "sourceColumn": "PriceMethodDescr",
            "sourceProviderType": "WChar"
          },
          {
            "name": "PriceMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PriceMethodKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_PriceMethod",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "SELECT [dbo].[BRS_PriceMethod].[PriceMethod],[dbo].[BRS_PriceMethod].[PriceMethodDescr],[dbo].[BRS_PriceMethod].[PriceMethodKey] FROM [dbo].[BRS_PriceMethod]",
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[BRS_PriceMethod].[PriceMethod],[dbo].[BRS_PriceMethod].[PriceMethodDescr],[dbo].[BRS_PriceMethod].[PriceMethodKey] FROM [dbo].[BRS_PriceMethod]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[BRS_PriceMethod].[PriceMethod],[dbo].[BRS_PriceMethod].[PriceMethodDescr],[dbo].[BRS_PriceMethod].[PriceMethodKey] FROM [dbo].[BRS_PriceMethod]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_PriceMethod"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[BRS_PriceMethod].[PriceMethod],[dbo].[BRS_PriceMethod].[PriceMethodDescr],[dbo].[BRS_PriceMethod].[PriceMethodKey] FROM [dbo].[BRS_PriceMethod]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Customer Shipto",
        "columns": [
          {
            "name": "ShipTo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShipTo",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "FieldSales",
            "dataType": "string",
            "sourceColumn": "FieldSales",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivision",
            "dataType": "string",
            "sourceColumn": "SalesDivision",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "CustomerStatus",
            "dataType": "string",
            "sourceColumn": "CustomerStatus",
            "sourceProviderType": "Char"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment"
          },
          {
            "name": "Specialty",
            "dataType": "string",
            "sourceColumn": "Specialty"
          },
          {
            "name": "DSO_TrackingShipTo",
            "dataType": "int64",
            "sourceColumn": "DSO_TrackingShipTo"
          },
          {
            "name": "DSO_TrackingCode",
            "dataType": "string",
            "sourceColumn": "DSO_TrackingCode"
          },
          {
            "name": "SalesPlan",
            "dataType": "string",
            "sourceColumn": "SalesPlan"
          },
          {
            "name": "CustomerGroup",
            "dataType": "string",
            "sourceColumn": "CustomerGroup"
          },
          {
            "name": "FocusCd",
            "dataType": "string",
            "sourceColumn": "FocusCd"
          },
          {
            "name": "CustomerParent",
            "dataType": "string",
            "sourceColumn": "CustomerParent"
          },
          {
            "name": "SalesplanFocusCode",
            "dataType": "string",
            "sourceColumn": "SalesplanFocusCode"
          },
          {
            "name": "PrivateLabelScope_Cust",
            "dataType": "string",
            "sourceColumn": "PrivateLabelScope_Cust"
          },
          {
            "name": "FocusSmCd",
            "dataType": "string",
            "sourceColumn": "FocusSmCd"
          }
        ],
        "partitions": [
          {
            "name": "Customer 1",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\tc.ShipTo",
                "\t,c.Customer",
                "\t,c.FieldSales",
                "\t,c.Branch",
                "\t,c.SalesDivision",
                "\t,c.MarketClass",
                "\t,c.CustomerStatus",
                "\t,c.Segment",
                "\t,c.Specialty",
                "",
                "\t,c.DCC_TrackingShipTo AS DSO_TrackingShipTo",
                "\t,c.DCC_TrackingCode AS DSO_TrackingCode",
                "\t,c.SalesPlan",
                "\t,c.SalesplanFocusCode",
                "\t,c.CustomerGroup",
                "\t,c.FocusCd",
                "\t,c.SmFocusCode FocusSmCd",
                "\t,iif(c.DCC_TrackingShipTo > 0, ",
                "\t\tt.PracticeName + ' | ' + RTRIM(CAST(t.ShipTo as char)),",
                "\t\t'')\t\t\t\tAS CustomerParent",
                "\t,PrivateLabelScope_Cust",
                "",
                "FROM",
                "\tDimension.Customer c",
                "\t",
                "\tINNER JOIN [dbo].[BRS_Customer] t",
                "\tON c.DSO_ParentShipTo = t.ShipTo"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "\tc.ShipTo",
                  "\t,c.Customer",
                  "\t,c.FieldSales",
                  "\t,c.Branch",
                  "\t,c.SalesDivision",
                  "\t,c.MarketClass",
                  "\t,c.CustomerStatus",
                  "\t,c.Segment",
                  "\t,c.Specialty",
                  "",
                  "\t,c.DCC_TrackingShipTo AS DSO_TrackingShipTo",
                  "\t,c.DCC_TrackingCode AS DSO_TrackingCode",
                  "\t,c.SalesPlan",
                  "\t,c.SalesplanFocusCode",
                  "\t,c.CustomerGroup",
                  "\t,c.FocusCd",
                  "\t,c.SmFocusCode FocusSmCd",
                  "\t,iif(c.DCC_TrackingShipTo > 0, ",
                  "\t\tt.PracticeName + ' | ' + RTRIM(CAST(t.ShipTo as char)),",
                  "\t\t'')\t\t\t\tAS CustomerParent",
                  "\t,PrivateLabelScope_Cust",
                  "",
                  "FROM",
                  "\tDimension.Customer c",
                  "\t",
                  "\tINNER JOIN [dbo].[BRS_Customer] t",
                  "\tON c.DSO_ParentShipTo = t.ShipTo</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Count of ShipTo",
            "expression": "COUNTA([ShipTo])",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "\tc.ShipTo",
              "\t,c.Customer",
              "\t,c.FieldSales",
              "\t,c.Branch",
              "\t,c.SalesDivision",
              "\t,c.MarketClass",
              "\t,c.CustomerStatus",
              "\t,c.Segment",
              "\t,c.Specialty",
              "",
              "\t,c.DCC_TrackingShipTo AS DSO_TrackingShipTo",
              "\t,c.DCC_TrackingCode AS DSO_TrackingCode",
              "\t,c.SalesPlan",
              "\t,c.SalesplanFocusCode",
              "\t,c.CustomerGroup",
              "\t,c.FocusCd",
              "\t,c.SmFocusCode FocusSmCd",
              "\t,iif(c.DCC_TrackingShipTo > 0, ",
              "\t\tt.PracticeName + ' | ' + RTRIM(CAST(t.ShipTo as char)),",
              "\t\t'')\t\t\t\tAS CustomerParent",
              "\t,PrivateLabelScope_Cust",
              "",
              "FROM",
              "\tDimension.Customer c",
              "\t",
              "\tINNER JOIN [dbo].[BRS_Customer] t",
              "\tON c.DSO_ParentShipTo = t.ShipTo"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "\tc.ShipTo",
              "\t,c.Customer",
              "\t,c.FieldSales",
              "\t,c.Branch",
              "\t,c.SalesDivision",
              "\t,c.MarketClass",
              "\t,c.CustomerStatus",
              "\t,c.Segment",
              "\t,c.Specialty",
              "",
              "\t,c.DCC_TrackingShipTo AS DSO_TrackingShipTo",
              "\t,c.DCC_TrackingCode AS DSO_TrackingCode",
              "\t,c.SalesPlan",
              "\t,c.SalesplanFocusCode",
              "\t,c.CustomerGroup",
              "\t,c.FocusCd",
              "\t,c.SmFocusCode FocusSmCd",
              "\t,iif(c.DCC_TrackingShipTo > 0, ",
              "\t\tt.PracticeName + ' | ' + RTRIM(CAST(t.ShipTo as char)),",
              "\t\t'')\t\t\t\tAS CustomerParent",
              "\t,PrivateLabelScope_Cust",
              "",
              "FROM",
              "\tDimension.Customer c",
              "\t",
              "\tINNER JOIN [dbo].[BRS_Customer] t",
              "\tON c.DSO_ParentShipTo = t.ShipTo</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Salesorder",
        "columns": [
          {
            "name": "SalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "Integer"
          },
          {
            "name": "sales_order_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sales_order_key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "PriceMethod",
            "dataType": "string",
            "sourceColumn": "PriceMethod",
            "sourceProviderType": "WChar"
          },
          {
            "name": "PriceMethodRollup",
            "dataType": "string",
            "sourceColumn": "PriceMethodRollup",
            "sourceProviderType": "WChar"
          },
          {
            "name": "OrderSource",
            "dataType": "string",
            "sourceColumn": "OrderSource",
            "sourceProviderType": "Char"
          },
          {
            "name": "PromotionType",
            "dataType": "string",
            "sourceColumn": "PromotionType",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Promotion",
            "dataType": "string",
            "sourceColumn": "Promotion",
            "sourceProviderType": "WChar"
          },
          {
            "name": "PromotionConvention",
            "dataType": "string",
            "sourceColumn": "PromotionConvention",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DocType",
            "dataType": "string",
            "sourceColumn": "DocType",
            "sourceProviderType": "Char"
          },
          {
            "name": "ReturnValidInd",
            "dataType": "boolean",
            "sourceColumn": "ReturnValidInd",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "name": "ReturnMonths",
            "dataType": "int64",
            "sourceColumn": "ReturnMonths"
          },
          {
            "name": "OriginalSalesOrderNumber",
            "dataType": "int64",
            "sourceColumn": "OriginalSalesOrderNumber"
          },
          {
            "name": "ReturnRange",
            "dataType": "string",
            "sourceColumn": "ReturnRange"
          },
          {
            "name": "PriceMethodCode",
            "dataType": "string",
            "sourceColumn": "PriceMethodCode"
          },
          {
            "name": "PriceMethodRollupCode",
            "dataType": "string",
            "sourceColumn": "PriceMethodRollupCode"
          },
          {
            "type": "calculated",
            "name": "OrderSize",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": "[Sales in Period]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "CreditBand",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "CALCULATE(",
              "     VALUES(CreditBand[Band]),",
              "     FILTER(CreditBand,",
              "            Salesorder[OrderSize] < CreditBand[Spend_From] &&",
              "                Salesorder[OrderSize] >= CreditBand[Spend_To]",
              "     )",
              "   )"
            ],
            "sortByColumn": "CreditBandSort"
          },
          {
            "type": "calculated",
            "name": "CreditBandSort",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "CALCULATE(",
              "     VALUES(CreditBand[SpendKey]),",
              "     FILTER(CreditBand,",
              "            Salesorder[OrderSize] < CreditBand[Spend_From] &&",
              "                Salesorder[OrderSize] >= CreditBand[Spend_To]",
              "     )",
              "   )"
            ]
          }
        ],
        "partitions": [
          {
            "name": "Salesorder",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\tSalesOrderNumber,",
                "\tsales_order_key,",
                "\tReturnValidInd,",
                "\tReturnMonths,",
                "\tReturnRange,",
                "\tOriginalSalesOrderNumber,",
                "\tPriceMethod,",
                "\tPriceMethodRollup,",
                "\tOrderSource,",
                "\tPromotionType,",
                "\tPromotion,",
                "\tPromotionConvention,",
                "\tDocType,",
                "\tPriceMethodCode,",
                "\tPriceMethodRollupCode",
                "FROM",
                "\tDimension.Salesorder_qt"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "\tSalesOrderNumber,",
                  "\tsales_order_key,",
                  "\tReturnValidInd,",
                  "\tReturnMonths,",
                  "\tReturnRange,",
                  "\tOriginalSalesOrderNumber,",
                  "\tPriceMethod,",
                  "\tPriceMethodRollup,",
                  "\tOrderSource,",
                  "\tPromotionType,",
                  "\tPromotion,",
                  "\tPromotionConvention,",
                  "\tDocType,",
                  "\tPriceMethodCode,",
                  "\tPriceMethodRollupCode",
                  "FROM",
                  "\tDimension.Salesorder_qt</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "\tSalesOrderNumber,",
              "\tsales_order_key,",
              "\tReturnValidInd,",
              "\tReturnMonths,",
              "\tReturnRange,",
              "\tOriginalSalesOrderNumber,",
              "\tPriceMethod,",
              "\tPriceMethodRollup,",
              "\tOrderSource,",
              "\tPromotionType,",
              "\tPromotion,",
              "\tPromotionConvention,",
              "\tDocType,",
              "\tPriceMethodCode,",
              "\tPriceMethodRollupCode",
              "FROM",
              "\tDimension.Salesorder_qt"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Salesorder_qt"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "\tSalesOrderNumber,",
              "\tsales_order_key,",
              "\tReturnValidInd,",
              "\tReturnMonths,",
              "\tReturnRange,",
              "\tOriginalSalesOrderNumber,",
              "\tPriceMethod,",
              "\tPriceMethodRollup,",
              "\tOrderSource,",
              "\tPromotionType,",
              "\tPromotion,",
              "\tPromotionConvention,",
              "\tDocType,",
              "\tPriceMethodCode,",
              "\tPriceMethodRollupCode",
              "FROM",
              "\tDimension.Salesorder_qt</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "MarketClass",
        "columns": [
          {
            "name": "MarketClassCode",
            "dataType": "string",
            "sourceColumn": "MarketClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClassDesc",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClassParent",
            "dataType": "string",
            "sourceColumn": "MarketRollup_L1",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClassKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MarketClassKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_CustomerMarketClass",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_CustomerMarketClass].[MarketClass],[dbo].[BRS_CustomerMarketClass].[MarketClassDesc],[dbo].[BRS_CustomerMarketClass].[MarketRollup_L1],[dbo].[BRS_CustomerMarketClass].[MarketClassKey] FROM [dbo].[BRS_CustomerMarketClass] ",
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClass</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>121</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClassDesc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>111</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>69</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClassKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>106</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClass</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClassDesc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L1</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L2</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L3</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClassKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClass</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClassDesc</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L1</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L2</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketRollup_L3</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClassKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_CustomerMarketClass].[MarketClass],[dbo].[BRS_CustomerMarketClass].[MarketClassDesc],[dbo].[BRS_CustomerMarketClass].[MarketRollup_L1],[dbo].[BRS_CustomerMarketClass].[MarketClassKey] FROM [dbo].[BRS_CustomerMarketClass] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_CustomerMarketClass"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>MarketClass</string>",
              "      </key>",
              "      <value>",
              "        <int>121</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketClassDesc</string>",
              "      </key>",
              "      <value>",
              "        <int>111</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <int>69</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L1</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L2</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L3</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketClassKey</string>",
              "      </key>",
              "      <value>",
              "        <int>106</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>MarketClass</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketClassDesc</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L1</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L2</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L3</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketClassKey</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>MarketClass</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketClassDesc</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L1</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L2</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketRollup_L3</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketClassKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Creditinfo",
        "columns": [
          {
            "name": "CreditMinorReason",
            "dataType": "string",
            "sourceColumn": "CreditMinorReason",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CreditType",
            "dataType": "string",
            "sourceColumn": "CreditType",
            "sourceProviderType": "WChar"
          },
          {
            "name": "credit_key",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "sourceColumn": "credit_key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Creditinfo",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT",
                "\tcredit_key,",
                "\tRTRIM(CreditMinorReasonCode) + ' | ' + RTRIM(CreditMinorReason) as CreditMinorReason,",
                "\tRTRIM(CreditTypeCode) + ' | ' + RTRIM(CreditType) as CreditType",
                "FROM",
                "\tBRS_Creditinfo"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
                  "\tcredit_key,",
                  "\tRTRIM(CreditMinorReasonCode) + ' | ' + RTRIM(CreditMinorReason) as CreditMinorReason,",
                  "\tRTRIM(CreditTypeCode) + ' | ' + RTRIM(CreditType) as CreditType",
                  "FROM",
                  "\tBRS_Creditinfo</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT",
              "\tcredit_key,",
              "\tRTRIM(CreditMinorReasonCode) + ' | ' + RTRIM(CreditMinorReason) as CreditMinorReason,",
              "\tRTRIM(CreditTypeCode) + ' | ' + RTRIM(CreditType) as CreditType",
              "FROM",
              "\tBRS_Creditinfo"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_Creditinfo"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT",
              "\tcredit_key,",
              "\tRTRIM(CreditMinorReasonCode) + ' | ' + RTRIM(CreditMinorReason) as CreditMinorReason,",
              "\tRTRIM(CreditTypeCode) + ' | ' + RTRIM(CreditType) as CreditType",
              "FROM",
              "\tBRS_Creditinfo</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "CreditBand",
        "columns": [
          {
            "name": "Spend_From",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Spend_From",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Spend_To",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Spend_To",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Band",
            "dataType": "string",
            "sourceColumn": "Spend_Display",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Spend_Rank",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Spend_Rank",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "SpendKey",
            "dataType": "int64",
            "isUnique": true,
            "sourceColumn": "SpendKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "CreditBand",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_Customer_Spend_Category].[Spend_From],[dbo].[BRS_Customer_Spend_Category].[Spend_To],[dbo].[BRS_Customer_Spend_Category].[Spend_Display],[dbo].[BRS_Customer_Spend_Category].[Spend_Rank],[dbo].[BRS_Customer_Spend_Category].[SpendKey] FROM [dbo].[BRS_Customer_Spend_Category]  WHERE (NOT(([Spend_Category] = N' ')) OR [Spend_Category] IS NULL) ",
              "dataSource": "SqlServer CAHSIONNLSQL1BRSales"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivision</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_From</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_To</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Display</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>100</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Rank</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Discount_Rate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>136</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Category</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>111</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SpendKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivision</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_From</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_To</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Display</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Rank</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Discount_Rate</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Category</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SpendKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivision</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Discount_Rate</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Category</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Category</string>",
                  "      </key>",
                  "      <value>",
                  "        <FilterExpression xsi:nil=\"true\" />",
                  "      </value>",
                  "    </item>",
                  "  </ColumnFilter>",
                  "  <SelectionFilter>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Category</string>",
                  "      </key>",
                  "      <value>",
                  "        <SelectionFilter>",
                  "          <SelectionType>Deselect</SelectionType>",
                  "          <Items>",
                  "            <anyType xsi:type=\"xsd:string\"> </anyType>",
                  "          </Items>",
                  "        </SelectionFilter>",
                  "      </value>",
                  "    </item>",
                  "  </SelectionFilter>",
                  "  <FilterParameters>",
                  "    <item>",
                  "      <key>",
                  "        <string>Spend_Category</string>",
                  "      </key>",
                  "      <value>",
                  "        <CommandParameters />",
                  "      </value>",
                  "    </item>",
                  "  </FilterParameters>",
                  "  <SortByColumn>Spend_Rank</SortByColumn>",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_Customer_Spend_Category].[Spend_From],[dbo].[BRS_Customer_Spend_Category].[Spend_To],[dbo].[BRS_Customer_Spend_Category].[Spend_Display],[dbo].[BRS_Customer_Spend_Category].[Spend_Rank],[dbo].[BRS_Customer_Spend_Category].[SpendKey] FROM [dbo].[BRS_Customer_Spend_Category]  WHERE (NOT(([Spend_Category] = N' ')) OR [Spend_Category] IS NULL) "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_Customer_Spend_Category"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivision</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_From</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_To</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Display</string>",
              "      </key>",
              "      <value>",
              "        <int>100</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Rank</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Discount_Rate</string>",
              "      </key>",
              "      <value>",
              "        <int>136</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Category</string>",
              "      </key>",
              "      <value>",
              "        <int>111</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SpendKey</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivision</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_From</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_To</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Display</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Rank</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Discount_Rate</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Category</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SpendKey</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivision</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Discount_Rate</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Category</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Category</string>",
              "      </key>",
              "      <value>",
              "        <FilterExpression xsi:nil=\"true\" />",
              "      </value>",
              "    </item>",
              "  </ColumnFilter>",
              "  <SelectionFilter>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Category</string>",
              "      </key>",
              "      <value>",
              "        <SelectionFilter>",
              "          <SelectionType>Deselect</SelectionType>",
              "          <Items>",
              "            <anyType xsi:type=\"xsd:string\"> </anyType>",
              "          </Items>",
              "        </SelectionFilter>",
              "      </value>",
              "    </item>",
              "  </SelectionFilter>",
              "  <FilterParameters>",
              "    <item>",
              "      <key>",
              "        <string>Spend_Category</string>",
              "      </key>",
              "      <value>",
              "        <CommandParameters />",
              "      </value>",
              "    </item>",
              "  </FilterParameters>",
              "  <SortByColumn>Spend_Rank</SortByColumn>",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a8e62166-6ac7-4dc0-ba4c-dd291fbd6a18",
        "fromTable": "Sales",
        "fromColumn": "ItemKey",
        "toTable": "Item",
        "toColumn": "ItemKey"
      },
      {
        "name": "e3687906-1ce1-4f47-8a0f-8137092a358a",
        "fromTable": "Sales",
        "fromColumn": "FiscalMonth",
        "toTable": "Period",
        "toColumn": "FiscalMonth"
      },
      {
        "name": "981f08d8-1fed-485a-84e6-7a9dcd87f4e1",
        "fromTable": "Sales",
        "fromColumn": "BillTo",
        "toTable": "Customer Billto",
        "toColumn": "Billto"
      },
      {
        "name": "45390581-ebd8-4864-a96c-28b8d2d27930",
        "fromTable": "Sales",
        "fromColumn": "entered_by_key",
        "toTable": "CSR",
        "toColumn": "entered_by_key"
      },
      {
        "name": "e5c61263-3720-4e46-b257-bf0f2b9f3064",
        "fromTable": "Sales",
        "fromColumn": "PriceMethodKey",
        "toTable": "PriceMethod",
        "toColumn": "PriceMethodKey"
      },
      {
        "name": "a0b21940-7bb1-4c92-92e8-5a95305588e0",
        "fromTable": "Sales",
        "fromColumn": "ShipTo",
        "toTable": "Customer Shipto",
        "toColumn": "ShipTo"
      },
      {
        "name": "affe5c20-e601-42aa-ba0e-042fd79b3ee4",
        "fromTable": "Sales",
        "fromColumn": "sales_order_key",
        "toTable": "Salesorder",
        "toColumn": "sales_order_key"
      },
      {
        "name": "0a97ff4e-e1ed-4e06-9610-f79e20a8b865",
        "fromTable": "Sales",
        "fromColumn": "MarketClassKey",
        "toTable": "MarketClass",
        "toColumn": "MarketClassKey"
      },
      {
        "name": "65d78d2a-604c-4047-8a71-ad5844bb8476",
        "fromTable": "Sales",
        "fromColumn": "CreditKey",
        "toTable": "Creditinfo",
        "toColumn": "credit_key"
      }
    ],
    "roles": [
      {
        "name": "user",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "CAHSI\\tcrowley",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1815"
          },
          {
            "memberName": "CAHSI\\Gary.Winslow",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1322"
          },
          {
            "memberName": "CAHSI\\GWatson",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-5503"
          },
          {
            "memberName": "CAHSI\\Marco.Calabrese",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11954"
          },
          {
            "memberName": "CAHSI\\Randeep.Bhela",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-10655"
          },
          {
            "memberName": "CAHSI\\JLi",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-2414"
          },
          {
            "memberName": "CAHSI\\Jodee.Webb",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11457"
          },
          {
            "memberName": "CAHSI\\Nia.Othitis",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-5731"
          },
          {
            "memberName": "CAHSI\\Kishore.Pranjivan",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-11564"
          },
          {
            "memberName": "CAHSI\\Jason.Brown",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-8508"
          },
          {
            "memberName": "CAHSI\\Tina.Duczmal",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1522"
          },
          {
            "memberName": "CAHSI\\LMayhew",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1208"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}