{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "SqlServer CAHSIONNLSQL1 BRSales",
        "connectionString": "Provider=SQLNCLI11;Data Source=CAHSIONNLSQL1;Initial Catalog=DEV_BRSales;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "CAHSI\\tcrowley",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "BRS_DS_Day",
        "columns": [
          {
            "name": "SalesDate",
            "dataType": "dateTime",
            "sourceColumn": "SalesDate",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "DayNumber",
            "dataType": "int64",
            "sourceColumn": "DayNumber",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "DaySeq",
            "dataType": "int64",
            "sourceColumn": "DaySeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "DayType",
            "dataType": "string",
            "sourceColumn": "DayType",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DS_Day",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT   SalesDate, DayNumber, DaySeq, DayType",
                "FROM     BRS_DS_Day"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT   SalesDate, DayNumber, DaySeq, DayType",
                  "FROM     BRS_DS_Day</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT   SalesDate, DayNumber, DaySeq, DayType",
              "FROM     BRS_DS_Day"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DS_Day"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT   SalesDate, DayNumber, DaySeq, DayType",
              "FROM     BRS_DS_Day</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "BRS_DS_Market_Rollup",
        "columns": [
          {
            "name": "MarketClass",
            "dataType": "string",
            "sourceColumn": "MarketClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClassDesc",
            "dataType": "string",
            "sourceColumn": "MarketClassDesc",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketRollup_L1",
            "dataType": "string",
            "sourceColumn": "MarketRollup_L1",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketRollup_L2",
            "dataType": "string",
            "sourceColumn": "MarketRollup_L2"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DS_Market_Rollup",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT MarketClass, MarketClassDesc, MarketRollup_L1, MarketRollup_L2",
                "FROM dbo.BRS_CustomerMarketClass",
                "WHERE (StatusCd <> 0)"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT MarketClass, MarketClassDesc, MarketRollup_L1, MarketRollup_L2",
                  "FROM dbo.BRS_CustomerMarketClass",
                  "WHERE (StatusCd <> 0)</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT MarketClass, MarketClassDesc, MarketRollup_L1, MarketRollup_L2",
              "FROM dbo.BRS_CustomerMarketClass",
              "WHERE (StatusCd <> 0)"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DS_Market_Rollup"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT MarketClass, MarketClassDesc, MarketRollup_L1, MarketRollup_L2",
              "FROM dbo.BRS_CustomerMarketClass",
              "WHERE (StatusCd <> 0)</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "BRS_DS_Period",
        "columns": [
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "sourceColumn": "MonthNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "QuarterNum",
            "dataType": "int64",
            "sourceColumn": "QuarterNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "YearNum",
            "dataType": "int64",
            "sourceColumn": "YearNum",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "WorkingDaysMonth",
            "dataType": "int64",
            "sourceColumn": "WorkingDaysMonth",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MonthSeq",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthSeq",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInQtr",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInQtr",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "FirstMonthSeqInYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FirstMonthSeqInYear",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "LastWorkingDt",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastWorkingDt",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DS_Period",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_DS_Period].* FROM [dbo].[BRS_DS_Period] ",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            }
          }
        ],
        "measures": [
          {
            "name": "Working Days",
            "expression": "sum([WorkingDaysMonth])",
            "formatString": "#,0"
          },
          {
            "name": "Total Working Days in Month",
            "expression": "CALCULATE([Working Days],FILTER(ALL(BRS_DS_Period),[MonthSeq]=LOOKUPVALUE([MonthSeq],[FiscalMonth],max(BRS_DS_Config[FiscalMonth]))))",
            "formatString": "#,0"
          },
          {
            "name": "Total Working Days in Quarter",
            "expression": "CALCULATE([Working Days],FILTER(ALL(BRS_DS_Period),[FirstMonthSeqInQtr]=LOOKUPVALUE([FirstMonthSeqInQtr],[FiscalMonth],max(BRS_DS_Config[FiscalMonth]))))",
            "formatString": "#,0"
          },
          {
            "name": "Total Working Days in Year",
            "expression": "CALCULATE([Working Days],FILTER(ALL(BRS_DS_Period),[FirstMonthSeqInYear]=LOOKUPVALUE([FirstMonthSeqInYear],[FiscalMonth],max(BRS_DS_Config[FiscalMonth]))))",
            "formatString": "#,0"
          },
          {
            "name": "Working Days in Quarter",
            "expression": "CALCULATE([Working Days],FILTER(ALL(BRS_DS_Period),[FirstMonthSeqInQtr]=LOOKUPVALUE([FirstMonthSeqInQtr],[FiscalMonth],max(BRS_DS_Config[FiscalMonth])) && [FiscalMonth] <= MAX(BRS_DS_Config[PriorFiscalMonth]) ))",
            "formatString": "#,0"
          },
          {
            "name": "Working Days in Year",
            "expression": "CALCULATE([Working Days],FILTER(ALL(BRS_DS_Period),[FiscalMonth] >= MAX(BRS_DS_Config[YearFirstFiscalMonth]) && [FiscalMonth] <= MAX(BRS_DS_Config[PriorFiscalMonth])))",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_DS_Period].* FROM [dbo].[BRS_DS_Period] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DS_Period"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "BRS_DS_Cube",
        "columns": [
          {
            "name": "TimePeriod",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TimePeriod",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "DAY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DAY",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "MTD",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MTD",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "QTD",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "QTD",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "YTD",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "YTD",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Branch",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "GLBU_Class",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GLBU_Class",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "AdjCode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "AdjCode",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "SalesDivision",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalesDivision",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "TrxSrc",
            "dataType": "string",
            "sourceColumn": "TrxSrc",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "MarketClass",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MarketClass",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "SegCd",
            "dataType": "string",
            "sourceColumn": "SegCd",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "CategoryRollupPPE",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CategoryRollupPPE",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "sourceProviderType": "VarChar"
          },
          {
            "name": "SalesAmt",
            "dataType": "double",
            "sourceColumn": "SalesAmt",
            "sourceProviderType": "Double"
          },
          {
            "name": "GPAmt",
            "dataType": "double",
            "sourceColumn": "GPAmt",
            "sourceProviderType": "Double"
          },
          {
            "name": "SalesDate",
            "dataType": "dateTime",
            "sourceColumn": "SalesDate",
            "formatString": "General Date",
            "sourceProviderType": "Date"
          },
          {
            "name": "UniqueID",
            "dataType": "int64",
            "sourceColumn": "UniqueID",
            "sourceProviderType": "Integer"
          },
          {
            "type": "calculated",
            "name": "SalesDivisionAdj",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "if([GLBU_Class]=\"TEETH\",\"AAL\",[SalesDivision])"
          },
          {
            "name": "ppe_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ppe_key"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DS_Cube",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "Exec BRS_DS_Cube_proc 0",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>Exec BRS_DS_Cube_proc 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Total Sales",
            "expression": "sum([SalesAmt])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "DAY Sales",
            "expression": "CALCULATE([Total Sales],BRS_DS_Cube[DAY]=\"DAY\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales",
            "expression": "CALCULATE([Total Sales],BRS_DS_Cube[MTD]=\"MTD\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Sales",
            "expression": "CALCULATE([Total Sales],BRS_DS_Cube[QTD]=\"QTD\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales",
            "expression": "CALCULATE([Total Sales],BRS_DS_Cube[YTD]=\"YTD\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total GP",
            "expression": "sum([GPAmt])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "DAY GP",
            "expression": "CALCULATE([Total GP],BRS_DS_Cube[DAY]=\"DAY\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP",
            "expression": "CALCULATE([Total GP],BRS_DS_Cube[MTD]=\"MTD\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD GP",
            "expression": "CALCULATE([Total GP],BRS_DS_Cube[QTD]=\"QTD\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP",
            "expression": "CALCULATE([Total GP],BRS_DS_Cube[YTD]=\"YTD\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CY DAY Sales",
            "expression": " CALCULATE([Total Sales],FILTER('BRS_DS_Cube', BRS_DS_Cube[DAY]=\"DAY\" && BRS_DS_Cube[TimePeriod]=\"CY\"))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4096\" DisplayName=\"$ English (US Minor Outlying Islands)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY DAY Sales",
            "expression": " CALCULATE([Total Sales],FILTER('BRS_DS_Cube',BRS_DS_Cube[DAY]=\"DAY\" && BRS_DS_Cube[TimePeriod]=\"PY\"))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4096\" DisplayName=\"$ English (US Minor Outlying Islands)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DAY Sales Var",
            "expression": " [CY DAY Sales]-[PY DAY Sales]",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4096\" DisplayName=\"$ English (US Minor Outlying Islands)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DAY Sales Var%",
            "expression": " DIVIDE([DAY Sales Var], [PY DAY Sales] )",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY DAY GP",
            "expression": " CALCULATE([Total GP],FILTER('BRS_DS_Cube', BRS_DS_Cube[DAY]=\"DAY\" && BRS_DS_Cube[TimePeriod]=\"CY\"))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4096\" DisplayName=\"$ English (US Minor Outlying Islands)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "PY DAY GP",
            "expression": " CALCULATE([Total GP], FILTER('BRS_DS_Cube', BRS_DS_Cube[DAY]=\"DAY\" && BRS_DS_Cube[TimePeriod]=\"PY\"))",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4096\" DisplayName=\"$ English (US Minor Outlying Islands)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DAY GP Var",
            "expression": " ([CY DAY GP]-[PY DAY GP])",
            "formatString": "\\$#,0;-\\$#,0;\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"4096\" DisplayName=\"$ English (US Minor Outlying Islands)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "DAY GP Var%",
            "expression": " DIVIDE([DAY GP Var], [PY DAY GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY DAY GM",
            "expression": " DIVIDE([CY DAY GP], [CY DAY Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY DAY GM",
            "expression": " DIVIDE([PY DAY GP], [PY DAY Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "DAY GM Var",
            "expression": " ([CY DAY GM]-[PY DAY GM])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY MTD Sales",
            "expression": " CALCULATE([Total Sales], FILTER('BRS_DS_Cube', BRS_DS_Cube[MTD]=\"MTD\" && BRS_DS_Cube[TimePeriod]=\"CY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD Sales",
            "expression": " CALCULATE([Total Sales],FILTER('BRS_DS_Cube',  BRS_DS_Cube[MTD]=\"MTD\" && BRS_DS_Cube[TimePeriod]=\"PY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Var",
            "expression": " [CY MTD Sales]-[PY MTD Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Sales Var%",
            "expression": " DIVIDE([MTD Sales Var], [PY MTD Sales] )",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY MTD GP",
            "expression": " CALCULATE([Total GP], FILTER('BRS_DS_Cube', BRS_DS_Cube[MTD]=\"MTD\" && BRS_DS_Cube[TimePeriod]=\"CY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY MTD GP",
            "expression": " CALCULATE([Total GP], FILTER('BRS_DS_Cube', BRS_DS_Cube[MTD]=\"MTD\" && BRS_DS_Cube[TimePeriod]=\"PY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Var",
            "expression": " ([CY MTD GP]-[PY MTD GP])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD GP Var%",
            "expression": " DIVIDE([MTD GP Var], [PY MTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY MTD GM",
            "expression": " DIVIDE([CY MTD GP], [CY MTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY MTD GM",
            "expression": " DIVIDE([PY MTD GP], [PY MTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "MTD GM Var",
            "expression": " ([CY MTD GM]-[PY MTD GM])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY QTD Sales",
            "expression": " CALCULATE([Total Sales],FILTER('BRS_DS_Cube',  BRS_DS_Cube[QTD]=\"QTD\" && BRS_DS_Cube[TimePeriod]=\"CY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY QTD Sales",
            "expression": " CALCULATE([Total Sales], FILTER('BRS_DS_Cube', BRS_DS_Cube[QTD]=\"QTD\" && BRS_DS_Cube[TimePeriod]=\"PY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Sales Var",
            "expression": " [CY QTD Sales]-[PY QTD Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD Sales Var%",
            "expression": " DIVIDE([QTD Sales Var], [PY QTD Sales] )",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY QTD GP",
            "expression": " CALCULATE([Total GP],FILTER('BRS_DS_Cube',  BRS_DS_Cube[QTD]=\"QTD\" && BRS_DS_Cube[TimePeriod]=\"CY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY QTD GP",
            "expression": " CALCULATE([Total GP], FILTER('BRS_DS_Cube', BRS_DS_Cube[QTD]=\"QTD\" && BRS_DS_Cube[TimePeriod]=\"PY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD GP Var",
            "expression": " ([CY QTD GP]-[PY QTD GP])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QTD GP Var%",
            "expression": " DIVIDE([QTD GP Var], [PY QTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY QTD GM",
            "expression": " DIVIDE([CY QTD GP], [CY QTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY QTD GM",
            "expression": " DIVIDE([PY QTD GP], [PY QTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "QTD GM Var",
            "expression": " ([CY QTD GM]-[PY QTD GM])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY YTD Sales",
            "expression": " CALCULATE([Total Sales], FILTER('BRS_DS_Cube', BRS_DS_Cube[YTD]=\"YTD\" && BRS_DS_Cube[TimePeriod]=\"CY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD Sales",
            "expression": " CALCULATE([Total Sales], FILTER('BRS_DS_Cube', BRS_DS_Cube[YTD]=\"YTD\" && BRS_DS_Cube[TimePeriod]=\"PY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Var",
            "expression": " [CY YTD Sales]-[PY YTD Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD Sales Var%",
            "expression": " DIVIDE([YTD Sales Var], [PY YTD Sales] )",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY YTD GP",
            "expression": " CALCULATE([Total GP], FILTER('BRS_DS_Cube', BRS_DS_Cube[YTD]=\"YTD\" && BRS_DS_Cube[TimePeriod]=\"CY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PY YTD GP",
            "expression": " CALCULATE([Total GP], FILTER('BRS_DS_Cube', BRS_DS_Cube[YTD]=\"YTD\" && BRS_DS_Cube[TimePeriod]=\"PY\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Var",
            "expression": " ([CY YTD GP]-[PY YTD GP])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD GP Var%",
            "expression": " DIVIDE([YTD GP Var], [PY YTD GP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "CY YTD GM",
            "expression": " DIVIDE([CY YTD GP], [CY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "PY YTD GM",
            "expression": " DIVIDE([PY YTD GP], [PY YTD Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD GM Var",
            "expression": " ([CY YTD GM]-[PY YTD GM])",
            "formatString": "0.0%;-0.0%;0.0%"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "Exec BRS_DS_Cube_proc 0"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DS_Cube"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>Exec BRS_DS_Cube_proc 0</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "BRS_DS_Config",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "sourceColumn": "id",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "SalesDate",
            "dataType": "dateTime",
            "sourceColumn": "SalesDate",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DayNumber",
            "dataType": "int64",
            "sourceColumn": "DayNumber",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "DayType",
            "dataType": "string",
            "sourceColumn": "DayType",
            "sourceProviderType": "Char"
          },
          {
            "name": "DayStatusCd",
            "dataType": "int64",
            "sourceColumn": "DayStatusCd",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ExceptionCd",
            "dataType": "int64",
            "sourceColumn": "ExceptionCd",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "ExceptionNote",
            "dataType": "string",
            "sourceColumn": "ExceptionNote",
            "sourceProviderType": "WChar"
          },
          {
            "name": "LastWorkingDt",
            "dataType": "dateTime",
            "sourceColumn": "LastWorkingDt",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "PriorFiscalMonth",
            "dataType": "int64",
            "sourceColumn": "PriorFiscalMonth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "YearFirstFiscalMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "YearFirstFiscalMonth"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DS_Config",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT   id, SalesDate, FiscalMonth, DayNumber, DayType, DayStatusCd, ExceptionCd, ExceptionNote, LastWorkingDt, PriorFiscalMonth,YearFirstFiscalMonth",
                "FROM     BRS_DS_Config"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT   id, SalesDate, FiscalMonth, DayNumber, DayType, DayStatusCd, ExceptionCd, ExceptionNote, LastWorkingDt, PriorFiscalMonth,YearFirstFiscalMonth",
                  "FROM     BRS_DS_Config</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT   id, SalesDate, FiscalMonth, DayNumber, DayType, DayStatusCd, ExceptionCd, ExceptionNote, LastWorkingDt, PriorFiscalMonth,YearFirstFiscalMonth",
              "FROM     BRS_DS_Config"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DS_Config"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT   id, SalesDate, FiscalMonth, DayNumber, DayType, DayStatusCd, ExceptionCd, ExceptionNote, LastWorkingDt, PriorFiscalMonth,YearFirstFiscalMonth",
              "FROM     BRS_DS_Config</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "BRS_DS_GLBU_Rollup",
        "columns": [
          {
            "name": "GLBU_Class",
            "dataType": "string",
            "sourceColumn": "GLBU_Class",
            "sourceProviderType": "Char"
          },
          {
            "name": "GLBU_ClassNm",
            "dataType": "string",
            "sourceColumn": "GLBU_ClassNm",
            "sourceProviderType": "Char"
          },
          {
            "name": "ReportingClass",
            "dataType": "string",
            "sourceColumn": "ReportingClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "GLBU_ClassDS_L1_desc",
            "dataType": "string",
            "sourceColumn": "GLBU_ClassDS_L1_desc"
          },
          {
            "name": "GLBU_ClassDS_L1_sort",
            "dataType": "int64",
            "sourceColumn": "GLBU_ClassDS_L1_sort"
          },
          {
            "name": "GLBU_ClassDS_L2_desc",
            "dataType": "string",
            "sourceColumn": "GLBU_ClassDS_L2_desc"
          },
          {
            "name": "GLBU_ClassDS_L2_sort",
            "dataType": "int64",
            "sourceColumn": "GLBU_ClassDS_L2_sort"
          },
          {
            "name": "GLBU_ClassDS_L3_desc",
            "dataType": "string",
            "sourceColumn": "GLBU_ClassDS_L3_desc"
          },
          {
            "name": "GLBU_ClassDS_L3_sort",
            "dataType": "int64",
            "sourceColumn": "GLBU_ClassDS_L3_sort"
          },
          {
            "name": "GLBU_ClassDS_Reporting_desc",
            "dataType": "string",
            "sourceColumn": "GLBU_ClassDS_Reporting_desc"
          },
          {
            "name": "GLBU_ClassDS_Reporting_sort",
            "dataType": "int64",
            "sourceColumn": "GLBU_ClassDS_Reporting_sort"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DS_GLBU_Rollup",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": [
                "SELECT   GLBU_Class, GLBU_ClassNm, ReportingClass, GLBU_ClassDS_L1_desc, GLBU_ClassDS_L1_sort, GLBU_ClassDS_L2_desc, GLBU_ClassDS_L2_sort, GLBU_ClassDS_L3_desc, GLBU_ClassDS_L3_sort, GLBU_ClassDS_Reporting_desc, GLBU_ClassDS_Reporting_sort",
                "FROM     BRS_BusinessUnitClass"
              ],
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT   GLBU_Class, GLBU_ClassNm, ReportingClass, GLBU_ClassDS_L1_desc, GLBU_ClassDS_L1_sort, GLBU_ClassDS_L2_desc, GLBU_ClassDS_L2_sort, GLBU_ClassDS_L3_desc, GLBU_ClassDS_L3_sort, GLBU_ClassDS_Reporting_desc, GLBU_ClassDS_Reporting_sort",
                  "FROM     BRS_BusinessUnitClass</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT   GLBU_Class, GLBU_ClassNm, ReportingClass, GLBU_ClassDS_L1_desc, GLBU_ClassDS_L1_sort, GLBU_ClassDS_L2_desc, GLBU_ClassDS_L2_sort, GLBU_ClassDS_L3_desc, GLBU_ClassDS_L3_sort, GLBU_ClassDS_Reporting_desc, GLBU_ClassDS_Reporting_sort",
              "FROM     BRS_BusinessUnitClass"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DS_GLBU_Rollup"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT   GLBU_Class, GLBU_ClassNm, ReportingClass, GLBU_ClassDS_L1_desc, GLBU_ClassDS_L1_sort, GLBU_ClassDS_L2_desc, GLBU_ClassDS_L2_sort, GLBU_ClassDS_L3_desc, GLBU_ClassDS_L3_sort, GLBU_ClassDS_Reporting_desc, GLBU_ClassDS_Reporting_sort",
              "FROM     BRS_BusinessUnitClass</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "BRS_DS_PPE",
        "columns": [
          {
            "name": "CategoryRollupPPE",
            "dataType": "string",
            "sourceColumn": "CategoryRollupPPE",
            "sourceProviderType": "Char"
          },
          {
            "name": "ppe_descr",
            "dataType": "string",
            "sourceColumn": "ppe_descr",
            "sourceProviderType": "Char"
          },
          {
            "name": "ppe_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ppe_key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "disp_ppe_group_cd",
            "dataType": "string",
            "sourceColumn": "disp_ppe_group_cd"
          }
        ],
        "partitions": [
          {
            "name": "BRS_DS_PPE",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [dbo].[BRS_DS_PPE]",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT * FROM [dbo].[BRS_DS_PPE]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT * FROM [dbo].[BRS_DS_PPE]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_DS_PPE"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT * FROM [dbo].[BRS_DS_PPE]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "BRS_DS_Branch",
        "columns": [
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch",
            "sourceProviderType": "Char"
          },
          {
            "name": "BranchName",
            "dataType": "string",
            "sourceColumn": "BranchName",
            "sourceProviderType": "Char"
          },
          {
            "name": "StatusCd",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusCd",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "BranchKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BranchKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ZoneName",
            "dataType": "string",
            "sourceColumn": "ZoneName",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "BRS_Branch",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_Branch].[Branch],[dbo].[BRS_Branch].[BranchName],[dbo].[BRS_Branch].[StatusCd],[dbo].[BRS_Branch].[BranchKey],[dbo].[BRS_Branch].[ZoneName] FROM [dbo].[BRS_Branch] ",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Branch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>63</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BranchName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>102</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DefaultTerritoryCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AccountingCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BranchKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>112</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ZoneName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FSC_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>138</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ESS_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>77</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>bx_active_ind</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>97</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EPS_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>77</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>language_cd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PrivateLabelScopeInd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>134</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Branch</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BranchName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DefaultTerritoryCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AccountingCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BranchKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ZoneName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FSC_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ESS_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>bx_active_ind</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EPS_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>language_cd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PrivateLabelScopeInd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>DefaultTerritoryCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AccountingCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FSC_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ESS_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>bx_active_ind</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EPS_code</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>language_cd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>PrivateLabelScopeInd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_Branch].[Branch],[dbo].[BRS_Branch].[BranchName],[dbo].[BRS_Branch].[StatusCd],[dbo].[BRS_Branch].[BranchKey],[dbo].[BRS_Branch].[ZoneName] FROM [dbo].[BRS_Branch] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_Branch"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Branch</string>",
              "      </key>",
              "      <value>",
              "        <int>63</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BranchName</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>102</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DefaultTerritoryCd</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AccountingCode</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BranchKey</string>",
              "      </key>",
              "      <value>",
              "        <int>112</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ZoneName</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FSC_code</string>",
              "      </key>",
              "      <value>",
              "        <int>138</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ESS_code</string>",
              "      </key>",
              "      <value>",
              "        <int>77</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>bx_active_ind</string>",
              "      </key>",
              "      <value>",
              "        <int>97</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EPS_code</string>",
              "      </key>",
              "      <value>",
              "        <int>77</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>language_cd</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PrivateLabelScopeInd</string>",
              "      </key>",
              "      <value>",
              "        <int>134</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Branch</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BranchName</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DefaultTerritoryCd</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AccountingCode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BranchKey</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ZoneName</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FSC_code</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ESS_code</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>bx_active_ind</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EPS_code</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>language_cd</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PrivateLabelScopeInd</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>DefaultTerritoryCd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AccountingCode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FSC_code</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ESS_code</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>bx_active_ind</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EPS_code</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>language_cd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>PrivateLabelScopeInd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "BRS_AdjCode",
        "columns": [
          {
            "name": "AdjCode",
            "dataType": "string",
            "sourceColumn": "AdjCode",
            "sourceProviderType": "Char"
          },
          {
            "name": "AdjType",
            "dataType": "string",
            "sourceColumn": "AdjType",
            "sourceProviderType": "Char"
          },
          {
            "name": "AdjCodeDesc",
            "dataType": "string",
            "sourceColumn": "AdjCodeDesc",
            "sourceProviderType": "Char"
          },
          {
            "name": "AdjClass",
            "dataType": "string",
            "sourceColumn": "AdjClass",
            "sourceProviderType": "Char"
          },
          {
            "name": "StatusCd",
            "dataType": "int64",
            "sourceColumn": "StatusCd",
            "sourceProviderType": "SmallInt"
          },
          {
            "name": "MTDEstInd",
            "dataType": "boolean",
            "sourceColumn": "MTDEstInd",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceProviderType": "Boolean"
          },
          {
            "name": "AdjCodeKey",
            "dataType": "int64",
            "sourceColumn": "AdjCodeKey",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_AdjCode",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_AdjCode].[AdjCode],[dbo].[BRS_AdjCode].[AdjType],[dbo].[BRS_AdjCode].[AdjCodeDesc],[dbo].[BRS_AdjCode].[AdjClass],[dbo].[BRS_AdjCode].[StatusCd],[dbo].[BRS_AdjCode].[MTDEstInd],[dbo].[BRS_AdjCode].[AdjCodeKey] FROM [dbo].[BRS_AdjCode] ",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjType</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>123</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjCodeDesc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>143</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjLevel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjClass</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>71</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MTDEstInd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>124</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MTDEst_rt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjCodeKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>89</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjType</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjCodeDesc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjLevel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjClass</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MTDEstInd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MTDEst_rt</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjCodeKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>NoteTxt</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MTDEst_rt</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AdjLevel</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_AdjCode].[AdjCode],[dbo].[BRS_AdjCode].[AdjType],[dbo].[BRS_AdjCode].[AdjCodeDesc],[dbo].[BRS_AdjCode].[AdjClass],[dbo].[BRS_AdjCode].[StatusCd],[dbo].[BRS_AdjCode].[MTDEstInd],[dbo].[BRS_AdjCode].[AdjCodeKey] FROM [dbo].[BRS_AdjCode] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_AdjCode"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>AdjCode</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjType</string>",
              "      </key>",
              "      <value>",
              "        <int>123</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjCodeDesc</string>",
              "      </key>",
              "      <value>",
              "        <int>143</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjLevel</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjClass</string>",
              "      </key>",
              "      <value>",
              "        <int>71</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MTDEstInd</string>",
              "      </key>",
              "      <value>",
              "        <int>124</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MTDEst_rt</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjCodeKey</string>",
              "      </key>",
              "      <value>",
              "        <int>89</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>AdjCode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjType</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjCodeDesc</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjLevel</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjClass</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MTDEstInd</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MTDEst_rt</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjCodeKey</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>NoteTxt</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MTDEst_rt</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AdjLevel</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "BRS_SalesDivision",
        "columns": [
          {
            "name": "SalesDivision",
            "dataType": "string",
            "sourceColumn": "SalesDivision",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivisionDesc",
            "dataType": "string",
            "sourceColumn": "SalesDivisionDesc",
            "sourceProviderType": "Char"
          },
          {
            "name": "MarketClass_New",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MarketClass_New",
            "sourceProviderType": "Char"
          },
          {
            "name": "SalesDivision_key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesDivision_key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "BRS_SalesDivision",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[BRS_SalesDivision].[SalesDivision],[dbo].[BRS_SalesDivision].[SalesDivisionDesc],[dbo].[BRS_SalesDivision].[MarketClass_New],[dbo].[BRS_SalesDivision].[SalesDivision_key] FROM [dbo].[BRS_SalesDivision] ",
              "dataSource": "SqlServer CAHSIONNLSQL1 BRSales"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivision</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivisionDesc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>114</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClass_New</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>115</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AccountingCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivision_key</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>164</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>freegoods_exempt_cd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>138</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>freegoods_exempt_note</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>149</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivision</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivisionDesc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MarketClass_New</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AccountingCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SalesDivision_key</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>freegoods_exempt_cd</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>freegoods_exempt_note</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>StatusCd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AccountingCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>freegoods_exempt_cd</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>freegoods_exempt_note</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[BRS_SalesDivision].[SalesDivision],[dbo].[BRS_SalesDivision].[SalesDivisionDesc],[dbo].[BRS_SalesDivision].[MarketClass_New],[dbo].[BRS_SalesDivision].[SalesDivision_key] FROM [dbo].[BRS_SalesDivision] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "BRS_SalesDivision"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivision</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivisionDesc</string>",
              "      </key>",
              "      <value>",
              "        <int>114</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketClass_New</string>",
              "      </key>",
              "      <value>",
              "        <int>115</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AccountingCode</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivision_key</string>",
              "      </key>",
              "      <value>",
              "        <int>164</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>freegoods_exempt_cd</string>",
              "      </key>",
              "      <value>",
              "        <int>138</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>freegoods_exempt_note</string>",
              "      </key>",
              "      <value>",
              "        <int>149</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivision</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivisionDesc</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MarketClass_New</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AccountingCode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SalesDivision_key</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>freegoods_exempt_cd</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>freegoods_exempt_note</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>StatusCd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AccountingCode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>freegoods_exempt_cd</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>freegoods_exempt_note</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "c90095bf-b3b6-40b7-8b76-5ba06d433a81",
        "fromTable": "BRS_DS_Cube",
        "fromColumn": "MarketClass",
        "toTable": "BRS_DS_Market_Rollup",
        "toColumn": "MarketClass"
      },
      {
        "name": "8dd90abf-e260-4c19-b5d2-aa17f7dc573f",
        "fromTable": "BRS_DS_Cube",
        "fromColumn": "FiscalMonth",
        "toTable": "BRS_DS_Period",
        "toColumn": "FiscalMonth"
      },
      {
        "name": "7f83f126-8b00-4629-86ec-8dfd0b52fe58",
        "fromTable": "BRS_DS_Period",
        "fromColumn": "FiscalMonth",
        "toTable": "BRS_DS_Config",
        "toColumn": "FiscalMonth",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "88a5110f-db2b-4534-b65d-aee28fbd4350",
        "fromTable": "BRS_DS_Cube",
        "fromColumn": "GLBU_Class",
        "toTable": "BRS_DS_GLBU_Rollup",
        "toColumn": "GLBU_Class"
      },
      {
        "name": "b0d87bd3-8d08-452d-854a-0d88884b7162",
        "fromTable": "BRS_DS_Cube",
        "fromColumn": "ppe_key",
        "toTable": "BRS_DS_PPE",
        "toColumn": "ppe_key"
      },
      {
        "name": "af1743c2-1086-4c5a-b1fc-9adae94e32a8",
        "fromTable": "BRS_DS_Cube",
        "fromColumn": "Branch",
        "toTable": "BRS_DS_Branch",
        "toColumn": "Branch"
      },
      {
        "name": "dbb1196e-8613-41ae-87de-a9618dd244c7",
        "fromTable": "BRS_DS_Cube",
        "fromColumn": "AdjCode",
        "toTable": "BRS_AdjCode",
        "toColumn": "AdjCode"
      },
      {
        "name": "2e8da17d-f529-4d88-b74a-8d83e8d89747",
        "fromTable": "BRS_DS_Cube",
        "fromColumn": "SalesDivision",
        "toTable": "BRS_SalesDivision",
        "toColumn": "SalesDivision"
      }
    ],
    "roles": [
      {
        "name": "UserRole",
        "modelPermission": "readRefresh",
        "members": [
          {
            "memberName": "CAHSI\\TCrowley",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1815"
          },
          {
            "memberName": "CAHSI\\Gary.Winslow",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-1322"
          },
          {
            "memberName": "CAHSI\\JLi",
            "memberId": "S-1-5-21-2722441861-2609703027-3449782368-2414"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}